### ISSUE TITLE
type of other class gives error :: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by mayurbais** [jhipster/jhipster-uml#100]
Hi,
I have issue in following model, 

![image](https://cloud.githubusercontent.com/assets/9245684/12060920/2825aee4-af2e-11e5-894f-e173d78ce28e.png)

<h3>here , if I make language in schoolDetails of type LanguageLOV, I get error : </h3>

    Cannot read property 'name' of undefined
    TypeError: Cannot read property 'name' of undefined
    at null.<anonymous> (C:\Users\arjun\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:258:96)
    at Array.forEach (native)
    at ModelioParser.fillConstraints (C:\Users\arjun\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:242:34)
    at ModelioParser.parse (C:\Users\arjun\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:29:8)
    at Object.<anonymous> (C:\Users\arjun\AppData\Roaming\npm\node_modules\jhipster-uml\jhipster-uml.js:71:27)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

<h4>can you please help me debug this. 

<h4>content of my XMI file is : 

    <?xml version="1.0" encoding="UTF-8"?><uml:Model     xmlns:uml="http://www.omg.org/spec/UML/20110701" xmlns:xmi="http://schema.omg.org/spec/XMI/2.1" xmi:version="2.1" xmi:id="_l00fQK9wEeWWpIRXoeM4Aw" name="iris2">
  <eAnnotations xmi:id="_l00fQa9wEeWWpIRXoeM4Aw" source="Objing">
    <contents xmi:type="uml:Property" xmi:id="_l00fQq9wEeWWpIRXoeM4Aw" name="exporterVersion">
      <defaultValue xmi:type="uml:LiteralString" xmi:id="_l00fQ69wEeWWpIRXoeM4Aw" value="3.0.0"/>
    </contents>
  </eAnnotations>
  <ownedRule xmi:type="uml:Constraint" xmi:id="_l00fRK9wEeWWpIRXoeM4Aw" name="required" constrainedElement="_l00fR69wEeWWpIRXoeM4Aw">
    <specification xmi:type="uml:LiteralString" xmi:id="_l00fRa9wEeWWpIRXoeM4Aw" value="true"/>
  </ownedRule>
  <packagedElement xmi:type="uml:Class" xmi:id="_l00fRq9wEeWWpIRXoeM4Aw" name="SchoolDetails">
    <ownedAttribute xmi:type="uml:Property" xmi:id="_l00fR69wEeWWpIRXoeM4Aw" name="language" visibility="public" type="_l00fSa9wEeWWpIRXoeM4Aw" isUnique="false">
      <ownedComment xmi:type="uml:Comment" xmi:id="_l00fSK9wEeWWpIRXoeM4Aw">
        <body/>
      </ownedComment>
    </ownedAttribute>
  </packagedElement>
  <packagedElement xmi:type="uml:Class" xmi:id="_l00fSa9wEeWWpIRXoeM4Aw" name="LanguageLOV">
    <ownedComment xmi:type="uml:Comment" xmi:id="_l00fSq9wEeWWpIRXoeM4Aw">
      <body>&lt;Enter note text here&gt;</body>
    </ownedComment>
    <ownedAttribute xmi:type="uml:Property" xmi:id="_l00fS69wEeWWpIRXoeM4Aw" name="name" visibility="public" isUnique="false">
      <type xmi:type="uml:PrimitiveType" href="http://www.omg.org/spec/UML/20110701/PrimitiveTypes.xmi#String"/>
    </ownedAttribute>
    <ownedAttribute xmi:type="uml:Property" xmi:id="_l00fTK9wEeWWpIRXoeM4Aw" name="value" visibility="public" isUnique="false">
      <type xmi:type="uml:PrimitiveType" href="http://www.omg.org/spec/UML/20110701/PrimitiveTypes.xmi#String"/>
    </ownedAttribute>
  </packagedElement>
</uml:Model>

**Comment by MathieuAA** [comment]
Hello! I'm affraid UML class diagrams don't work like that. You were right when you made two classes, but instead of defining an object as an attribute (a LanguageLOVin SchoolDetails here) you have to create a relationship from SchoolDetails to LanguageLOV.

For instance, here's working a diagram for your case:
![example](https://i.imgur.com/ekqRaXs.png)

Notice the absence direction of the relationship (from ScoolDetails to LanguageLOV) and the absence of a named value for SchoolDetails indicating that LanguageLOV doesn't know its SchoolDetails, but SchoolDetails can access its languageLOV attribute.

**Comment by mayurbais** [comment]
thanks.
But I tried this with UMLdesigner and it works for that .

And this solves my purpose.

Also, One more thing, the latest  Jhipster-sample-app on git hub has some
error, When I use jhipster-uml in that app, it adds the entry for new
entity in master.xml of liquibase at the top ,  which fails when server is
started,

Can you pls look into it.


Regards,
Mayur
(c)323-873-2822

**Comment by MathieuAA** [comment]
First of, happy new year man!
Now for the ugly part of my answer: it _may_ have worked with UML Designer, but it is still not correct.
If you're having a problem with Liquibase or the JHipster generator, I suggest you ask the fantastic JHipster team for help. I'll look into it later to see if there's an issue with JHipster-UML.

**Comment by mayurbais** [comment]
thanks.! :)
and Happy new year to you too :) Its amazed to see that, U reply on the new
year's eve too :)

Regards,
Mayur
(c)323-873-2822

On Fri, Jan 1, 2016 at 1:00 AM, Mathieu ABOU-AICHI <notifications@github.com

**Comment by mayurbais** [comment]
Hi,
did exactly what you suggested, and it worked and generated all the code.
it created  following code  in SchoolDetails class. along with other member variables.

      @OneToOne
        private CountryLOV countryLOV;



but now, when I try to insert a a new school details.

It creates a insert statement, with column id as "countrylov_id"

where as the actual column that got created in DB is "country_lov_id", and hence the insert fails.

is it beacause of the nomenclature of the class , "CountryLOV," should it be "Countrylov" ?
