### ISSUE TITLE
Cannot read property 'name' of undefined for enumeration type+  Modelio.

### ISSUE THREAD

**Issue by mayurbais** [jhipster/jhipster-uml#101]
![image](https://cloud.githubusercontent.com/assets/9245684/12077521/a12610a2-b19c-11e5-90e6-d682ddd6a8de.png)

daigram like above, also gives me the error, "Cannot read property 'name' of undefined"

Can you suggest me the proper way of using enums...actully this also worked with uml designer.

**Comment by MathieuAA** [comment]
Yes but both editors are very different (and UML Designer does thing differently which, in this case, is a bad thing).

Here's how you use enums:

![enumexample](https://i.imgur.com/WrBHEUn.png)

You don't use the usual attributes but the "Enumeration Literal" in Modelio.
Please, re-use the same issue thread as last time.

**Comment by mayurbais** [comment]
Thanks.

Regards,
Mayur
(c)323-873-2822

On Sun, Jan 3, 2016 at 2:01 AM, Mathieu ABOU-AICHI <notifications@github.com
