### ISSUE TITLE
mismatched column id

### ISSUE THREAD

**Issue by mayurbais** [jhipster/jhipster-uml#103]
Hi,
did exactly what you suggested, in issue https://github.com/jhipster/jhipster-uml/issues/100 and it worked and generated all the code.
it created  following code  in SchoolDetails class. along with other member variables.

      @OneToOne
        private CountryLOV countryLOV;

but now, when I try to insert a a new school details.

It creates a insert statement, with column id as "countrylov_id"

where as the actual column that got created in DB is "country_lov_id", and hence the insert fails.

is it beacause of the nomenclature of the class , "CountryLOV," should it be "Countrylov" ?

**Comment by mayurbais** [comment]
I commented this:
 //naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

in application-dev, and now column names in db and entity are consistent

**Comment by MathieuAA** [comment]
Hi, if you had to change something in the generated app then:
  - It was a mistake;
  - JHipster-UML is _probably_ at fault here.

I'll investigate this further.

**Comment by mayurbais** [comment]
okay. Thanks.

**Comment by MathieuAA** [comment]
I think you're right. There is something wrong with the names. Just tested the example of a unidirectional One-to-One relationship with normal names, and it worked...
However your example doesn't even pass the tests (`mvn test`).
I suggest you open an issue on JHipster's project.
