### ISSUE TITLE
inline create-form 

### ISSUE THREAD

**Issue by mayurbais** [jhipster/jhipster-uml#104]
Hi,
So far, uml is been working out great for me.
I have a question,

I want to create a entity called "AdmissionDetails" and "Student".
I can create these two entities in two separate forms . Then may be select a student, from a drop-down on create admission details page. and link the two. (one to one).

Is there any way, that I can create student, while creating admission details, 
as something like create a student in the background, while creating admission detail, by inject student related field on  create admission detail form.

**Comment by MathieuAA** [comment]
Yes, you can (no copyright infringement intended). By the same way JHipster enables you to create each entity separately. What is preventing you from actually "merging" two forms? (the term "merging" may not be appropriate, but it's an idea...).

It's not a question about JHipster-UML, but you can do anything with what JHipster generates (have a look at what the JS code does when creating an entity, and how it involves the Java part).

**Comment by mayurbais** [comment]
yes. I merged the two js forms generated by that entity generator , and did it..thats how we used to do in our traditional ways.  before auto-generation tools :)  .. I was wondering is there automotive way of doing this, like introducing one more question  when generating-entity or reading some link in the UML diagram.

**Comment by MathieuAA** [comment]
I doubt it. JHipster only generates the basic form. And it's not in JHipster-UML's scope to do it.

**Comment by mayurbais** [comment]
yup!

Regards,
Mayur
(c)323-873-2822

On Thu, Jan 7, 2016 at 3:25 AM, Mathieu ABOU-AICHI <notifications@github.com

**Comment by mayurbais** [comment]
not sure, this will also count as "wish list items", but , 
when you associate one entity to other, we can give name to that association in modelio.
when entity is generated, it assumes the default name (name of the other entity )for the join column , can we use the association name instead.

ex:  student has relation ship with self, I named it in association name as "sibling", but in the entity class, I see
  
    @OneToMany(mappedBy = "student")
    private Set<Student> students = new HashSet<>();

I know, I can go ahead and change in the js and classes, and translation jsons and every where.. but would be good, if we do this.

**Comment by MathieuAA** [comment]
I thought it was working... Open an issue with your last comment. I'll see why you had this...

**Comment by mayurbais** [comment]
ok.
