### ISSUE TITLE
association name as relationship column name

### ISSUE THREAD

**Issue by mayurbais** [jhipster/jhipster-uml#105]
Not sure, this will also count as "wish list items", but , 
when you associate one entity to other, we can give name to that association in modelio.
when entity is generated, it assumes the default name (name of the other entity )for the join column , can we use the association name instead.

ex:  student has relation ship with self, I named it in association name as "sibling", but in the entity class, I see
  
    @OneToMany(mappedBy = "student")
    private Set<Student> students = new HashSet<>();

I know, I can go ahead and change in the js and classes, and translation jsons and every where.. but would be good, if we do this., which means something like

    @OneToMany(mappedBy = "student")
    private Set<Student> siblings= new HashSet<>();

**Comment by MathieuAA** [comment]
Like I said in #106, the new parsed data system is finished. If you want to test it here are the commands (I'll merge the branch after some tests are implemented).

**Comment by MathieuAA** [comment]
I've just released a new version, if you wanna test it =)

**Comment by MathieuAA** [comment]
I'd like to close this thread, can you you confirm your problem is solved?
