### ISSUE TITLE
The entity name cannot end with 'Detail'

### ISSUE THREAD

**Issue by mayurbais** [jhipster/jhipster-uml#107]
I am getting this "The entity name cannot end with 'Detail'  " (  Error("Validation error"); ) for one of my entity whose name does ends in "Details" . 

Any reason for this?

**Comment by MathieuAA** [comment]
Is it Detail or Details?

**Comment by mayurbais** [comment]
"PrevSchoolDetail" ==> gives error

"PrevSchoolDetails" == > works

**Comment by mayurbais** [comment]
one more issue, : If in Student class I have this kind of relation ship,

       @OneToMany(mappedBy = "student")
       @JsonIgnore
       @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
       private Set<Parent> parents = new HashSet<>();

I should expect, multiselect drop down in the create-student form for linking "parents", but I am getting a dropdown with parent ids.

**Comment by MathieuAA** [comment]
Must be a reserved word. I can't check that right now. Probably tomorrow or tonight at best.

**Comment by mayurbais** [comment]
thats fine..I can change my entity name, but issues like this is urgent :

https://github.com/jhipster/jhipster-uml/issues/108

I will change the js forms , but if you give me solution for above problem,
then changing the generated form wont be right way..


Regards,
Mayur
(c)323-873-2822

On Fri, Jan 8, 2016 at 1:12 AM, Mathieu ABOU-AICHI <notifications@github.com

**Comment by MathieuAA** [comment]
Detail is a reserver keyword, see [this](https://github.com/jhipster/generator-jhipster/blob/master/entity/index.js#L104) for more information. Or ask the JHipster team for details about that.

**Comment by jdubois** [comment]
Yes that's because we generate AngularJS routes which are named "detail", and so that makes us have errors in the AngularJS code

**Comment by mayurbais** [comment]
okay.
makes sense

Regards,
Mayur
(c)323-873-2822
