### ISSUE TITLE
drop-down for oneToMany 

### ISSUE THREAD

**Issue by mayurbais** [jhipster/jhipster-uml#108]
one more issue, : If in Student class I have this kind of relation ship,

       @OneToMany(mappedBy = "student")
       @JsonIgnore
       @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
       private Set<Parent> parents = new HashSet<>();

I should expect, multiselect drop down in the create-student form for linking "parents", but I am getting a dropdown with parent ids.

My UML daigram is : 

![image](https://cloud.githubusercontent.com/assets/9245684/12193471/95fa6552-b59d-11e5-88a0-0807604ddcee.png)

**Comment by MathieuAA** [comment]
Invert the names maybe?

**Comment by mayurbais** [comment]
as in?

**Comment by MathieuAA** [comment]
You named one end to be `student`, the other `sibling` (the reflexive case, the one that Modelio fails to properly renders in your screenshot). Would inverting the names work?

**Comment by MathieuAA** [comment]
Is it working?
