### ISSUE TITLE
sample XMI file..

### ISSUE THREAD

**Issue by mayurbais** [jhipster/jhipster-uml#109]
Hi, 
I think many people are requesting it. and it will also minimize the constant / duplicate questions in uml issue list. 
Can you please provide the sample XMI file for the example given in "A complete example" section of 
http://jhipster.github.io/jhipster_uml.html. So that we can refer to it, and understand easily correct ways of doing things.

will be of great help.

**Comment by MathieuAA** [comment]
Of course. Just go [there](https://github.com/jhipster/jhipster-uml/tree/master/test/xmi). This is where we keep our XMI files. For instance, if you'd want to see how the example is generated with Modelio, the file to use would be [modelio.xmi](https://github.com/jhipster/jhipster-uml/blob/master/test/xmi/modelio.xmi).

I'll add it to the doc, thanks.

**Comment by mayurbais** [comment]
Thanks  a ton. 
I searched at lot many places for this then posted this one.
 forgot to look at the test folder...sorry.

**Comment by MathieuAA** [comment]
Don't be. You were right to post an issue.
