### ISSUE TITLE
two properties of the same class

### ISSUE THREAD

**Issue by mayurbais** [jhipster/jhipster-uml#110]
I have two classes.
1) Attendance  and 2) User

in attedance class, I want to create two property of type User,

private User attedanceFor
private User approvedFor,

so for this I need to create two, one-to-one relationships with user class?   but it creates two 
property with the same name which fails when compiled. 

Is there way around? 

is it related to, https://github.com/jhipster/jhipster-uml/issues/105 ?

**Comment by mayurbais** [comment]
I saw this, in umldesigner_parser.js,

      case 'uml:PrimitiveType':
      case 'uml:DataType':
        this.rawTypesIndexes.push(index);

whereas in modelio_parser.js 

      case 'uml:PrimitiveType':
        this.rawTypesIndexes.push(index);

so, is there any way we read, classes also as types, in modelio?
by which we can add a property to a class as type of some other class, and may be solve this a umldesginer way? (too much to ask? or is it incorrect?)

**Comment by MathieuAA** [comment]
Not really. UML Designer does thing differently (one can also say weirdly). Classes in UML Designer are `uml:Class`.
And yes, it is incorrect from a UML viewpoint. I admit it would be easier to do it like that, but some editors don't support this (rightly so).

And yes, it is related. Don't know why it doesn't work, I thought I fixed it. When I have the time, I'll fix that...

**Comment by MathieuAA** [comment]
Work is being done in the new_parsed_branch.

**Comment by mayurbais** [comment]
yes.
Much thanks.
Its working.

Regards,
Mayur
(c)323-873-2822
