### ISSUE TITLE
generalization relationship association.

### ISSUE THREAD

**Issue by mayurbais** [jhipster/jhipster-uml#111]
What should we expect in our generated entities if we are using generalization relationship?
ex: 
If I have a class "CustomUser" and  other class "SystemUser" and 
Custom User has generalization relationship with SystemUser, (just like BugFixing class has with Task in sample Modelio xmi ) should we expect entities to have "extends " declaration or any other kind of generated code?

for now it does not do anything.

**Comment by MathieuAA** [comment]
Yes it's normal. JHipster doesn't support inheritance with the Q&As just yet. We are prepared to support it as soon as the generation does.

**Comment by mayurbais** [comment]
ok.
