### ISSUE TITLE
JDL paginate option keyword not being recognized by the jhipster-uml

### ISSUE THREAD

**Issue by david-vasquez** [jhipster/jhipster-uml#113]
The JDL `paginate` option keyword is not being recognized by jhipster-uml (v1.5.2) as mentioned in the documentation.

This is my `db.jh` sample file:
```
entity Reader{ name String required}
paginate Reader with pager
```
Running the command `jhipster-uml db.jh` I got the following error message:
```
Expected "/**", "entity", "enum", "relationship", a space or end of input but "p" found.
SyntaxError: Expected "/**", "entity", "enum", "relationship", a space or end of input but "p" found.
...
```
Am I missing something in my JDL file?

**Comment by MathieuAA** [comment]
Hi, that's normal. I changed the doc before the change was effective. It will be before the end of the week. Sorry for the incovenience!

**Comment by david-vasquez** [comment]
Thanks, just realized the following text in the documentation 
*As of JHipster-UML v1.6.0,...*

Looking forward for the new release!

**Comment by MathieuAA** [comment]
A lot of people are (me included I must say).

**Comment by david-vasquez** [comment]
Hi Mathieu,

I´ve just installed the long awaited 1.6.0 version. However, I still get the same parser error when trying to use the 'pagination' option:
'Expected "/**", "entity", "enum", "relationship", a space or end of input but "p" found.'

Any ideas?

**Comment by MathieuAA** [comment]
You may still have v1.5.2 installed and is conflicting with v1.6.0.
