### ISSUE TITLE
Modelio does not set type uml:Constraint when generating xmi

### ISSUE THREAD

**Issue by 2J** [jhipster/jhipster-uml#114]
![modelio](https://cloud.githubusercontent.com/assets/3698091/12401638/c88ea2c0-bdf5-11e5-85bf-abfd4853d135.PNG)

This is a sample entity that I made in modelio with a constraint of minlength 4. 

Here is the xmi generated from this uml:

```
<?xml version="1.0" encoding="UTF-8"?>
<uml:Model xmi:version="2.1" xmlns:xmi="http://schema.omg.org/spec/XMI/2.1" xmlns:uml="http://www.eclipse.org/uml2/3.0.0/UML" xmi:id="_J2yYAL4fEeWDruD32SL_AQ" name="test">
  <eAnnotations xmi:id="_J2yYAb4fEeWDruD32SL_AQ" source="Objing">
    <contents xmi:type="uml:Property" xmi:id="_J2yYAr4fEeWDruD32SL_AQ" name="exporterVersion">
      <defaultValue xmi:type="uml:LiteralString" xmi:id="_J2yYA74fEeWDruD32SL_AQ" value="3.0.0"/>
    </contents>
  </eAnnotations>
  <ownedRule xmi:id="_J2yYBL4fEeWDruD32SL_AQ" name="minlength" constrainedElement="_J2yYB74fEeWDruD32SL_AQ">
    <specification xmi:type="uml:LiteralString" xmi:id="_J2yYBb4fEeWDruD32SL_AQ" value="4"/>
  </ownedRule>
  <packagedElement xmi:type="uml:Class" xmi:id="_J2yYBr4fEeWDruD32SL_AQ" name="testclass">
    <ownedAttribute xmi:id="_J2yYB74fEeWDruD32SL_AQ" name="name" visibility="private" isUnique="false">
      <type xmi:type="uml:PrimitiveType" href="pathmap://UML_LIBRARIES/UMLPrimitiveTypes.library.uml#String"/>
    </ownedAttribute>
  </packagedElement>
</uml:Model>
```

This xmi does not work because for the ownedRule element, this is missing: ```xmi:type="uml:Constraint"```

Because the element is missing, line 59 in [modelio_parser.js](https://github.com/jhipster/jhipster-uml/blob/master/lib/editors/modelio_parser.js#L59) never runs, and I get this error when I try to import it:

```
Parser detected: MODELIO.

Cannot read property '$' of undefined
TypeError: Cannot read property '$' of undefined
    at null.<anonymous> (C:\Users\anon.ymous\AppData\Roaming\npm\node_modules\jhipster-uml\lib\ed
itors\modelio_parser.js:244:26)
    at Array.forEach (native)
    at ModelioParser.fillConstraints (C:\Users\anon.ymous\AppData\Roaming\npm\node_modules\jhipst
er-uml\lib\editors\modelio_parser.js:242:34)
    at ModelioParser.parse (C:\Users\anon.ymous\AppData\Roaming\npm\node_modules\jhipster-uml\lib
\editors\modelio_parser.js:29:8)
    at Object.<anonymous> (C:\Users\anon.ymous\AppData\Roaming\npm\node_modules\jhipster-uml\jhip
ster-uml.js:71:27)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
```

Not sure if I made a mistake when making the constraint or missed an option, but I wasn't able to find anything in Modelio to set the type to Constraint manually.

**Comment by 2J** [comment]
If I add ```xmi:type="uml:Constraint"``` attribute manually, it creates this xmi:

```
<?xml version="1.0" encoding="UTF-8"?>
<uml:Model xmi:version="2.1" xmlns:xmi="http://schema.omg.org/spec/XMI/2.1" xmlns:uml="http://www.eclipse.org/uml2/3.0.0/UML" xmi:id="_J2yYAL4fEeWDruD32SL_AQ" name="test">
  <eAnnotations xmi:id="_J2yYAb4fEeWDruD32SL_AQ" source="Objing">
    <contents xmi:type="uml:Property" xmi:id="_J2yYAr4fEeWDruD32SL_AQ" name="exporterVersion">
      <defaultValue xmi:type="uml:LiteralString" xmi:id="_J2yYA74fEeWDruD32SL_AQ" value="3.0.0"/>
    </contents>
  </eAnnotations>
  <ownedRule xmi:type="uml:Constraint" xmi:id="_J2yYBL4fEeWDruD32SL_AQ" name="minlength" constrainedElement="_J2yYB74fEeWDruD32SL_AQ">
    <specification xmi:type="uml:LiteralString" xmi:id="_J2yYBb4fEeWDruD32SL_AQ" value="4"/>
  </ownedRule>
  <packagedElement xmi:type="uml:Class" xmi:id="_J2yYBr4fEeWDruD32SL_AQ" name="testclass">
    <ownedAttribute xmi:id="_J2yYB74fEeWDruD32SL_AQ" name="name" visibility="private" isUnique="false">
      <type xmi:type="uml:PrimitiveType" href="pathmap://UML_LIBRARIES/UMLPrimitiveTypes.library.uml#String"/>
    </ownedAttribute>
  </packagedElement>
</uml:Model>

```

and jhipster-uml successfully creates the entity with the correct validation.

**Comment by MathieuAA** [comment]
Interesting. Although this doesn't concern JHipster-UML, this is clearly something to be aware of.
Can you tell me the version of Modelio you used?

**Comment by 2J** [comment]
Yeah, I wasn't sure if it was appropriate to open an issue here but I didn't know where else to report it. 

Modelio version:

Version 3.4.1  
Build: 201512081403  
System: win32 (6.1)  
Architecture: x86_64

**Comment by MathieuAA** [comment]
I've just tested it (I did everything you did, maybe not in the same order), and I couldn't reproduce it.
What are the export options you used?

**Comment by 2J** [comment]
May I ask how you added the constraint to the attribute? 

the export option I used was the default one, with deselected "Adding modelio annotation" and compatibility "EMF UML3.0.0"

**Comment by MathieuAA** [comment]
You used the wrong export option. You should have used the `OMG UML2.4.1` instead of the EMF.
You did everything right apart from this little detail (I assume you added a constraint then added its name and its body).

**Comment by 2J** [comment]
You're right, it worked. I guess I misread the instructions on the JHipster-UML page. Sorry about that. Thank you very much!

**Comment by MathieuAA** [comment]
You're welcome
