### ISSUE TITLE
Create an entity with a relationship to an existing entity

### ISSUE THREAD

**Issue by david-vasquez** [jhipster/jhipster-uml#118]
I'm trying to create a new entity with a relationship to an existing entity. However I got an error message signaling that the existing entity (in this case "Person") is not declared.
`C:\Projects\testjhipster>jhipster-uml .jhipster-uml\PersonBudParticipation.jh In the association Person_participation_to_PersonBudParticipation_person, the entity Person is not declared.`
Do I need to "declare" the existing entity explicitly (e.g. with no field), so I can use it in a relationship?
This is weird since I've already created an entity with a relationship to the User entity and did not need to declare it.

Please advice.

**Comment by MathieuAA** [comment]
Person has to be declared. The User entity is special because it is used by JHipster.

**Comment by david-vasquez** [comment]
I´ve declared Person in the .jh file (removing the fields) as follows:
´entity Person {
}`
As expected, the generator, asked if I wanted to overwrite the previously generated Person* files. 
I told the generator not to for every single file, except for the new entity.

Is this the usual way to create a new entity with a relationship to an existing one (i.e. by declaring again the existing entity as "empty")?

Please let me know if I'm missing something or confirm that the described procedure above is actually the usual way. 

Tks in advance!

**Comment by MathieuAA** [comment]
Yes it is. You just have to declare it once:

    entity ENTITY_1_NAME {}
    entity ENTITY_2_NAME {}
    ...
    entity ENTITY_N_NAME {}

This could be improved by not writing the curly braces like:

    entity ENTITY_1_NAME
    entity ENTITY_2_NAME
    ...
    entity ENTITY_N_NAME

Or better yet:

    entity ENTITY_1_NAME, ENTITY_2_NAME, ..., ENTITY_N_NAME

And if they each have an attribute with the same name:

    entity ENTITY_1_NAME, ENTITY_2_NAME, ..., ENTITY_N_NAME {
        attributeName attributeType [attributeConstraints] 
    }

However, I am against not declaring it as this could lead to mistakes.
There clearly is room for improvement here, and the grammar will be changed in the future and its changes are open for debate.

Would one of the solutions be cool and practical enough for you?

**Comment by david-vasquez** [comment]
I think it's ok to just declare an "empty" entity for your existing entities just for the sake of clarity when creating a new entity that needs to be related to the existing one, 

However, the point is that the generator detects that the "empty" entity already exists, as if it was a "redefinition" of the existing entity. So the user has to manually tell the generator not to replace the previously generated files for that "empty" declared entity. That was confusing on my first try.

As for the syntax, removing the curly braces would be nice, to avoid confusion with the actual definition of an entity that was previously generated. Moreover, it would be also nice if the generator could detect that the entity with no curly braces is just a declaration of existing ones, and therefore should not ask to recreate it all over again. 

What do you think?

**Comment by MathieuAA** [comment]
If the first version of your JDL file (or XMI file incidentally) contains some entites that aren't changed in the second version, they won't be rewritten (default behavior).
By "changed" I mean:
  - No difference in the attributes,
  - And no difference in the relationships (whether the entity is a source or a destination, the relationship must stay **exactly** the same so as not be rewritten).

I don't want that a change in the syntax over two versions of a JDL file to mean that a side effect must happen (here the side effect is keeping the entity).
The JDL file must stay consistent and represent the entities. We shouldn't interpret the JDL as a versioning language (or something like Liquibase).

If, however, the change detection system doesn't work, I'll fix it.

**Comment by david-vasquez** [comment]
I see your point. I think I was using the JDL incorrectly, since I was creating new JDL files to create new entities progressively. But indeed, we just need to work with a single file that contains all entities in your app, and use it every time we need to create a new entity.

As for the relations, if a new relation is needed for an already existing entity, i think the generator will detect that change and suggest to overwrite your exisitng Liquibase change file for that entity. In that case, I assume you have to tell the generator not to overwrite, but instead, you need to run liquibase:diff instead to update your database. Correct?

**Comment by MathieuAA** [comment]
JHipster UML will (**should**) detect a change and will do a `yo jhipster:entity YOUR_ENTITY` to update that entity. If no change is detected, nothing is (again, **should be**) done.
We don't use `liquibase:diff`. We diff with the JSON file. We could diff with what Liquibase returns... but I never bothered to check. It may be a good idea (but we'd have to pipe the output to a file, read the file assuming it is supposed to be read programatically, and interpret the changes).
