### ISSUE TITLE
Question: Using JDL to specify entity options

### ISSUE THREAD

**Issue by amitjindal** [jhipster/jhipster-uml#119]
Hi from example, I can use the following structure to specify options for generating the entities. However it is difficult to specify each entity in all of these. Say I have around 65 entities. Can I specify a star or all option?

So how do I specify something like:
```
dto * with mapstruct
paginate * with pager
service * with serviceImpl
```
or 
```
dto ALL with mapstruct
paginate ALL with pager
service ALL with serviceImpl
```

**Comment by MathieuAA** [comment]
Hi, no you can't at the moment. However, I agree it would be nice to have that. I'm going to implement it and include it in the next release.

**Comment by MathieuAA** [comment]
I think it would be nice to have some exclusion option like : `<OPTION> (all, *) except [] with <OPTION_ITEM>`.

**Comment by amitjindal** [comment]
While exclusions are rarely used in a single project, Yes, I think exclusions will be valuable.

**Comment by MathieuAA** [comment]
For v1.6.1, I'll ship the `all` or `*` option.
I'll add the exclusion in v1.6.2 (and make a new issue out of it).
