### ISSUE TITLE
How to add relationships to existing entities?

### ISSUE THREAD

**Issue by dhafirnz** [jhipster/jhipster-uml#124]
How can we add relationships to existing entities? I guess if I have an existing entity called "Address" and I want to add a new entity say called "Supplier" with One-To_Many relationship with entity Address, do we add a class Address to the UML model? Would that be accepted ? If not, what is the best way?
I guess my question is that, do we have only one shot in using Jhipster-UML to define our domain or we can use it incrementally?

**Comment by MathieuAA** [comment]
You don't have one shot. You can use it as many times as you like =)
