### ISSUE TITLE
Support of several JDL files

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-uml#125]
From the last meetup: it would be nice to have and use more than one JDL file when generating entities.

**Comment by david-vasquez** [comment]
Indeed, that would be a nice feature, so you can just create a new file when you need to add new entities to your application. Relationships to existing entities should not require including them again, just like relationships to the User entity do not require to include the User entity.

BR

**Comment by MathieuAA** [comment]
This could "break" the change introduce by #135.
One would have to concatenate the JDL files to see where an error is...
