### ISSUE TITLE
Fields with 'Id' suffix are ignored

### ISSUE THREAD

**Issue by javasparx** [jhipster/jhipster-uml#126]
Hi guys,

jhipster-uml version: 1.6.0
e.g. 
**models.jh**
```
entity Merchant{
    extRef String,
    extId String
}
```
**Merchant.json**
```
{
  "relationships": [],
  "fields": [
    {
      "fieldId": 1,
      "fieldName": "extRef",
      "fieldType": "String"
    }
  ],
  "changelogDate": "20160128063412",
  "dto": "no",
  "pagination": "no",
  "service": "no"
}
```

**Comment by MathieuAA** [comment]
Hi, it is the desired behavior as JHipster generates an id field itself.

**Comment by andidev** [comment]
Though it is possible to create other fields with name ending with Id. At least I hope JHipster  supports that. Otherwise it is a bug.

**Comment by MathieuAA** [comment]
Well, a bug is something you don't expect to happen. We kept the id fields out of the pool of generated attributes because JHipster correctly handles ids. However, I agree: if a user wants to create another id field, he should be allowed to do that... I'll remove this from the code but still forbid `id` fields (with the exact same name) from being created though.

**Comment by MathieuAA** [comment]
It will be available with v1.6.1 (which shouldn't take too long to be released).

**Comment by ouyangshixiong** [comment]
waiting for the issue to be fixed.

**Comment by jdubois** [comment]
@ouyangshixiong we all do this on our free time, so it's going to be fixed when someone has got the time to do it.

**Comment by MathieuAA** [comment]
@ouyangshixiong As I said, it's fixed and will be released soon (before the end of the week if I find the time). And as @jdubois said, we all do this on our free time (and this is the case for this project). So please, be patient (you can see the state for this milestone pretty easily, if you want to know what still needs to be done before we release).
