### ISSUE TITLE
The --regenerate keyword

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-uml#127]
See [this](https://github.com/jhipster/generator-jhipster/pull/2703).

**Comment by cbornet** [comment]
It will be [--regenerate](https://github.com/jhipster/generator-jhipster/pull/2712)

**Comment by MathieuAA** [comment]
Thank you =)

**Comment by MathieuAA** [comment]
Done as of 6094910

**Comment by david-vasquez** [comment]
Is the `--regenerate` option set by default? or do we need to include it explicitly to avoid overwriting?

**Comment by MathieuAA** [comment]
It is an option, so yes: you need to explicitely use it.
The only exception is for the first-time case where it is done without the user's knowing.

**Comment by david-vasquez** [comment]
I read the entirely thread at jhipster, but for me it is still confusing. Could you please describe the behavior when the --regenerate option is used with jhipster-uml?

If not used, will it run as in the previous version? if so, what will be the benefit of using the option?

**Comment by MathieuAA** [comment]
When you use JUML for the first time, this option is passed, even if you don't manually add it, in order to correctly generate everything without having to answer any question (because JHipster notices you have a .jhipster/XXX.json file, and asks if you want to change it).
If you don't pass it (after the first time use), you won't be asked whether you want to modify the entity, but JHipster will read what's in the JSON files, and **regenerate** your entities from scratch. I hope it is clear, if not I'll explain in greater length.

**Comment by david-vasquez** [comment]
Let me see if I understood by stating the other alternative:

When you **do** pass the --regenerate option (after the first time use) then you will be asked if you want to modify your entity.

In other words, you pass the `--regenerate` option not to tell JHipster to *regenerate*, but to let JHipster ask you if you want to regenerate. Otherwise, JHipster will regenerate without asking (as you stated above). 

Is this correct? or am I still missing something :)

**Comment by MathieuAA** [comment]
It's the opposite.

**Comment by cbornet** [comment]
@MathieuAA Why don't you always set the --regenerate ? The JHipster questions have no interest when you use Jhipster-uml !

**Comment by david-vasquez** [comment]
I think is good for the user to choose whether he wants to regenerate or not, specially after the first time use. So JHipster questions are actually good for the user that just wants to update his existing entities.

**Comment by cbornet** [comment]
But with jhipster-uml, you update your entities in jhipster-uml, not with questions, ...

**Comment by david-vasquez** [comment]
in that sense you are right, but I was referring to the **overwriting** questions.

**Comment by MathieuAA** [comment]
I guess I added the flag without really thinking about this. I'll fix it for v1.6.2. Thanks @cbornet.
