### ISSUE TITLE
Required Relationship Attribute in JDL

### ISSUE THREAD

**Issue by objectArtz** [jhipster/jhipster-uml#128]
Hi, in JDL i would like to mark a relationship attribute in my entity as required. Until no I manually set the @NotNull annotation at the relation attribute in the class. 

It would be nice to have some "required"-expression like:

relationship ManyToOne {
	Foo{bar} to Bar required
}

There has already been posted an issue in JHipster repository (https://github.com/jhipster/generator-jhipster/issues/1859). I understand that the entity generator should not get an extra question for this feature, but from my point of view it would make sense to integrate it in JDL.

**Comment by MathieuAA** [comment]
As Julien closed the issue, there is no point at all that I further develop what he was trying to say.
As far as JHipster UML is concerned, we won't add something JHipster doesn't add.
If we add it, this change will not be propagated to what JHipster generates (because it will simply ignore it.
