### ISSUE TITLE
Length of value DEFAULT_*FIELD* does not match with validation maxlength

### ISSUE THREAD

**Issue by javasparx** [jhipster/jhipster-uml#129]
```
entity Currency{
    date LocalDate required,
    rate BigDecimal required,
    code String maxlength(3),
    valid Boolean
}
```
Hi guys,
I did not check minlength(L>5) but I think it has same problem.

**Currency.java**
```
...
    @Size(max = 3)
    @Column(name = "code", length = 3)
    private String code;
...
```

**CurrencyResourceIntTest.java**
```
...
private static final String DEFAULT_CODE = "AAAAA";
private static final String UPDATED_CODE = "BBBBB";
...
@Before
public void initTest() {
        currency = new Currency();
        currency.setDate(DEFAULT_DATE);
        currency.setRate(DEFAULT_RATE);
        currency.setCode(DEFAULT_CODE); // <---
        currency.setValid(DEFAULT_VALID);
}
```

java.lang.AssertionError: Status 
Expected :201
Actual   :400

**Comment by MathieuAA** [comment]
Hello, there is absolutely no problem with JHipster UML (for once =p).
This is likely a JHipster issue, and you should post about this in JHipster's issue tracker.

**Comment by MathieuAA** [comment]
Oops deleted my last post. As I said, there's no problem with what JHipster UML generates (for once =p).
As this is likely a JHipster issue, you should post about it in JHipster's issue tracker.

**Comment by javasparx** [comment]
Thanks @MathieuAA )))
