### ISSUE TITLE
Warn and Exception when checkValidityOfAssociation don't name relation

### ISSUE THREAD

**Issue by lourai** [jhipster/jhipster-uml#131]
when you get error (or warn) from checkValidityOfAssociation function, you get last word, but not the name of the relation or both source and dest class where the error is located.

For ONE_TO_MANY and MANY_TO_ONE you can just name tested var, but for ONE_TO_ONE and MANY_TO_MANY, you must get Class name you don't have in function param.

**Comment by MathieuAA** [comment]
I'll see what can be done about it tonight. If a simple fix is enough, I'll include the improvement in v1.6.1, if not then it would be v1.6.2.

**Comment by MathieuAA** [comment]
It's done and will be available in v1.6.2.
