### ISSUE TITLE
Error generating the otherEntityField From Modelio on a one-to-many relationship

### ISSUE THREAD

**Issue by sebastienmoreno** [jhipster/jhipster-uml#132]
I am trying to generate a Jhipster(2.27.0) application from Modelio(3.4.1) model with JHipster-UML(1.6.0).

On this example I have a one-to-many relationship between 2 entities (assessment and answer). I want to generate the 'otherEntityField' allowing to browse the relation through text and not ID.

The only way I manage to do that was to setup a bidirectional one-to-many relationship like this: 
![cqrfq](https://cloud.githubusercontent.com/assets/13941558/12782373/2fb1cd6a-ca7b-11e5-8db0-fc6aba798b6d.png)

And after jhipster-uml generate the code, I have to change the generated entity (here "Assessment.java"). The @OneToMany annotation should use "assessment" mappedBy parameter and not "assessment(entity)".

**Before changes:**
`@OneToMany(mappedBy = "assessment(entity)")`
`@JsonIgnore`
`@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)`
`private Set<Answer> answers = new HashSet<>();`

**After changes:**
`@OneToMany(mappedBy = "assessment")`
`@JsonIgnore`
`@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)`
`private Set<Answer> answers = new HashSet<>();`

**After that, it works.**

Is this a bug from jhipster-uml or is there a way to generate directly the "otherEntityField" ?

Here is the StackOverFlow details:
http://stackoverflow.com/questions/35159622/generating-the-otherentityfield-from-modelio-using-jhipster-uml-on-a-one-to-

**Comment by MathieuAA** [comment]
Thanks for posting it, it was solved with 78fe398, I'll release a new version by the end of the week if I find the time.
