### ISSUE TITLE
JDL Comments not working

### ISSUE THREAD

**Issue by david-vasquez** [jhipster/jhipster-uml#133]
Entering comments as follow wouldn't work:
```java
/**
  * Entity: MyEntityName
  * Created on: dd/mm/yy
  */
```
Additionally, it would be nice for the Parser to let us know where it failed (line number in the JDL file)

**Comment by MathieuAA** [comment]
Indeed, this would be a nice feature! I'll try to add it for v1.6.2.

As for the bug, I'll confirm it tomorrow, and fix it (and finally release).

**Comment by MathieuAA** [comment]
I've just created a separate issue for your request: #135.

**Comment by MathieuAA** [comment]
This is fixed, I'll release everything that has been done before the end of the week.
Thanks for reporting this!
