### ISSUE TITLE
Add JHipster's --table-name flag

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-uml#136]
When it is ready, see [this PR](https://github.com/jhipster/generator-jhipster/pull/2559).

**Comment by MathieuAA** [comment]
The syntax will be the following: `ENTITY_NAME(TABLE_NAME)` for UML editors.
If ENTITY_NAME is equal to TABLE_NAME, then specifying ENTITY_NAME alone will be enough.

**Comment by MathieuAA** [comment]
Feature finished for UML editors and the entity creator, only the JDL has to be modified now.

**Comment by agoncal** [comment]
@MathieuAA Is this feature available on JDL ? I can't see it.

**Comment by agoncal** [comment]
Cool !!!  

I can see it's working since 4.6.2 (maybe before)

```
entity Language (t_language) {
    alpha3b String required maxlength(3),
    alpha2 String required maxlength(2)
    name String required maxlength(DEFAULT_NAME_LENGTH),
    flag32	String,
    flag128 String
}

```
