### ISSUE TITLE
Modifying existing entity creating conflicts?

### ISSUE THREAD

**Issue by dhafirnz** [jhipster/jhipster-uml#137]
Not sure if this is the right forum to ask a question, but I have been struggling for a week trying to modify an existing entity by adding a new enum and a new relationship to another entity.
The command jhispter-uml model.jh seems to be stuck complaining about a conflict in exiting entity without giving any options. I have to press Enter to get a set of Ynaxdh options. When I select "a" it does something and stays stuck, and I have to cancel the command to release the lock. I end up with half cooked bundle of code files who don't work. Even when I select not to overwrite (option "n" ) it still goes ahead and overrides the entity with new one.

Even after answering all the questions, Then jhipster-uml stays stuck without any further message. I had to Ctrl+C to get out of it, obviously with half cooked files.

How to modify existing entity without creating a mess out of the project please?

**Comment by MathieuAA** [comment]
Hi, can you tell us the version of JHipster and JHipster UML you are using? And copy/paste your JDL file (if you can't, send it to me by mail).

**Comment by dhafirnz** [comment]
Hi Mathieu,
Thanks for looking into this issue, very much appreciated.
**JHipster version: 2.27.0**
**JHipster-UML: 1.6.1**
My OS is Windows 10 and I am sing Git Bash 2.7.1 64 bit

## Background
I am creating a new Enterprise application from scratch and want to stick to JHipster (excellent project by the way!). I initially created my first entity Address using the entity generator, which was  tedious, this is why I am so excited to see the UML option. I tried all four UI UML generators but they all either limited or too complicated to work with. I resorted to JHL which is much easier to work with, but had few parser issues which I am hoping will be addressed in coming releases.

## What I tried
So I tried to add few more entities in which couple of them will have M2M relationship with the existing entity Address. Also, I wanted to add a new field to Address (enum type). This is what I tried:
(1) I re-defined all existing fields in Address with my new enum field. It detected conflict, had to press Enter, answer "a" to override all. It got stuck in no where land. 
(2) I only defined the new enum field in Address, answered "n" to override. Got stucj in nowhere land again.
(3) I just declared Address entity without any field and answered "n" to override to keep my entity as is, also got stuck.
In all three above cases I had to Ctrl+C to break free, but with half cooked files.

## Here is my JHL file (not a NATO secret!) :
```
**enum CompanyStatus {
	INACTIVE, ACTIVE, SUSPENDED
}
entity Company {
	code String required maxlength(20) minlength(5),
	name String required maxlength(100) minlength(5),
	phone String required maxlength(20),
	tollPhone String required maxlength(20),
	mobile String required maxlength(20),
	email String required maxlength(50) minlength(5) pattern("^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"),	
	status CompanyStatus required,
	startDate LocalDate required,
	endDate LocalDate
}

entity Module{
	code String required maxlength(20) minlength(5),
	name String required maxlength(100) minlength(5),
	resource String maxlength(100)
}
relationship ManyToMany {
  Company{module} to Module{company}
}
enum SaluteType{
	MR,MRS,MISS,MS
}
entity Client {
	salute SaluteType,
	firstName String  required maxlength(30),
	lastName String  required maxlength(30),	
	phone String required maxlength(20) ,	
	mobile String required maxlength(20) ,
	email String required maxlength(50) minlength(5) pattern("^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$")			
}
relationship OneToMany {
  Company{client} to Client{company(name)}
}

enum AddressType{
	DELIVERY_ADDRESS,BILLING_ADDRESS,RESIDENCE_ADDRESS
}
entity Address {
	streetNum String maxlength(10),
	streetName String maxlength(30),
	poBoxNum String maxlength(30),
	suburb String maxlength(30),
	town String maxlength(30),
	city String  maxlength(30),
	postcode String  maxlength(8),
	state String  maxlength(30),
	country String maxlength(30),
	type AddressType
}
relationship ManyToMany {
  Company{address} to Address{company}
}
relationship ManyToMany {
  Client{address} to Address{client}
}
**
```

## Console output
After running the jhipster-uml command I get the following message
```
$ jhipster-uml model1.jh
Creating:
        Module
        Address
        Company
        Client
Found the .jhipster/Module.json configuration file, automatically generating the entity
The entity Module is being created.
   create src\main\java\nz\co\threepoints\ps\core\domain\Module.java
   create src\main\java\nz\co\threepoints\ps\core\repository\ModuleRepository.java
   create src\main\java\nz\co\threepoints\ps\core\repository\search\ModuleSearchRepository.java
   create src\main\java\nz\co\threepoints\ps\core\web\rest\ModuleResource.java
   create src\main\resources\config\liquibase\changelog\20160209055103_added_entity_Module.xml
identical src\main\webapp\scripts\app\entities\module\modules.html
identical src\main\webapp\scripts\app\entities\module\module-detail.html
identical src\main\webapp\scripts\app\entities\module\module-dialog.html
identical src\main\webapp\scripts\app\entities\module\module-delete-dialog.html
identical src\main\webapp\scripts\app\entities\module\module.js
identical src\main\webapp\scripts\app\entities\module\module.controller.js
identical src\main\webapp\scripts\app\entities\module\module-dialog.controller.js
identical src\main\webapp\scripts\app\entities\module\module-delete-dialog.controller.js
identical src\main\webapp\scripts\app\entities\module\module-detail.controller.js
identical src\test\javascript\spec\app\entities\module\module-detail.controller.spec.js
identical src\main\webapp\scripts\components\entities\module\module.service.js
identical src\main\webapp\scripts\components\entities\module\module.search.service.js
   create src\main\webapp\i18n\en\module.json
   create src\main\webapp\i18n\fr\module.json
   create src\test\java\nz\co\threepoints\ps\core\web\rest\ModuleResourceIntTest.java


Found the .jhipster/Address.json configuration file, automatically generating the entity
The entity Address is being created.
   create src\main\java\nz\co\threepoints\ps\core\domain\enumeration\AddressType.java
   create src\main\webapp\i18n\en\addressType.json
 conflict src\main\java\nz\co\threepoints\ps\core\domain\Address.java

```
At this stage I have to press Enter to get the Ynaxdh option, if I type "a" it prints the following lines and then stick forever:
```
 Overwrite src\main\java\nz\co\threepoints\ps\core\domain\Address.java? overwr
    force src\main\java\nz\co\threepoints\ps\core\domain\Address.java
identical src\main\java\nz\co\threepoints\ps\core\repository\AddressRepository.java
identical src\main\java\nz\co\threepoints\ps\core\repository\search\AddressSearchRepository.java
 conflict src\main\java\nz\co\threepoints\ps\core\web\rest\AddressResource.java
? Overwrite src\main\java\nz\co\threepoints\ps\core\web\rest\AddressResource.ja
    force src\main\java\nz\co\threepoints\ps\core\web\rest\AddressResource.java
    force src\main\resources\config\liquibase\changelog\20160104072929_added_entity_Address.xml
    force src\main\webapp\scripts\app\entities\address\addresss.html
    force src\main\webapp\scripts\app\entities\address\address-detail.html
    force src\main\webapp\scripts\app\entities\address\address-dialog.html
    force src\main\webapp\scripts\app\entities\address\address-delete-dialog.html
    force src\main\webapp\scripts\app\entities\address\address.js
    force src\main\webapp\scripts\app\entities\address\address.controller.js
    force src\main\webapp\scripts\app\entities\address\address-dialog.controller.js
    force src\main\webapp\scripts\app\entities\address\address-delete-dialog.controller.js
    force src\main\webapp\scripts\app\entities\address\address-detail.controller.js
    force src\test\javascript\spec\app\entities\address\address-detail.controller.spec.js
    force src\main\webapp\scripts\components\entities\address\address.service.js
    force src\main\webapp\scripts\components\entities\address\address.search.service.js
    force src\main\webapp\i18n\en\address.json
    force src\main\webapp\i18n\fr\address.json
    force src\test\java\nz\co\threepoints\ps\core\web\rest\AddressResourceIntTest.java

```
AT this stage I have to Ctrl+C to get the command prompt.

**Comment by dhafirnz** [comment]
Ok, I located the source of troubles, we half of them. It is the latest Git Bash I am using (v2.7.1). This seems to be buggy as I just tried running jhipster-uml using Windows CMD console and worked smoothly without sticking. However, my jhipster App menu is stuffed now :(

I have now two operational problems:
(1) In the Entity menu I get the menu item "Address" appearing twice. So instead of having [Address, Company, Module, Client] I get [**Address**, Company, Module, **Address**, Client]
(2) Clicking on any entity throws the following AngularJS ui-router error:

```
Error: Could not resolve 'address' from state 'site'
    at Object.transitionTo (angular-ui-router.js:3140)
    at Object.go (angular-ui-router.js:3068)
    at angular-ui-router.js:4181
    at angular.js:17918
    at completeOutstandingRequest (angular.js:5552)
    at angular.js:5829
```

I am hoping if I fix problem (1) it will fix problem (2).

**Comment by MathieuAA** [comment]
Hi, I'll update the doc after I reproduce the problem on my computer.
Concerning your problem, try to recreate an app from scratch without using the Windows "shell".

**Comment by MathieuAA** [comment]
An update, after asking some people who use/d Git Bash, it shouldn't be more than a layer above the standard shell... If it doesn't work, then your problems may have come from this tool.

**Comment by dhafirnz** [comment]
Yes, I am certain it is Git Bash new version (2.7.1) as I had no problem with older versions. Using the standard command shell works fine.
My issue now is the double menu items appearing after updating Address entity and why it fails to open any entity with the given JavaScript error.

**Comment by dhafirnz** [comment]
Hi Mathiue,
There seems to be a _case sensitive_ issue with uml generator. AT some stage in the parser it thinks the DB table name is case sensitive and hence treated as different table. 
When I initially created the Address entity using yo entity generator I must have typed "address" as the table name. Although it camelized the table name to "Address" in the Liquibase and Java, the .jhipster/address.js has kept it as "address" . When I re-defined it again in my JHL script I typed it as "Address". That confused UML JS generator and created another menu entry in **navbar.html** called "Address". This is why I ended up with two identical menu items under "Entities".

My Entities dropdown menu script ended up like this:

```
<ul class="dropdown-menu">
                        
<li ui-sref-active="active" >
    <a ui-sref="address" data-toggle="collapse" data-target=".navbar-collapse.in"><span class="glyphicon glyphicon-asterisk"></span>
                        &#xA0;<span translate="global.menu.entities.address">address</span></a></li>                        
<li ui-sref-active="active" >
    <a ui-sref="module" data-toggle="collapse" data-target=".navbar-collapse.in"><span class="glyphicon glyphicon-asterisk"></span>
                        &#xA0;<span translate="global.menu.entities.module">Module</span></a></li>                        
<li ui-sref-active="active" >
    <a ui-sref="company" data-toggle="collapse" data-target=".navbar-collapse.in"><span class="glyphicon glyphicon-asterisk"></span>
                        &#xA0;<span translate="global.menu.entities.company">Company</span></a></li>                        
<li ui-sref-active="active" >
    <a ui-sref="client" data-toggle="collapse" data-target=".navbar-collapse.in"><span class="glyphicon glyphicon-asterisk"></span>
                        &#xA0;<span translate="global.menu.entities.client">Client</span></a></li>
<li ui-sref-active="active" >
    <a ui-sref="client" data-toggle="collapse" data-target=".navbar-collapse.in"><span class="glyphicon glyphicon-asterisk"></span>
                        &#xA0;<span translate="global.menu.entities.address">Address</span></a></li>
                        <!-- jhipster-needle-add-entity-to-menu - JHipster will add entities to the menu here -->
 </ul>
```

You can see Address entity has been added twice to the menu. It did however, updated all other scripts correctly including the Liquibase and Java entity.

You can re-create the situation by:
1- Create an entity named "address" using entity generator.
2- Update the entity but call it "Address" using JHL , you should see double menu item Address under Entities admin menu.

**Comment by MathieuAA** [comment]
Please open another issue and copy/paste your second problem. We have to keep the issue tracker organized. I'll look into it tonight
