### ISSUE TITLE
It is not clear what the parser is complaining about?

### ISSUE THREAD

**Issue by dhafirnz** [jhipster/jhipster-uml#138]
I am struggling to locate the error line when the parser complains about a syntax.
Like:
Expected a space but "(" found.
SyntaxError: Expected a space but "(" found.

It is very concerning that  parser is expecting a space but got something else. Not sure which line got it wrong. Is it possible to spit out the offending line number?

**Comment by MathieuAA** [comment]
I've already pushed something for that, but it is not released yet (and won't be for a while I guess).
Can you copy/paste your JDL file, or send it to me by mail?

**Comment by dhafirnz** [comment]
I had to run my script in segments to identify the offending block, and found a syntax error missing 't' in maxlength, so:
**maxlengh**(20) instead of **maxlength**(20)
Thanks,
