### ISSUE TITLE
No entity has to be generated..

### ISSUE THREAD

**Issue by superandrew** [jhipster/jhipster-uml#140]
When I try to parse this uml exported from visual paradigm I got this message. Unfortunately no -verbose option is available.

<img width="1364" alt="img 2016-02-09 at 23 27 58" src="https://cloud.githubusercontent.com/assets/71364/12932954/db8235da-cf85-11e5-9eed-d6c923311aeb.png">

    Parser detected: VISUAL PARADIGM.

    No entity has to be generated.

Is it broken or am I doing something wrong?

**Comment by MathieuAA** [comment]
Two things:
  - There is no reason for this message to be displayed (I'll look into it tonight);
  - JHipster and JHipster UML don't support inheritance, and I can see your UML class diagram may be incorrect.

Can you copy/paste your XMI file here? I'll use to test the parser along with some files of mine.

**Comment by superandrew** [comment]
Here's the uml file (zipped).

[Classes.uml.zip](https://github.com/jhipster/jhipster-uml/files/124382/Classes.uml.zip)

ok for inheritance, anyway I tried with just a class and it doesn't work either.

Thanks!

**Comment by superandrew** [comment]
I guess the problem is in the file I exported from visual paradigm. If I export an xmi it doesn't work but in a different way. If I export an uml probably jhipster-uml can't find anything to parse.

If I export xmi I get:

    ? Please choose between the available editors: (Use arrow keys)
    ❯ umldesigner
      I don't see my editor.

If I flag the latter, I got this:

    ? Please choose between the available editors: I don't see my editor.
    You should report this issue by mentioning what your editor is.
    Error
        at Object.<anonymous> (/Users/../.node/lib/node_modules/jhipster-uml/lib/exceptions/undetected_editor_exception.js:7:39)
        at Module._compile (module.js:425:26)
        at Object.Module._extensions..js (module.js:432:10)

With the first, despite having installed umldesigner, I got this:

    ? Please choose between the available editors: umldesigner
    Cannot read property 'forEach' of undefined
    TypeError: Cannot read property 'forEach' of undefined
    at UMLDesignerParser.findElements (/Users/../.node/lib/node_modules/jhipster-uml/lib/editors/umldesigner_parser.js:33:28)

any idea?

**Comment by MathieuAA** [comment]
How do you export your file? What are the options you use?

**Comment by superandrew** [comment]
Here they are:
<img width="1524" alt="img 2016-02-10 at 10 08 48" src="https://cloud.githubusercontent.com/assets/71364/12942945/5bd6b3fc-cfde-11e5-8323-074a67d868b4.png">

**Comment by MathieuAA** [comment]
Try with "export for UML 2". We only support this version of the spec.

**Comment by superandrew** [comment]
In this case we go to the beginning of the post, because that is what I was trying. If I select uml2 you can find the output in the zip file.

**Comment by superandrew** [comment]
I should probably deselect "Export Data Type to: UML Primitive Type" because in this case I get:

    Parser detected: VISUAL PARADIGM.

    The type 'int' isn't supported by JHipster.
    Error
    at Object.<anonymous> (/Users/../.node/lib/node_modules/jhipster-uml/lib/exceptions/invalid_type_exception.js:7:34)

**Comment by MathieuAA** [comment]
Indeed!
