### ISSUE TITLE
Case-sensitive entity name creates duplicate menu item

### ISSUE THREAD

**Issue by dhafirnz** [jhipster/jhipster-uml#141]
There seems to be a _case sensitive_ issue with uml generator. At some stage in the parser it thinks the entity name is case sensitive and hence treats it as a different "entity" when constructing the menu in navbar.html. 
When I initially created the Address entity using "yo entity generator" I must have typed "address" as the entity name. Although it camelized the table name to "Address" in the Liquibase and Java, the .jhipster/address.js has kept it as "address" . When I re-defined "address" entity it again in my JHL script I typed it as "Address". That confused JHIPSTER-UML generator and created another menu entry in **navbar.html** called "Address". This is why I ended up with two identical menu items under "Entities".

My Entities dropdown menu script ended up like this:

```
<ul class="dropdown-menu">
                        
<li ui-sref-active="active" >
    <a ui-sref="address" data-toggle="collapse" data-target=".navbar-collapse.in"><span class="glyphicon glyphicon-asterisk"></span>
                        &#xA0;<span translate="global.menu.entities.address">address</span></a></li>                        
<li ui-sref-active="active" >
class="glyphicon glyphicon-asterisk"></span>
                        &#xA0;<span translate="global.menu.entities.address">Address</span></a></li>
                        <!-- jhipster-needle-add-entity-to-menu - JHipster will add entities to the menu here -->
 </ul>
```

You can see Address entity has been added twice to the menu. It did however, updated all other scripts and Java classes correctly including the Liquibase and Java entity.

You can re-create the situation by:
1- Create an entity named "address" using entity generator.
2- Update the entity but call it "Address" using JHL , you should see double menu item Address under Entities admin menu.

**Comment by MathieuAA** [comment]
What version of JHipster UML are you using? I can't reproduce the issue.

**Comment by dhafirnz** [comment]
I think the last one I downloaded was 1.6.1. What is the best way to tell the current version of JHipster UML?

**Comment by dhafirnz** [comment]
The JHL parser expects an upper case as the first character of the entity name! Why is that?
This script is rejected by the parser:
`entity address {...}`

I get the following error message:
```
Expected a space or an entity name but "a" found.
SyntaxError: Expected a space or an entity name but "a" found.
    at peg$buildException (C:\Users\u382911\AppData\Roaming\npm\node_modules\jhipster-uml\lib\dsl\jhGrammar.js:362:14)
    at Object.peg$parse [as parse] (C:\Users\u382911\AppData\Roaming\npm\node_modules\jhipster-uml\lib\dsl\jhGrammar.js:3787:13)
    at DSLParser.parse (C:\Users\u382911\AppData\Roaming\npm\node_modules\jhipster-uml\lib\dsl\dsl_parser.js:36:27)
    at Object.<anonymous> (C:\Users\u382911\AppData\Roaming\npm\node_modules\jhipster-uml\jhipster-uml.js:77:27)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)

```
The following is what it expect:

`entity Address {...}`

Is this a separate issue?

**Comment by MathieuAA** [comment]
Hello, sorry for the late answer, but I had a lot of work.
This is **not** an issue, it is intended (I believe there was a comment about that a few months ago). And no, this doesn't affect what's generated because we format everything from the JDL to the JSON.

**Comment by MathieuAA** [comment]
I'm going to add a -version option... it may be helpful.

**Comment by MathieuAA** [comment]
If you want, clone this repo and `npm link` it so that you may try with the latest version (it's stable!).
