### ISSUE TITLE
translationFilterProviderError AngularJS Error if International is not used.

### ISSUE THREAD

**Issue by dhafirnz** [jhipster/jhipster-uml#144]
I started a new Jhipster application and chose not to have International support. When I started adding my entities AngularJs failed to boot strap on my entities and started to get the following AngularJS error:
Error: [$injector:unpr] Unknown provider: translateFilterProvider <- translateFilter

This is without me adding a single character of code.
I then regenerated the project and this time I chose International support and that went fine and smooth without error.

I created all my entities using jhipster-uml (V1.6.1) JDL script.

**Comment by MathieuAA** [comment]
This doesn't concern JHipster UML. Post it in the main project's issue tracker.
