### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by snc43** [jhipster/jhipster-uml#145]
While trying to reverse engineer an DataModel. the following error is reported by the Modelio parser 
```
$ jhipster-uml ./assignment.xmi 
Parser detected: MODELIO.

Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
```
Attached it the xmi file (renamed to txt formate)
[assignmen.txt](https://github.com/jhipster/jhipster-uml/files/129579/assignmen.txt)

**Comment by MathieuAA** [comment]
Hi, you have a constraint problem.
If you open your XMI file, you should see:

```
    <ownedRule xmi:type="uml:Constraint" xmi:id="_RF-orNLtEeWluu3iRVkrIA" name="UNIQUE " constrainedElement="_RF_QTNLtEeWluu3iRVkrIA _RF_QUdLtEeWluu3iRVkrIA">
      <specification xmi:type="uml:LiteralString" xmi:id="_RF-ordLtEeWluu3iRVkrIA" value=""/>
    </ownedRule>
```

There is no `UNIQUE` constraint in JHipster, and there is more than one constrained element.
That's why the error was thrown.

**Comment by snc43** [comment]
Hello, I do not think that is the issue here. the issue here is 
```
<ownedRule xmi:type="uml:Constraint" xmi:id="_RF-oqtLtEeWluu3iRVkrIA" name="required" constrainedElement="_RF_QTNLtEeWluu3iRVkrIA _RF_QUdLtEeWluu3iRVkrIA">
```

see the 
```
constrainedElement="_RF_QTNLtEeWluu3iRVkrIA _RF_QUdLtEeWluu3iRVkrIA"
```
As per UML 2.4.1 Spec the constrainedElement can be 0... *

Now when ever we do have multiple constrainedElement we see this error 

Please see the attached updated xmi file where I have modified the constrained name as per the dataType supported validation name. But I still see the same error.

[assignment.txt](https://github.com/jhipster/jhipster-uml/files/129783/assignment.txt)

**Comment by snc43** [comment]
See this line 


```
node-v4.3.0-linux-x64/lib/node_modules/jhipster-uml/lib/editors/modelio_parser.js
line number 253
var type = this.parsedData.getType(this.parsedData.getField(constraint.$.constrainedElement).type);
```

**Comment by MathieuAA** [comment]
The problem is that there are **two** constrained elements, where only one should be. I know, I've checked it this very morning.

**Comment by snc43** [comment]
![screenshot from 2016-02-14 22 16 42](https://cloud.githubusercontent.com/assets/5745950/13034946/bb183fec-d368-11e5-8612-824c691e9606.png)

This is what my ERD looks like

**Comment by MathieuAA** [comment]
There are some constraints that won't be used by JHipster UML (the "UNIQUE" ones). I still don't know how you got two constrained elements for a constraint (you have this several times in your diagram).
