### ISSUE TITLE
Would be nice to choose or automatically detect which entity or entitites have changed

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/jhipster-uml#149]
### The issue

JHipster-UML has helped me a lot since its first release. But keep the data model over the time with this tool bring some extra work and then you start to spend all time saved during the data model start.

What really bothers me is once you change something on your entity (add a new field for example) it passes over all the other entities (that has no change at all) and makes you answer 'no' for everything because you have a lot of customizations.

Am I doing something wrong or it can become an issue and perhaps become a new feature for a new version?

**Comment by MathieuAA** [comment]
I noticed some problems with the checks, but I have to test your problem.

**Comment by MathieuAA** [comment]
I don't have this issue... what version of JHipster UML are you using?

**Comment by marcelinobadin** [comment]
v1.6.1, the latest.

Does it just try to change the entities you changed? Because what I tried to explain is that it will try to change any other entity if the files are not the same as generated, if you have customizations it will ask if you want to change or not. What I told that can be nice to have is to select what are the entities you have changed and you want to update (if it could be automatically chosen would be great).

When you have too many entities and customizations it is very difficult to keep the JDL file updated. What I do is too change directly in the json file and run the jhipster:entity again for the entities I have changed.

My goal here is to keep the maintenance of my data model on the JDL. This is a great tool and can make easy documentation lifecycle.

**Comment by MathieuAA** [comment]
Oh! I didn't understand that! It's a good idea =)
I'll see about adding it in v1.6.2 or v1.6.3.

**Comment by marcelinobadin** [comment]
I was wondering... one thing you can do is, first check if there is a change on the entity.json, if there is not, don't try continue the jhipster:entity sub-generator.

**Comment by MathieuAA** [comment]
I've finished implementing the new system, I'll add the option to select which entity to update later this week. And then I'll release after moving Visual-Paradigm away from this project.

**Comment by MathieuAA** [comment]
Finished, and improved (992dd30).
