### ISSUE TITLE
Wrong relationships generation

### ISSUE THREAD

**Issue by superandrew** [jhipster/jhipster-uml#150]
### The issue
Hello, I created a test case in Visual Paradigm.

![img 2016-02-26 at 15 17 06](https://cloud.githubusercontent.com/assets/71364/13354550/04c53334-dc9c-11e5-984e-d05c3598b4d2.png)
I have a class Container filled with 0 or more items. Every item must have one and only one container. 
Here's the specification of the relationship.
![img 2016-02-26 at 15 17 50](https://cloud.githubusercontent.com/assets/71364/13354573/1f9f9168-dc9c-11e5-91d5-4159c22e8329.png)
The generated code
`package .domain;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import java.util.Objects;

public class Container implements Serializable {

    @ManyToMany
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    @JoinTable(name = "container_items",
               joinColumns = @JoinColumn(name="containers_id", referencedColumnName="ID"),
               inverseJoinColumns = @JoinColumn(name="itemss_id", referencedColumnName="ID"))
    private Set<Item> itemss = new HashSet<>();

    public  getId() {
        return id;
    }

    public void setId( id) {
        this.id = id;
    }

    public Set<Item> getItemss() {
        return itemss;
    }

    public void setItemss(Set<Item> items) {
        this.itemss = items;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Container container = (Container) o;
        if(container.id == null || id == null) {
            return false;
        }
        return Objects.equals(id, container.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public String toString() {
        return "Container{" +
            "id=" + id +
            '}';
    }
}
`

`package .domain;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import java.util.Objects;

public class Item implements Serializable {

    @ManyToMany(mappedBy = "itemss")
    @JsonIgnore
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    private Set<Container> containers = new HashSet<>();

    public  getId() {
        return id;
    }

    public void setId( id) {
        this.id = id;
    }

    public Set<Container> getContainers() {
        return containers;
    }

    public void setContainers(Set<Container> containers) {
        this.containers = containers;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Item item = (Item) o;
        if(item.id == null || id == null) {
            return false;
        }
        return Objects.equals(id, item.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public String toString() {
        return "Item{" +
            "id=" + id +
            '}';
    }
}
`

I really do not understand why all these relationships are generated many to many. I probably did something wrong in the relationship in Visual Paradigm, but I can't figure out what.

### Steps to reproduce
Export from Visual Paradigm, launch

`jhipster-uml test.uml -db sql`

### The XMI or JDL file

Here's the generated uml
[test.uml.zip](https://github.com/jhipster/jhipster-uml/files/148306/test.uml.zip)

Is it a problem with Jhipster or is there something wrong with my configuration?

**Comment by MathieuAA** [comment]
Hi, what version of JHipster UML are you using?

**Comment by superandrew** [comment]
I would love to tell you, where can I check?

`jhipster-uml --version | -version | -v | --v` throws an error

**Comment by superandrew** [comment]
`npm -v jhipster-uml
3.7.3`

**Comment by superandrew** [comment]
now if I run

`npm install -g jhipster-uml` I get

`└── jhipster-uml@1.6.1`

So I really don't know :)

**Comment by MathieuAA** [comment]
Doing `npm -v jhipster-uml` returns your version of npm. The `-v` option is committed, but not yet released (soon). After your last command, you have the latest version. What's the result of this command? (same errors?).

Where do you do `jhipster-uml test.uml`? In what folder?

**Comment by superandrew** [comment]
ok, thanks, I've tried to regenerate the sources, same problem. Every relationship is generated many to many. I'm generating it in a folder on my desktop right now.

**Comment by MathieuAA** [comment]
Ok, try to generate in your JHipster app folder.

**Comment by superandrew** [comment]
The first problem I was having was with a much more complicated UML in my jshipster app folder, so I created a simple case to help understanding the problem.

Anyway, I created an app ad hoc, copied the test.uml, and launched

`jhipster-uml test.uml` (without -db sql being in a jhipster directory)

the class are almost identical

<img width="1245" alt="img 2016-02-26 at 16 20 48" src="https://cloud.githubusercontent.com/assets/71364/13356316/ec2e9384-dca4-11e5-9b0d-1d9a3e108109.png">

**Comment by MathieuAA** [comment]
The left hand version is the right one. You didn't have the `id` field because you weren't in a JHipster app folder. If you use JHipster UML somewhere else, only the JSON files are correct.
I don't understand why it read your relationship as a Many-to-Many though. I can't test your XMI file right now.

**Comment by MathieuAA** [comment]
I confirm there's a bug in the VP XMI file parser. Fixing it now.

**Comment by superandrew** [comment]
great to hear!

Please let me know If I can help in any way.

**Comment by MathieuAA** [comment]
You've already helped me by telling there is a bug =) 
The fix is taking longer than expected due to the mess VP does when it exports diagrams... Sorry for the dealy.

**Comment by superandrew** [comment]
Don't worry, I'm just happy that this helped diagnosticating a problem.

Thanks!

**Comment by superandrew** [comment]
cool! do you already have planned the next release for this issue to be fixed?

**Comment by MathieuAA** [comment]
Nop, we still need to find a way to properly ignore the packages before releasing v1.6.2...

**Comment by MathieuAA** [comment]
Update: I think I'll postpone, again, the fix for the package issue... until v1.70 which should be right after v1.6.2. There will be some minor change. 
You can therefore expect a release before the end of the week.
