### ISSUE TITLE
Consider dropping support of Visual Paradigm XMI files

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-uml#152]
I'm submitting this issue to @jhipster/developers, @jhipster/uml, and to everyone willing to participate in this debate: **should we drop VP**?

### The pros
  1. One less editor to support, study and follow;
  2. The XMI is HUGE (~0.15% of useful XML to read) and work to speed up the reading of such files is tedious (and shouldn't be done by us);
  3. VP is very expensive ($, €, etc.);
  4. Working with this editor is really painful for us.

### The cons
  1. One less editor :(;
  2. Almsot a breaking change, and it could be delayed...

### Alternative to the cons
  1. Having the VP parser as a module

### Precisions
Please, feel free to give your input here (I will be updating this post). The indicated milestone is not set for good, it's just a practical *non-moving* target.

**Comment by gmarziou** [comment]
Just a naive question: does the modules system for jhipster apply to jhipster-uml?

**Comment by MathieuAA** [comment]
Not sure if it's the right place to post this, but yes and no.
Yes because @CarlKlagba did the work for it, it's a custom implementation that allows others to `require('jhipster-uml')` and use some *classes*.
No because, as far as I understand JHispter's module system, JHipster UML is not a generator and JHipster's module sub-generator is kind of a proxy used by modules to access JHipster's generators. We only provide endpoints to some parts of JHipster UML without pulling to many dependencies.

**Comment by gmarziou** [comment]
Thanks, I asked this because I thought that maybe it could have been a way to drop VP from core while letting some volunteers (if any) take over it as a module

**Comment by MathieuAA** [comment]
I think I understand your question now =)
We didn't have in mind having some plug-ins for JHipster UML. But yes, this is a good idea.

**Comment by deepu105** [comment]
I thought the editor aupport was already some kind of plugin stuff

**Comment by MathieuAA** [comment]
Yes and no. As you can see, all 4 XMI parsers are integrated inside JHipster UML's source packages.
If someone, as Gaël said, would take over the VP parser, then he/she would have to create another project, create the class and use JHipster UML to do the rest (scheduling, and generating the JSON).
It is, however, easy to remove the parser as the code is not bound with any parser implementation. So yes, in that regard, you can consider each parser implementation as a plug-in.

**Comment by dalves96** [comment]
Hi. I had **some success using Visual Paradigm** as main exporter uml/xmi file.
Here is a way to continuing using Visual Paradigm with some help of Modelio.

So I will explain the procedure:

First I've made the structure on Visual Paradigm similar to the Jhipster-Uml complete example, with various types like Blob and ZonedDateTime. 
Next I've exported to xmi/uml like the explanation on the site and imported on Modelio, then I only needed to make same small changes like:
-The Role on the non Navigable side couldn't have anything written (except on OneToOne or ManyToMany relations).
![image](https://cloud.githubusercontent.com/assets/2979698/16149836/4506948c-348b-11e6-8c46-88da4051a6a0.png)

Then jhipster-uml path/to/the/xmi/file should work without a problem.

I've noticed a duplicaton bug after the file is loaded to Jhipster on the used parameters for the Blob type. 
I don't know if that already does on the files original created on Modelio or not?

**Pros:** 
Can still use Visual Paradigm.
**Cons:** 
I have to use 2 parsers, and have 2 exports; 
And have a more time expended.

I hope this helps to continuing using Visual Paradigm,  
Does this count as a viable way to use VisualParadigm with Modelio?

**Comment by MathieuAA** [comment]
Well, the main problem I have with VP is that it's not free, and I can't test or fix issues as easily as with the other parsers. Your solution, if I understand it correctly (correct me if I'm wrong), would be to use VP from the very start and that's what I find difficult. VP requires a license and I don't want to pay.
As suggested here, one could just create a module for VP and support it by using the various classes JHipster UML makes available (and will make very shortly).

**Comment by MathieuAA** [comment]
All the work will be done [here](https://github.com/MathieuAA/vpplugin).
I'll close this as soon as I get it done.
