### ISSUE TITLE
Generate JDL file from Modelio, UMLDesigner...

### ISSUE THREAD

**Issue by sebastienmoreno** [jhipster/jhipster-uml#153]
Here is a suggestion : 
would it be interesting to generate the JDL file from the XMI UML files ?

The JDL file would be a kind of 'pivot' file.

It would help migration for projects which use UML editors like Modelio and want to switch to JDL.

Thanks in advance !

**Comment by MathieuAA** [comment]
Nice idea! I'll see to that this week-end =)

**Comment by MathieuAA** [comment]
The work needed to add this requires a minor modification, and I'm postponing this to v1.7.0.

**Comment by sebastienmoreno** [comment]
Great Mathieu !

**Comment by deepu105** [comment]
@MathieuAA see if this can be generalized so that we can try to give this feature to import a UML in JDL studio as well

**Comment by MathieuAA** [comment]
@sebastienmoreno, @deepu105 My idea: the user passes an XMI files like this `jhipster-uml MY_FILE.xmi -toJDL`, this wouldn't trigger the creation of JSON files, but only parse the XMI file and output the JDL file. If, however, the user wants to specify the output file, then doing `jhipster-uml MY_FILE.xmi -toJDL MY_JDL_FILE.jdl` will create the file and (or delete its previous content) and write the content.

The reason I don't want JUML to generate the JSON after this is that I want the users to modify the returned JDL file or assert it is correct.

Deepu, will the JDL studio be able to support something like that?

**Comment by deepu105** [comment]
yes if you can output JDL that would be sufficient

Thanks & Regards,
Deepu

**Comment by sebastienmoreno** [comment]
Good idea!

**Comment by MathieuAA** [comment]
Small update: I'm updating the JDL project to be able to implement this (work is being done [here](https://github.com/jhipster/jhipster-domain-language/tree/coreobjects)). This is going nicely but I don't know when I'll be done. I expect this feature to be fully implemented by the end of next week or the week after.

**Comment by MathieuAA** [comment]
It's finally done, and merged in master.

**Comment by ehillis** [comment]
Where is this done?   What master?  I tried using the above suggested -toJDL option and it is not available.

**Comment by MathieuAA** [comment]
Hi, it has been pushed to the master branch. That means it worked for me without any guarantee it will for anyone else until it's released. You can clone this repo and test it out if you wish =) 

Le 14 septembre 2016 21:29:51 GMT+02:00, ehillis <notifications@github.com> a écrit :
>Where is this done?   What master?  I tried using the above suggested
>-toJDL option and it is not available.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-uml/issues/153#issuecomment-247127217

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment]
I've noticed a bug yesterday so I had it enabled on the master branch today. It shouldn't bug. I hope so anyway.

Le 14 septembre 2016 21:29:51 GMT+02:00, ehillis <notifications@github.com> a écrit :
>Where is this done?   What master?  I tried using the above suggested
>-toJDL option and it is not available.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-uml/issues/153#issuecomment-247127217

-- 
Mathieu ABOU-AICHI
