### ISSUE TITLE
Is there any way to add property like "CascadeType.ALL" to relationships

### ISSUE THREAD

**Issue by ouyangshixiong** [jhipster/jhipster-uml#154]
### The issue
Jhipster-uml generated entities do not have cascadeType on relationships column(OneToMany OneToOne).
As we all known, if i delete row A in one table, other table remain reference to the row A.
It brings data Consistency problem。

Is there any way to set cascadeType on relationships by JDL? Thank you very much.

**Comment by MathieuAA** [comment]
Hi, JHipster UML doesn't generate entities! It simply uses the fact that you have JHipster installed, and calls it to generate the entities from the JSON JHipster UML generates. Thus, JHipster UML is simply a JSON generator.
So the answer is no, not from JHipster UML anyway.

**Comment by ouyangshixiong** [comment]
OK.Thanks.
