### ISSUE TITLE
How to contribute to JHipster generator?

### ISSUE THREAD

**Issue by khouloudkhadija** [jhipster/jhipster-uml#156]
I am blocked :I want to modify the source code of jhipster generator , and I don't know how to do it. How can I test the modified jhipster generator? How to use my own jhipser generator? How can I know that my new jhipster is doing well? Please I need your help. Thanks.

**Comment by MathieuAA** [comment]
Hi, you're in the wrong project. Post this question to the generator's board.

**Comment by khouloudkhadija** [comment]
Sorry, didn't understand where can I post this question exactly ??

**Comment by MathieuAA** [comment]
[There](https://github.com/jhipster/generator-jhipster/issues).

**Comment by PierreBesson** [comment]
@khouloudkhadija Are you looking for [this](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) ?
