### ISSUE TITLE
Can I use stereotypes?

### ISSUE THREAD

**Issue by alcidesmorales** [jhipster/jhipster-uml#157]
I think in some cases it may be useful or desirable to explicitly indicate which classes want to process as an entity and which not. Perhaps by using stereotypes that can be easily achieved.

For example something like `<< Entity >>` would be very easy to understand.

In the same way you could generalize to generate corresponding `<< Service >>` classes if you want to use something more than CRUD.

BTW, congratulations for the good job

**Comment by MathieuAA** [comment]
Hi, it may be a good idea, but I don't know whether it (the stereotype feature) is supported by all 4 parsers... Gotta investigate.

**Comment by MathieuAA** [comment]
I played a little with all 4 editors, and GenMyModel doesn't support stereotypes (a thread [here](http://help.genmymodel.com/forums/169180-ideas-and-feature-requests/suggestions/6126655-stereotypes-and-taggedvalues-or-more-generaly-um). 
Moreover, not generating entities is kind of dangerous as it could mess up the scheduler.
This could be an option for the future, so I'll add a milestone for this as "Future".

Thanks for the suggestion!

**Comment by MathieuAA** [comment]
I'm deprecating this project in favor of the JDL, and this is not happening any time soon.
