### ISSUE TITLE
ERROR fieldId is missing

### ISSUE THREAD

**Issue by alcidesmorales** [jhipster/jhipster-uml#160]
### The issue

After upgrading to JHipster UML version 1.6.2 all my entities fails to regenerate.
I double check, reverting to the previous version 1.6.1 works  and upgrading to version 1.6.2 fails again.

---
#### The stacktrace

Parser detected: MODELIO.

In the One-to-Many relationship from Department to Employee, only bidirectionality is supported for a One-to-Many association. The other side will be automatically added.
In the One-to-Many relationship from Employee to Job, only bidirectionality is supported for a One-to-Many association. The other side will be automatically added.
Creating:
        Region
        Task
        Country
        Location
        Department
        Employee
        Job
        JobHistory
Found the .jhipster/Region.json configuration file, automatically generating the entity
The entity Region is being created.
Error jhipster:entity Region --regenerate

ERROR fieldId is missing in .jhipster/Region.json for field {
    "fieldName": "regionId",
    "fieldType": "Long"
}

Found the .jhipster/Task.json configuration file, automatically generating the entity
The entity Task is being created.
Error jhipster:entity Task --regenerate

ERROR fieldId is missing in .jhipster/Task.json for field {
    "fieldName": "taskId",
    "fieldType": "Long"
}

Found the .jhipster/Country.json configuration file, automatically generating the entity
The entity Country is being created.
Error jhipster:entity Country --regenerate

ERROR fieldId is missing in .jhipster/Country.json for field {
    "fieldName": "countryId",
    "fieldType": "Long"
}

Found the .jhipster/Location.json configuration file, automatically generating the entity
The entity Location is being created.
Error jhipster:entity Location --regenerate

ERROR fieldId is missing in .jhipster/Location.json for field {
    "fieldName": "locationId",
    "fieldType": "Long"
}

Found the .jhipster/Department.json configuration file, automatically generating the entity
The entity Department is being created.
Error jhipster:entity Department --regenerate

ERROR fieldId is missing in .jhipster/Department.json for field {
    "fieldName": "departmentId",
    "fieldType": "Long"
}

Found the .jhipster/Employee.json configuration file, automatically generating the entity
The entity Employee is being created.
Error jhipster:entity Employee --regenerate

ERROR fieldId is missing in .jhipster/Employee.json for field {
    "fieldName": "employeeId",
    "fieldType": "Long"
}

Found the .jhipster/Job.json configuration file, automatically generating the entity
The entity Job is being created.
Error jhipster:entity Job --regenerate

ERROR fieldId is missing in .jhipster/Job.json for field {
    "fieldName": "jobId",
    "fieldType": "Long"
}

Found the .jhipster/JobHistory.json configuration file, automatically generating the entity
The entity JobHistory is being created.
Error jhipster:entity JobHistory --regenerate

ERROR fieldId is missing in .jhipster/JobHistory.json for field {
    "fieldName": "startDate",
    "fieldType": "ZonedDateTime",
    "fieldValidateRules": [
        "required"
    ]
}

---

### Steps to reproduce

Just execute as always:
**hipster-uml "models\modelio.xmi"**

---

### The XMI or JDL file

The same problems happen with my business model and also with this test XMI model
[Modelio XMI Test](https://github.com/jhipster/jhipster-uml/blob/master/test/xmi/modelio.xmi)

---

### Versions

| JHipster           | JHipster UML           |
| ------------------ | ---------------------- |
| 2.27.2              | 1.6.2                    |

**Comment by MathieuAA** [comment]
Hello, this is normal as JHipster removed them from the dumped JSON files.
See [this](https://github.com/jhipster/generator-jhipster/pull/2879).

**Comment by MathieuAA** [comment]
You must not be using the latest version from JHipster I guess.

**Comment by andidev** [comment]
I don't think it is released yet. This was made in the master branch one month ago and that means it's part of jhipster 3.0. But I'm not 100% sure though so maybe you know better.

**Comment by MathieuAA** [comment]
Usually I just check when the PR was merged, and if a release was made after (or if the PR/issue has been labelled "3.0")... If I can't rely on that, I don't know how to propagate changes made in JHispter to JHipster UML.

I'm gonna to test. If I'm wrong, I'll make an urgency release to add the ids again.

**Comment by MathieuAA** [comment]
OK, if I understand correctly you publish what is inside the v2.X maintenance branch, and commit in the master branch if you wanna add things to v3.0 (or fixes).
That's a bit weird, but whatever. I'll make an urgency release.
Sorry @alcidesmorales!

**Comment by andidev** [comment]
Yes that's how we work. Master branch has been 3.0 since I don't know when. Agree that it is a bit confusing.
