### ISSUE TITLE
Relationships many-to-one generated as one-to-many

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/jhipster-uml#162]
### The issue
Once I have upgraded to 1.6.4 and ran jhipster-uml, my relationships got broken. On entities which the relationship should be many-to-one it created as one-to-many.

Important to highlight that I upgraded the version and changed the JDL file to use the new format for relationships (grouped all inside a one-to-many block)

JHipster version 2.27.2

**Comment by MathieuAA** [comment]
Hi, can you please paste your JDL file?

**Comment by sebastienmoreno** [comment]
I have the same issue. (jhipster-uml 1.6.4)

The following JDL:
`
entity MaturityModel {
  name String required minlength(5),
  version Double required min(0),
  creationDate LocalDate required
}
relationship OneToMany{
	MaturityModel to MaturityLevel{maturityModel(name)}
}
`

Generates the following code:
`
public class MaturityLevel implements Serializable {
    @OneToMany(mappedBy = "maturityLevel")
    @JsonIgnore
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    private Set<MaturityModel> maturityModels = new HashSet<>();
`

**Comment by MathieuAA** [comment]
I must have inverted them... I'll fix it tonight.
Does changing the relationship to ManyToOne in the JDL works?

**Comment by sebastienmoreno** [comment]
Yes with ManyToOne it works but you can't have bidirectionnal in this case.

**Comment by MathieuAA** [comment]
The issue is that the entity creator doesn't invert the OtoM to a MtoO for MaturityLevel, see:

```json
{
  "relationships": [
    {
      "relationshipId": 1,
      "relationshipType": "one-to-many",
      "relationshipName": "maturityModel",
      "otherEntityName": "maturityModel",
      "otherEntityField": "name"
    }
  ],
  "fields": [],
  "changelogDate": "20160318222231",
  "dto": "no",
  "pagination": "no",
  "service": "no",
  "entityTableName": "MaturityLevel"
}
```

Fixing it now.
