### ISSUE TITLE
Reversed many-to-one relations

### ISSUE THREAD

**Issue by ashakhov** [jhipster/jhipster-uml#169]
#### Description
JHipster-UML v.1.6.4 for some reason generated one-to-many relations instead of many-to-one during generating entities from JDL file. That broke whole mapping system of generated application so it can't even be started. Version 1.6.3 doesn't have this issue.

#### The stacktrace

```
Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: org.jhipster.test.domain.City.customer in org.jhipster.test.domain.Customer.citys
```

---

### Steps to reproduce

1. Generate an application using existing .yo-rc.json
2. Run "jhipster-uml jhipster-jdl.jh"

---

### The XMI or JDL file
[JDL](https://jhipster.github.io/jdl-studio/#view/entity%20Customer%20{%0A%09lastName%20String%20required%20minlength%281%29%0A}%0A%0Aentity%20Country%20{%0A%09name%20String%20required%20minlength%281%29%0A}%0A%0Aentity%20Region%20{%0A%09name%20String%20required%20minlength%281%29%0A}%0A%0Aentity%20City%20{%0A%09name%20String%20required%20minlength%281%29%0A}%0A%0Arelationship%20OneToMany%20{%0A%20%20%20%20Country{region%28name%29}%20to%20Region{country%28name%29}%0A}%0A%0Arelationship%20OneToMany%20{%0A%20%20%20%20Region{city%28name%29}%20to%20City{region%28name%29}%0A}%0A%0Arelationship%20OneToMany%20{%0A%20%20%20%20%20City%20to%20Customer{city%28name%29}%0A}%0A%0Apaginate%20Customer%20with%20pagination%0A%0Aservice%20Customer%20with%20serviceClass)
---

### Versions

| JHipster           | JHipster UML           |
| ------------------ | ---------------------- |
| `2.27.2` | `1.6.4` |

**Comment by MathieuAA** [comment]
I think I've already solved it, but not yet released the fix. I'll test it to confirm it.

**Comment by MathieuAA** [comment]
As I though, the problem has been fixed, but the fix is not yet released. I'll do a patch release some time this week... Sorry for the inconvenience.
