### ISSUE TITLE
Add --angular-suffix option

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-uml#177]

**Comment by MathieuAA** [comment]
@jhipster/developers Does the suffix have to match a pattern? Like `^[A-z0-9-_]$`?

**Comment by deepu105** [comment]
there is no validation for this currently

Thanks & Regards,
Deepu

**Comment by MathieuAA** [comment]
I'll be enforcing this pattern for each suffix in JUML. When you guys want to add a validation, drop a message here, I'll update the code.

**Comment by deepu105** [comment]
yes you can do that.

Thanks & Regards,
Deepu
