### ISSUE TITLE
Not getting constraint body (value) from Modelio XMI

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/jhipster-uml#18]
It processes the xmi file, add the constraint (in this case, pattern) to the .jhipster/Entity.json but does not insert the body/value (in this case, a regular expression).

**Comment by MathieuAA** [comment]
Can you try with the latest release? I released the v1.0.5 a few hours ago.

**Comment by marcelinobadin** [comment]
Sure. I have tested and it worked fine. Thank you.
