### ISSUE TITLE
Error message: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by sam888** [jhipster/jhipster-uml#180]
### The issue
Hi,

I see the following error messages when run 
       **jhipster-uml .\northwind-visualParadigm.xmi**

The xmi file is created by Visual Paradigm 13.0 reverse engineering MySQL version of northwind sql (i.e. DB SQL script from https://github.com/dalers/mywind) into ERD then export out the xmi.

Thanks,
Sam

---
#### The stacktrace

```
jhipster-uml .\northwind-visualParadigm.xmi

C:\workspace\jhipster\northwind0> jhipster-uml .\northwind-visualParadigm.xmi
? Please choose between the available editors: I don't see my editor.
An error has occurred:
        UndetectedEditorException
Error message:
        You should report this issue by mentioning what your editor is.
Stack trace:
Error
    at Object.<anonymous> (C:\Users\Sam\AppData\Roaming\npm\node_modules\jhipster-uml\lib\exceptions\undetected_editor_exception.js:7:39)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Sam\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\editor_detector.js:9:33)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)


C:\workspace\jhipster\northwind0> jhipster-uml .\northwind-visualParadigm.xmi
? Please choose between the available editors: umldesigner
An error has occurred:
        TypeError
Error message:
        Cannot read property 'forEach' of undefined
Stack trace:
TypeError: Cannot read property 'forEach' of undefined
    at UMLDesignerParser.findElements (C:\Users\Sam\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\umldesigner_parser.js:33:28)
    at UMLDesignerParser.parse (C:\Users\Sam\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\umldesigner_parser.js:24:8)
    at Object.<anonymous> (C:\Users\Sam\AppData\Roaming\npm\node_modules\jhipster-uml\lib\jhipsteruml.js:61:25)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Sam\AppData\Roaming\npm\node_modules\jhipster-uml\jhipster-uml.js:7:3)
[northwind-visualParadigm.zip](https://github.com/jhipster/jhipster-uml/files/211578/northwind-visualParadigm.zip)


```

---

### Steps to reproduce

---

### The XMI or JDL file
See attached zip file.

---

### Versions

| JHipster           | JHipster UML           |
[northwind-visualParadigm.zip](https://github.com/jhipster/jhipster-uml/files/211596/northwind-visualParadigm.zip)

| ------------------ | ---------------------- |
| `3.0.0` |    `1.6.5`   |

**Comment by MathieuAA** [comment]
Hi, you chose "umldesigner" as your answer. That's why you have this issue.
By the way, reverse-engineered datamodel isn't perfect (sometimes not even good enough) and may cause some issues when using it as input for JHipster UML because editors often uses non-UML types and objects when reverse-engineering.

**Comment by sam888** [comment]
Hi Mathieu,

Thanks for reply. I think the main issue is that the Visual Paradigm is not in the list of available editors in console. So I chosed 'uml designer' and 'I don't see my editor' options instead. Is there any plan to  support Visual Paradigm?

I have tried many tools, none of which let me reverse-engineer UML model from database to export xmi except for Visual Paradigm. If you know of an open source tool that does exactly this, please let me know.

I guess I have no choice but to draw UML model manually in UML Designer then export it out to xmi... 

Thanks,
Sam

**Comment by MathieuAA** [comment]
If VP isn't detected, then the XMI file may be faulty... I'll check that out.
It's normal if you don't see it in the list, if it's detected no interaction is needed.

**Comment by MathieuAA** [comment]
Ok, it's because VP converts the model in a special format that we can't read at all. It basically doesn't convert anything to UML.
It's really weird that VP does that, how did you export the diagram?

**Comment by sam888** [comment]
I see the problem now. The XMI file exported out by VP has 
> <xmi:XMI>

 as outermost element. 
Caused by exporting XMI to file with extension xmi (i.e. blaaa.xmi)

. If VP export it to file with extension uml (i.e. blaaa.uml) then 
>  <uml:Model>

 will be the outermost elemeent. 

Basic step of exporting it is: 
	Project --> Export --> XMI --> Export for UML2 --> ...

The XMI file with UML extension is attached in zip file.
	
If I run jhipster-uml again for xmi file with uml extension, error message will be gone but a new error message appear below

> c:\workspace\jhipster\northwind0>jhipster-uml .\northwind-visualParadigm.uml
> Parser detected: VISUAL PARADIGM.
> 
> No entity has to be generated.

Thanks,
Sam

[northwind-visualParadigm-uml.zip](https://github.com/jhipster/jhipster-uml/files/212524/northwind-visualParadigm-uml.zip)

**Comment by MathieuAA** [comment]
Hi, that may be because you succeeded in generating your entities once before (and your .jhipster folder is not empty).
Try deleting your .jhipster folder and everything should be ok.

**Comment by MathieuAA** [comment]
Did it work? Should we close this thread?

**Comment by sam888** [comment]
Hi,
I am afraid not. I deleted the .jhipster folder & tried it again. Same message as before and the .jhipster folder generated is empty. The UML/xmi data model outputed by VP may be too complicated for jhipster-uml to handle.

Feel free to close this thread if you think it's impractical to try to fix it (i.e. too hard). If that's the case I will stick with drawing UML in **UML Designer** then output it to XMI.

Thanks,
Sam

**Comment by MathieuAA** [comment]
Not too complicated, just invalid. It isn't even compliant with the original XMI spec. That's why JUML can't process it. Did you try to do the same process with another editor?

**Comment by sam888** [comment]
I tried a few other editors, e.g. Modelio, UML Designer. None of them can reverse engineer xmi from existing DB/schema. Let me know if you know one.

Thanks

**Comment by MathieuAA** [comment]
Unfortunately, I don't. I'd have to see what's available.
