### ISSUE TITLE
Validation error when using maxbytes on ImageBlob

### ISSUE THREAD

**Issue by myspivey** [jhipster/jhipster-uml#183]
### The issue
Validation error when using maxbytes on ImageBlob.

---
#### The stacktrace

 jhipster-uml jhipster-jdl.jh
An error has occurred:
	WrongValidationException
Error message:
	The validation 'maxlength' isn't supported for the type 'ImageBlob'.
Stack trace:
Error
    at Object.<anonymous> (/Volumes/Data/.nvm/versions/node/v4.4.3/lib/node_modules/jhipster-uml/lib/exceptions/wrong_validation_exception.js:7:38)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Volumes/Data/.nvm/versions/node/v4.4.3/lib/node_modules/jhipster-uml/lib/editors/modelio_parser.js:10:32)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

---

### Steps to reproduce

Create Jhipster project with SQL type (I am using Postgres). Create JDL file with ImageBlob and maxbytes. Run Jhipster-UML

---

### The XMI or JDL file

entity Make {
    name String required,
    logo ImageBlob maxbytes(1000000),
	created ZonedDateTime required,
    approved Boolean required
}

---

### Versions

| JHipster      3.0.0     | JHipster UML    1.6.5       |
| ------------------ | ---------------------- |
| `JHipster Version` |    `jhipster-uml -v`   |

**Comment by MathieuAA** [comment]
From the stacktrace, you were using `maxlength`. Can you re-check?

**Comment by myspivey** [comment]
That is what is odd, I saw the same thing, however nowhere in the JDL is maxlength used. As soon as I removed maxbytes, it ran.

**Comment by MathieuAA** [comment]
The JDL grammar doesn't perform any kind of check, it's oly after the parsed JDL is received by JHipster UML that we check... I'll test the JDL.

**Comment by MathieuAA** [comment]
Ok, there is a bug somewhere. I'll find it and fix it tonight or tomorrow evening. Thanks for reporting this, and sorry of the inconvenience.

**Comment by myspivey** [comment]
No worries, thought I was crazy. Kept double checking my typing and if I had enough caffeine. Not holding me back right now just came across it. Cheers!

**Comment by MathieuAA** [comment]
Hi, this is a JDL bug. I'll open an issue thread in the issue tracker and commit the fix.
The fix will be shipped in the next release (which may be available before the end of the week).
