### ISSUE TITLE
liquibase changesets wrong when adding a new table with relations and regenerating entities

### ISSUE THREAD

**Issue by heppa** [jhipster/jhipster-uml#186]
### The issue

When adding a new table and a relation from a previously created table in a JDL and running jhipster-uml, liquibase adds the new column and foreign key in the changeset that was created for the generation of the first table previously instead of a new changeset. As the second table is only generated in a later changeset, this leads to an error.

Maybe I'm understanding something wrong here? Isn't jhipster-uml meant to be used to regenerate entities again when they need to be changed including correct liquibase changesets?

### Steps to reproduce
1. run jhipster-uml with 1 entity only.
2. add a second entity in jdl file and add a foreign key in first table (many-to-one One(two) to Two)
3. run jhipster-uml again.

---

### The XMI or JDL file

1.
entity One {
label String
}

2.
entity One {
label String
}

entity Two {
label String
}

relationship ManyToOne{
One(two) to Two}

---

### Versions

| JHipster           | JHipster UML           |
| ------------------ | ---------------------- |
| `3.0.0` |    `1.6.5`   |

**Comment by MathieuAA** [comment]
I'll look into it as soon as my VM works again =/

**Comment by MathieuAA** [comment]
Hi, I've completely changed the way the object-diff works, so as to avoid this problem. As the JDL has been moved to the JHipster Core project, and its use to the JDL subgen, can you test these tools instead of using JHipster UML?
