### ISSUE TITLE
Annotations ManyToMany, OneToMany, ManyToOne do not have the correct import on the classes file.

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/jhipster-uml#19]
Once it creates the domain classes it not insert the correct import to ManyToMany, OneToMany, ManyToOne annotations.

**Comment by MathieuAA** [comment]
Weird. We'll try to reproduce this issue... What version of JHipster-UML are you using? What kind of database (sql, mongodb or cassandra)?

**Comment by marcelinobadin** [comment]
Well, I'm using MongoDB. I got my data model with relationships which I had used for MySQL development, than I have created the project with jHipster (mongo option) and then applied the jhispter-uml. The script creates the relationships but without the correct imports in the classes.

I know that using MongoDB we don't have those relationships but once you are creating it should have some reason, right?

**Comment by marcelinobadin** [comment]
I did some research and I think instead of using ManyToOne and OneToMany annotations we do need to use DBRef and Transient (http://docs.spring.io/spring-data/mongodb/docs/1.3.3.RELEASE/reference/html/mapping-chapter.html)

**Comment by CarlKlagba** [comment]
This is a modeling issue, you can't create relationships between entities in a NoSQL database. For instance, if you want to create two entities, Book and Author, and you want to say that a Book has one Author you would need to add a field *author String* in Book. And the relation between the two entities be will be kept at the application level, not a the database level.

We will patch JHipster-UML so it warns users when they try to use relationships in a NoSQL database.

**Comment by marcelinobadin** [comment]
Ok. Thanks.
