### ISSUE TITLE
Consider allowing 'User' to be defined

### ISSUE THREAD

**Issue by derekmckinnon** [jhipster/jhipster-uml#190]
### The issue

`entitiescreator.js` makes the assumption that the entity `User` is always going to be predefined by the JHipster generator, however this may not always be the case. When creating an application, JHipster allows you to skip creating the User entity and related definitions with the `--skip-user-management` flag.

If you were to try and define a `User` entity, `createEntities` is currently hard-coded to prevent that from happening.

In the application I'm writing, I have very specific requirements for the User entity and naturally chose to just create my own at a later time, hoping to use JDL to express the fields. Unfortunately this is not possible without editing the `createEntities` function.

**Comment by MathieuAA** [comment]
Hi! Sorry, I was on holidays and I didn't want to check my mails.
I'll add it for v1.7.0.
