### ISSUE TITLE
microservice no longer added to Entity.json using .jh

### ISSUE THREAD

**Issue by NilsWild** [jhipster/jhipster-uml#196]
### The issue

microservice name no longer added to Entity.json using jdl studio

---
#### The stacktrace

-
---

### Steps to reproduce

create any entity in jdl studio and add line:
microservice all with testservice

---

### The XMI or JDL file

---

### Versions

jhipster-uml master branch at commit 097c174dc655ce108a29a2415857863fdc95bee0

i know that it has worked at commit d988449416fe022171179c1faaf43675e78d3dc5

**Comment by MathieuAA** [comment]
Hi, the JDL and JHipster UML filled for a divorce procedure... All jokes aside, everything JDL-y that worked before with JUML won't work again, and the master branch is kinda unstable at this point. However, I'll test this case when the JHipster core project is done. I don't want to miss anything. Thanks for reporting this! 

Le 30 juin 2016 23:32:06 GMT+02:00, Nils Wild <notifications@github.com> a écrit :
>### The issue
>
>microservice name no longer added to Entity.json using jdl studio
>
>---
>#### The stacktrace
>
>-
>---
>
>### Steps to reproduce
>
>create any entity in jdl studio with line:
>microservice all with testservice
>
>---
>
>### The XMI or JDL file
>
>
>
>---
>
>### Versions
>
>jhipster-uml master branch at commit
>097c174dc655ce108a29a2415857863fdc95bee0
>
>i know that it has worked at commit
>d988449416fe022171179c1faaf43675e78d3dc5
>
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-uml/issues/196

-- 
Mathieu ABOU-AICHI

**Comment by chrislovecnm** [comment]
So what is the status of microservices?

**Comment by MathieuAA** [comment]
Well, using the master branch is risky. That's why releases exist. For now, you have to work with the latest release. When the next release is... released, you'll have to use the sub gen.

Le 1 juillet 2016 22:02:06 GMT+02:00, Chris Love <notifications@github.com> a écrit :
>So what is the status of microservices?
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-uml/issues/196#issuecomment-230035726

-- 
Mathieu ABOU-AICHI

**Comment by chrislovecnm** [comment]
Yah having issues with the latest release :(  Generator from jdh.  Let me file and issue with Generator

**Comment by steelcoder** [comment]
Hi Mathieu, I've noticed microservice support has been added to the core, but not to jhipster uml yet. If I understand, JHipster UML will be obsolete soon, and we must user jdl import subgenerator instead?

**Comment by MathieuAA** [comment]
What?! Obsolete?! Never! It just won't consume JDL files anymore so that work towards the next big thing can actually happen. And I'm closing this as a release will be done tomorrow that will update the subgen dealing with JDL files.

**Comment by steelcoder** [comment]
Hum, I'm missing something. When I try to compile a jdl / jh file, with 1.6.5, it says microservice token is not supported

**Comment by MathieuAA** [comment]
It's normal, as the JDL as moved out, everything related to the JDL here has not been updated (and won't be). And the microservices can't be specified with this current version. The docs will be updated tomorrow to reflect the changes.

**Comment by steelcoder** [comment]
;)
