### ISSUE TITLE
Entities can contain reserved keywords

### ISSUE THREAD

**Issue by ruddell** [jhipster/jhipster-uml#197]
### The issue
There are several [sets of reserved keywords](https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-constants.js) depending on the database type, normally checked when going through the entity prompts.  Entities generated with jhipster-uml do not check these, which can lead to ambiguous error messages later.

For example, the `index` reserved keyword for MySQL. If you use H2 for development, no errors will appear when inserting/updating entities. When launched in production with SQL, the entities stop working with a generic error message: `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index, region_id, region_name) values (1, 1, 'test')' at line 1`

---
#### The stacktrace
No stacktrace

---

### Steps to reproduce

Generate the Region entity below (notice the reserved word `index`).  

- Running in dev, Region entities can be created, updated, and deleted.  
- Running in prod, Region entities give a generic error.

---

### The XMI or JDL file
```
entity Region {
	regionId Long,
    index Long,
	regionName String
}
```

---

### Versions

| JHipster           | JHipster UML           |
| ------------------ | ---------------------- |
| `master/3.4.2` |    `master/1.6.5`   |

**Note**: I don't normally use JDL/UML so let me know if I'm missing something. Thanks!

**Comment by MathieuAA** [comment]
Hello! I thought JHipster always checked for the keywords... my bad. This should be added in JHipster core, so that JHCore checks whether a string is keyword. JUML would call that method.

**Comment by ricardojlrufino** [comment]
An alternative to allow would be to enable the "quote" of the reserved words

> spring.jpa.properties.hibernate.globally_quoted_identifiers=true
