### ISSUE TITLE
/new?cacheBuster=1468404801560 500 (Internal Server Error) using Jhipster-Uml create Entity

### ISSUE THREAD

**Issue by minu-jain** [jhipster/jhipster-uml#198]
### The issue

I created Entities on mysql Db using Jhiposter-UML. I fist made jh file and then run the command as below:
jhipster-uml a.jh -db sql. My Entities are generated and server is uo.

When ever I am creating a new Entity form list page I am getting internal server error.
angular.js:11500 GET http://localhost:8080/api/industries/new?cacheBuster=1468404801560 500 (Internal Server Error)

Its opening the modal popup and trying to execute the state new and above URl is getting hit automatically using new parameter.It takes up this as entity Id. I am unable to locate from where it is calling this.

---
#### The stacktrace

```
Paste it here!
```

---

### Steps to reproduce

---

### The XMI or JDL file

---

### Versions

| JHipster           | JHipster UML           |
| ------------------ | ---------------------- |
| `JHipster Version` |    `jhipster-uml -v`   |

**Comment by MathieuAA** [comment]
Can you at least supply the JDL file? and the versions of JHipster and JHipster UML? I can't help you without further information.

**Comment by minu-jain** [comment]
Attached is the sample code in jDl file:
I have downloaded the latest code of Jhipster from github.

Command i ran: jhipster-uml a.jh -db sql

entity Industry {
value String required maxlength(50) }

entity CreditType {
module String required maxlength(17),
credit Integer required max(255),
isActive Boolean required ,
createdby Integer required max(255),
updatedby Integer required max(255),
updatedon ZonedDateTime required ,
createdon ZonedDateTime required  }

entity Clients {
companyName String required maxlength(500),
noOfEmployees Long required ,
address String required maxlength(65535),
city Integer required max(255),
state String required maxlength(32),
country String required maxlength(32),
credits Double required max(255),
clientType String required maxlength(7),
clientAccess String required maxlength(8),
salesCoordinatorId Integer required max(255),
emId Integer required max(255),
pmId Integer max(255),
documentUniqueName String required maxlength(128),
isActive Integer required max(255),
isDemo Boolean required ,
createdby Integer required max(255),
updatedby Integer required max(255),
createdon ZonedDateTime required ,
updatedon ZonedDateTime required ,
deleted ZonedDateTime ,
clientApproval Integer max(255) }

entity ClientAlertRequest {
requestId Integer required max(255),
commodityId Integer max(255),
location String maxlength(255),
latitude String maxlength(125),
longtitude String maxlength(125),
isActive String maxlength(2) }

entity ClientBnq {
businessObjective String maxlength(65535),
goals String maxlength(65535),
keyquestions String maxlength(65535),
assumptions String maxlength(65535),
suggestions String maxlength(65535),
geographicalScope String maxlength(65535),
clientsNameDisclosure Boolean ,
contactClientsSupplier Boolean ,
isActive Boolean ,
createdBy Integer required max(255),
updatedBy Integer max(255),
createdOn ZonedDateTime ,
updatedOn ZonedDateTime ,
categoryType String required maxlength(2),
categoryId Integer required max(255),
email String required maxlength(500),
feedbackDate ZonedDateTime ,
acknowledgementMessage String required maxlength(65535),
acknowledgementDate ZonedDateTime  }

entity ClientCredits {
totalCredits Float required ,
isActive Integer required max(255),
withCap Boolean required ,
availableCredits Float required ,
createdby Integer required max(255),
updatedby Integer required max(255),
createdon ZonedDateTime ,
updatedon ZonedDateTime required  }

entity ProjectRequests {
serviceId Integer max(255),
questionaireId Integer required max(255),
projectName String maxlength(65535),
projectImage String required maxlength(255),
authoringImage String required maxlength(255),
emId Integer max(255),
pmId Integer max(255),
userType String maxlength(6),
projectType String maxlength(12),
coreType String required maxlength(2),
sowStatus String required maxlength(2),
thoughtleadershipType String maxlength(14),
corereportType Integer max(255),
coreStatus String maxlength(11),
coreReportCount Integer max(255),
stakeHolder String maxlength(50),
credits Float ,
actualCredits Float ,
beroeCredits Float ,
actualHours String maxlength(50),
status String maxlength(15),
estimatedStartDate ZonedDateTime ,
estimatedEndDate ZonedDateTime ,
actualStartDate ZonedDateTime ,
actualEndDate ZonedDateTime ,
actualDeliveryDate ZonedDateTime ,
formattingDate ZonedDateTime ,
qaInTime ZonedDateTime ,
qaApprovedDate ZonedDateTime ,
qaStatus String maxlength(9),
refreshPeriod ZonedDateTime ,
clientInformation String maxlength(65535),
parentId Integer max(255),
timeZone String required maxlength(9),
isActive Boolean ,
uploadedSupplier String required maxlength(255),
createdBy Integer max(255),
updatedBy Integer max(255),
createdOn ZonedDateTime ,
updatedOn ZonedDateTime ,
projectCode String required maxlength(35),
prEditformStatus Integer max(255),
prHour String maxlength(35),
prParentId Integer max(255),
prTotalReports Integer max(255),
periodicType String maxlength(9),
periodicity String maxlength(12),
periodicReportDate ZonedDateTime ,
percentage Integer required max(255),
approvedBy Integer max(255),
approvedRole Integer max(255),
approvedDate ZonedDateTime ,
noOfSlides Integer max(255),
updateRefId Integer required max(255),
updateSrcId Integer required max(255) }

entity ClientProjectCredit {
credit Integer required max(255),
creditDeductionId Integer required max(255),
downloadBy Integer max(255),
downloadedDate ZonedDateTime  }

entity Spendpool {
description String maxlength(2000),
name String required maxlength(75),
version Integer max(255),
thumbnailPath String maxlength(75) }

entity ProcurementCategory {
description String maxlength(2000),
name String required maxlength(75),
version Integer max(255),
thumbnailPath String maxlength(75) }

entity Commodity {
commodityName String required maxlength(500),
isDuplicate Integer required max(255),
isActive Integer required max(255),
createdby Integer required max(255),
updatedby Integer required max(255),
createdon ZonedDateTime required ,
updatedon ZonedDateTime required  }

entity Currencypair {
currencyName String required maxlength(500),
isDuplicate Integer required max(255),
isActive Integer required max(255),
createdby Integer required max(255),
updatedby Integer required max(255),
createdon ZonedDateTime required ,
updatedon ZonedDateTime required  }

entity Deliverable {
name String required maxlength(500),
hours Integer max(255),
isActive Integer required max(255),
createdon ZonedDateTime required  }

entity ProjectComments {
userId Integer required max(255),
userType String required maxlength(6),
comment String maxlength(65535),
remark String maxlength(65535),
createdOn ZonedDateTime required ,
updatedOn ZonedDateTime required ,
isActive Integer required max(255) }

entity ProjectDeliverable {
subdelId Integer required max(255),
isActive Integer required max(255),
createdon ZonedDateTime required  }

entity ProjectFeedback {
clientId Integer required max(255),
scopingRigor String maxlength(20),
understandingBusinessObjectives String maxlength(20),
reportQuality String maxlength(20),
timeliness String maxlength(20),
valueProposition String maxlength(20),
categorySpecialization String maxlength(20),
clientBusinessUnderstanding Float required ,
understandingCategory Float required ,
criticalCategoryNewsUpdate Float required ,
softBenefits Float required ,
hardBenefits Float required ,
rightLevelEngagement Float required ,
overallValueAdd Float required ,
roleAdvisor Float required ,
innovation Float required ,
proactivepushStrategicMi Float required ,
engagmentOverallvalue Float required ,
engagmentRemarks String required maxlength(65535),
categoryOverallvalue Float required ,
strategicMiRecommendations String required maxlength(65535),
categoryRemarks String required maxlength(65535),
deliverdValue Integer required max(255),
beroeAgain Integer required max(255),
beroeColleague Integer required max(255),
projectUnderstanding String maxlength(20),
quality String maxlength(20),
timing String maxlength(20),
customerService String maxlength(20),
communication String maxlength(20),
overallValue String maxlength(20),
remarks String maxlength(65535),
isActive Boolean ,
createdby Integer max(255),
updatedby Integer max(255),
createdon ZonedDateTime ,
updatedon ZonedDateTime  }

entity ProjectFiles {
userId Integer required max(255),
roleId Integer required max(255),
documentUniqueName String maxlength(250),
fileName String maxlength(256),
fileType String maxlength(256),
fileSize String maxlength(128),
fileExtension String maxlength(128),
isActive Integer required max(255),
createdBy Integer required max(255),
updatedBy Integer required max(255),
createdon ZonedDateTime required ,
updatedon ZonedDateTime required  }

entity ProjectRecords {
recordType String maxlength(10),
recordData Integer max(255),
createdOn ZonedDateTime required ,
updatedOn ZonedDateTime required  }

entity ProjectUsers {
domainId String maxlength(254),
clusterId Integer max(255),
categoryId Integer max(255),
actualCluster Integer required max(255),
actualDomain Integer required max(255),
actualCategory String required maxlength(255),
isDuplicate Integer required max(255),
roleId Integer max(255),
userId Integer max(255),
hours Float required ,
isActive Boolean ,
createdby Integer max(255),
updatedby Integer max(255),
createdon ZonedDateTime ,
updatedon ZonedDateTime ,
releasedon ZonedDateTime required  }

entity ProjectStatus {
status String required maxlength(15),
isActive Boolean ,
createdby Integer max(255),
updatedby Integer max(255),
createdon ZonedDateTime ,
updatedon ZonedDateTime  }

relationship OneToMany {
Industry{clientsCollection} to Clients{industryId} ,
CreditType{clientsCollection} to Clients{creditsType} ,
CreditType{clientCreditsCollection} to ClientCredits{creditTypeId} ,
Clients{clientProjectCreditCollection} to ClientProjectCredit{clientId} ,
Clients{projectRequestsCollection} to ProjectRequests{clientId} ,
Clients{clientAlertRequestCollection} to ClientAlertRequest{clientId} ,
Clients{clientCreditsCollection} to ClientCredits{clientId} ,
ClientBnq{projectRequestsCollection} to ProjectRequests{clientBnqId} ,
ProjectRequests{projectFilesCollection} to ProjectFiles{projectId} ,
ProjectRequests{projectRecordsCollection} to ProjectRecords{projectId} ,
ProjectRequests{projectStatusCollection} to ProjectStatus{projectId} ,
ProjectRequests{projectUsersCollection} to ProjectUsers{projectId} ,
ProjectRequests{projectFeedbackCollection} to ProjectFeedback{projectId} ,
ProjectRequests{clientProjectCreditCollection} to ClientProjectCredit{projectId} ,
ProjectRequests{projectCommentsCollection} to ProjectComments{projectId} ,
ProjectRequests{projectDeliverableCollection} to ProjectDeliverable{projectId} ,
Spendpool{procurementCategoryCollection} to ProcurementCategory{spendpoolId} ,
ProcurementCategory{commodityCollection} to Commodity{categoryId} ,
Deliverable{projectDeliverableCollection} to ProjectDeliverable{deliverableId} 
}

paginate * with pagination

**Comment by minu-jain** [comment]
I treid with below sample also:
I have downloaded latest code from  github:




entity Industry {
value String required maxlength(50) }

entity CreditType {
module String required maxlength(17),
credit Integer required max(255),
isActive Boolean required ,
createdby Integer required max(255),
updatedby Integer required max(255),
updatedon ZonedDateTime required ,
createdon ZonedDateTime required  }

**Comment by minu-jain** [comment]
![issue](https://cloud.githubusercontent.com/assets/20437424/16829658/6074eed0-49b7-11e6-97a3-24f384b72f61.png)
  As u can see the error.internal server error and the GET request that is firing

**Comment by MathieuAA** [comment]
Well, as JHipster UML can't parse JDL, you should use the last release.
That being said, did you change the code in some way? You should post this issue [there](https://github.com/jhipster/generator-jhipster/issues) instead... I don't see how JHipster UML is related to this issue.

**Comment by minu-jain** [comment]
i didnot change the code. Just downloaded. Write JDL file and run the command.
On all new entitiues it is giving this error. On already present entity like Bank account, Label operation its not giving error,

**Comment by MathieuAA** [comment]
I'm closing this issue, with your permission @minu-jain, as [this issue](https://github.com/jhipster/generator-jhipster/issues/3845) has been closed as well.
