### ISSUE TITLE
Entities generated by jhipster-uml don't extend AbstractAuditingEntity

### ISSUE THREAD

**Issue by mwhitis** [jhipster/jhipster-uml#199]
## The issue

Just created a number of entities for a new app, and noticed that the entities generated don't extend AbstractAuditingEntity.  Just curious if this is by design, or if it's an issue?  I don't mind submitting a PR for this if it's something that can be fixed and/or configured, but wasn't sure of the thought behind it.

---

### Steps to reproduce

Run jhipster-uml against the attached jdl file

---

### The XMI or JDL file

[jdl.jh.txt](https://github.com/jhipster/jhipster-uml/files/371801/jdl.jh.txt)

---

### Versions

JHipster: 3.4.2
JHipster-uml: 1.6.5

**Comment by MathieuAA** [comment]
Hi! I believe it was already answered everywhere like [here](https://github.com/jhipster/jhipster-uml/issues/27) and [there](https://github.com/jhipster/generator-jhipster/issues/3674).
The long version is that it can't be done with the generator right now. That's why the audit module exists.
