### ISSUE TITLE
Would be nice to have the option to not overwrite some files once you are recreating some entity as the generator does

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/jhipster-uml#20]

**Comment by myspivey** [comment]
I agree. The ability to turn force off would be great.

**Comment by MathieuAA** [comment]
We could make it available as an argument. But I'd hate to further pollute the args...
I'll try some things in the meantime to implement this.

**Comment by marcelinobadin** [comment]
Cool. You can think on something like jhipster generator does. It detects if the file is identical or if you want to skip or overwrite.

**Comment by MathieuAA** [comment]
I have implemented this, see: c658aa1. 
Closing this thread, thanks @marcelinobadin and @myspivey  for the suggestion!
