### ISSUE TITLE
jdl microservice not recognized

### ISSUE THREAD

**Issue by MehrCurry** [jhipster/jhipster-uml#202]
### The issue
I added the following line to working jdl definition:

`microservice * with backend`

Now jhipster-uml telling me

```
An error has occurred:
        SyntaxError
At line 76, column 1.
Error message:
        Expected "/*", "//", "dto", "entity", "enum", "paginate", "relationship", "service", a space or end of input but "m" found.
```  
---
#### The stacktrace

```
Stack trace:
SyntaxError: Expected "/*", "//", "dto", "entity", "enum", "paginate", "relationship", "service", a space or end of input but "m" found.
    at peg$buildException (C:\Users\Guido\AppData\Roaming\npm\node_modules\jhipster-uml\lib\dsl\jhGrammar.js:386:14)
    at Object.peg$parse [as parse] (C:\Users\Guido\AppData\Roaming\npm\node_modules\jhipster-uml\lib\dsl\jhGrammar.js:4739:13)
    at Object.exports.createParser (C:\Users\Guido\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\parser_factory.js:36:48)
    at Object.<anonymous> (C:\Users\Guido\AppData\Roaming\npm\node_modules\jhipster-uml\lib\jhipsteruml.js:60:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

---

### Steps to reproduce

---

### The XMI or JDL file
entity Product {
	key String required
	name String required
    description String
    rule String
}

microservice * with backend
service all with serviceClass

---

### Versions

| JHipster           | JHipster UML           |
| ------------------ | ---------------------- |
| 3.4.2 |    1.6,5   |

**Comment by MathieuAA** [comment]
Hi. JHipster UML doesn't deal with the JDL anymore. You have to use the subgen for that.

Le 7 août 2016 08:15:27 GMT+02:00, MehrCurry <notifications@github.com> a écrit :
>### The issue
>I added the following line to working jdl definition:
>
>`microservice * with backend`
>
>Now jhipster-uml telling me
>
>```
>An error has occurred:
>        SyntaxError
>At line 76, column 1.
>Error message:
>Expected "/*", "//", "dto", "entity", "enum", "paginate",
>"relationship", "service", a space or end of input but "m" found.
>```  
>---
>#### The stacktrace
>
>```
>Stack trace:
>SyntaxError: Expected "/*", "//", "dto", "entity", "enum", "paginate",
>"relationship", "service", a space or end of input but "m" found.
>at peg$buildException
>(C:\Users\Guido\AppData\Roaming\npm\node_modules\jhipster-uml\lib\dsl\jhGrammar.js:386:14)
>at Object.peg$parse [as parse]
>(C:\Users\Guido\AppData\Roaming\npm\node_modules\jhipster-uml\lib\dsl\jhGrammar.js:4739:13)
>at Object.exports.createParser
>(C:\Users\Guido\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\parser_factory.js:36:48)
>at Object.<anonymous>
>(C:\Users\Guido\AppData\Roaming\npm\node_modules\jhipster-uml\lib\jhipsteruml.js:60:28)
>    at Module._compile (module.js:409:26)
>    at Object.Module._extensions..js (module.js:416:10)
>    at Module.load (module.js:343:32)
>    at Function.Module._load (module.js:300:12)
>    at Module.require (module.js:353:17)
>    at require (internal/module.js:12:17)
>```
>
>---
>
>### Steps to reproduce
>
>
>
>
>---
>
>### The XMI or JDL file
>entity Product {
>	key String required
>	name String required
>    description String
>    rule String
>}
>
>microservice * with backend
>service all with serviceClass
>
>---
>
>### Versions
>
>| JHipster           | JHipster UML           |
>| ------------------ | ---------------------- |
>| 3.4.2 |    1.6,5   |
>
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-uml/issues/202

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment]
Update: here is the command you should use from now on: `yo jhipster:import-jdl my_file.jdl`.
