### ISSUE TITLE
entities fields with SQL Reserved Words causing errors 

### ISSUE THREAD

**Issue by sohibegit** [jhipster/jhipster-uml#204]
### The issue
for example:

entity Invoice{
	order Order
}

I guess this should not be allowed because "order" is an SQL Reserved Words in some DBs.

Note: the error is only happening when performing any of the Entity database operations.

---
#### The stacktrace

```
Paste it here!
```

---

### Steps to reproduce

---

### The XMI or JDL file

---

### Versions

| JHipster    | JHipster UML   |
| -------------  | ------------------ - |
| `3.5.1`       |        `1.6.5`       |

**Comment by MathieuAA** [comment]
Hi, even though it's not a bug per se, it shoould be noticed by JUML. I should be able to fix that pretty quickly. Thanks for reporting this!
