### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by somewhereMrli** [jhipster/jhipster-uml#215]
Why not generate code from the database, so as long as the tools to support the generation of the database can be easily used, and now this is generated from the xml code is not suitable for complex engineering code migration.

**Comment by MathieuAA** [comment]
Because JHipster UML's purpose is not to generate code and not to get DB data and create things out of it.
I think you may be missing the point JHipster UML is making: this project only deals with UML file exported by UML editors.
Oh and please, use a correct issue name next time.
