### ISSUE TITLE
Entities generation is blocked

### ISSUE THREAD

**Issue by boubou158** [jhipster/jhipster-uml#217]
### The issue

Hello,

I'm having an issue with jhipster-uml. When I try to use jhipster-uml modelio.xmi (the example from the jhipster website), the *.json are generated into /.jhipster folder but when it tries to loop on each .json entities to create it, the script is blocked after the first or the second entity creation and nothing happen after. (I let the jhipster-uml running all the night and it was still blocked)

Do you have any idea what is going wrong?

---
#### The stacktrace

Creating:
    JobHistory
    Job
    Department
    Employee
    Location
    Country
    Region
    Task

Found the .jhipster/JobHistory.json configuration file, entity can be automatically generated!

The entity JobHistory is being updated.

   create src/main/resources/config/liquibase/changelog/20161020112044_added_entity_JobHistory.xml
   create src/main/resources/config/liquibase/changelog/20161020112044_added_entity_constraints_JobHistory.xml
    force src/main/resources/config/liquibase/master.xml
   create src/main/java/fr/rte/verso/back/ms/domain/JobHistory.java
   create src/main/java/fr/rte/verso/back/ms/repository/JobHistoryRepository.java
   create src/main/java/fr/rte/verso/back/ms/web/rest/JobHistoryResource.java
    force src/main/resources/ehcache.xml
   create src/test/java/fr/rte/verso/back/ms/web/rest/JobHistoryResourceIntTest.java
### The XMI file

Example jhipster website : modelio.xmi

---
### Versions

Jhipster-uml 2.0.0
Node v6.9.1
generator-jhipster v3.9.1
yeoman-generator v0.24.1
Ubuntu 15.10

Thanks a lot in advance!

**Comment by MathieuAA** [comment]
Weird. What is the version of the generator you are using?

**Comment by boubou158** [comment]
Thanks for your answer. My configuration is 

npm -g list | grep generator

├─┬ generator-jhipster@3.9.1
│ ├─┬ yeoman-generator@0.24.1
│ │ │ └─┬ yeoman-generator@0.23.4

Let me know if you need more informations, i'm new on github :)
I think the mechanism launched to copy the last file "src/test/java/fr/rte/verso/back/ms/web/rest/JobHistoryResourceIntTest.java" never ends. Do you have any idea of what mechanism is used? Maybe i have trouble with user rights but i can't see any exceptions raised ..

**Comment by MathieuAA** [comment]
There never is any exception at all. Are there any process that can slow/block the writing operation?

**Comment by MathieuAA** [comment]
Weird.. I'm wondering whether Node changed their API. I'll test some things tomorrow or during the week-end.
The kind of processes that can block or slow an IO are writing operation which write in volume and keep the disk busy.

**Comment by boubou158** [comment]
Which version of node do you recommand? I tried 5.12.0 and i had the same problem. 
Is the npm module "fs" used to copy the files? Maybe the problem comes from that...

**Comment by MathieuAA** [comment]
Maybe. I didn't have any problem last time I checked.

**Comment by MathieuAA** [comment]
Ran my tests with node v6.7.0, v2.0.0 of JUML and v3.9.0 of the generator, nothing.
Ran another test with node v6.70, v2.0.0 of JUML and (the last) v3.9.1 of the generator, still nothing.
However, I couldn't test with the latest version of node as it's not yet available for my platform, and the changelogs are inconclusive.

As far as I am concerned, the part that takes the longest is the gulpyone:
```
Running gulp Inject to add javascript to index

[22:39:54] Using gulpfile ~/jhipster/test/gulpfile.js
[22:39:54] Starting 'inject:app'...
[22:39:54] gulp-inject 160 files into index.html.
[22:39:54] Finished 'inject:app' after 321 ms
```

Did you follow the instructions when you installed JHipster and installed everything detailed [there](https://jhipster.github.io/installation/)?

**Comment by MathieuAA** [comment]
Closing as I don't have any more data to work on.
