### ISSUE TITLE
Installation of jhipster-uml

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-uml#218]
The current doc recommends global installation but I've had issues when using apps with different versions of JHipster (typically v3.x vs v2.x).
So my workflow is to install jhipster-uml locally with `npm install jhipster-uml --save-dev` and then use it from the project dir with `$(npm bin)/jhipster-uml myJhipsterApp.jdl` 
Then it's a matter of finding the good jhipster-uml version corresponding to the generator-jhipster version of the app. It would be great to have a compatibility matrix for that !

**Comment by MathieuAA** [comment]
Hi Christophe. Yes it would be. I'll try to get it done tomorrow or during the week-end.

**Comment by MathieuAA** [comment]
A PR has been made, so I'm closing this. By the way, JUML doesn't deal with JDL files any more, it just exports them from any supported XMI file.
