### ISSUE TITLE
Improve the passing of args

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-uml#220]
So that passing `--option-key value1 value2` is possible.

**Comment by Dufgui** [comment]
For this subject : globally improve args, why not create a config file. Just like the yo-rc.yml for the generator: jhipster-uml.yml

And this file contains option of command line and maybe some other more advanced....

What do you think about that ?

**Comment by MathieuAA** [comment]
That's a reason I've created the .juml file, but don't want to have some solid and static conf for the project.
To be more precise, one could do something like `--dto mapstruct all` instead of `--dto mapstruct entity_1 ...`

**Comment by MathieuAA** [comment]
New and way better idea: use the `.juml` file and name it `jumlfile`

**Comment by Dufgui** [comment]
Hello, with my test I discover the no fluent methods seems not working.
`
node ../../../opensource/jhipster-uml/jhipster-uml.js ../../jhipster-uml/test/xmi/genmymodel.xmi --no-fluent-methods
Unknown argument: fluent-methods

See  -h/--help for available options
`

Could you confirm it's not working ?
Could i fix it in the same commit (replace no-fluent-methods by fluent-methods with default true.) ?
And fix all usage.

**Comment by MathieuAA** [comment]
Yes
