### ISSUE TITLE
Support packages

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-uml#221]
Mirror of #86

**Comment by Dufgui** [comment]
Could you detail a little some issue like this. Just to see if I can take some of them. please ;o)

**Comment by MathieuAA** [comment]
I assume you are familiar with packages? As in Java's packages.
Some UML editors propose to have them and some users actually use them.
The point is to, for each editor:
  - See if packages are supported (I think they are for all three -- soon four),
  - Add the support.

The major problem I have with packages is that parsing a package tree is actually not that easy as it would require parsing the XMI file, doing the usual business of detecting and then adding things, then if packages exist, parse the package. Right, it wouldn't be too hard as the editors were revamped for v2.0.0.
Moreover, I expect users would want to specify packages so that their JHipster app will have these packages (com.app.jhipster.domain.MY_PACKAGE).

It's not a priority actually, but it would be nice to have the package support, one day.

**Comment by Dufgui** [comment]
So UML Designer manage package, modelio too, and genmymodel too (http://blog.genmymodel.com/releases-notes-september-2013.html). So I start by create a unit on UML Designer and add it in ParsedData. But after we must add it the json and manage it in the entity generator.

**Comment by MathieuAA** [comment]
Except that there's no package info on the entity level. That may be temporary, and it's not important. The most important part is not to forget that packages exist to be ignored by JUML, for now at least.

**Comment by Dufgui** [comment]
Yes it's not exist yet at entity level. What is the process to ask a change on it ?

**Comment by Dufgui** [comment]
I will parser package and add it in parsed date in all tools before the change of the json

**Comment by MathieuAA** [comment]
@Dufgui I'm going to pin you as an assignee for this ticket. I'll be one too when I finish what I'm doing. Are you okay with this?

**Comment by Dufgui** [comment]
yes, I start this already, you can assign me on this one

**Comment by Dufgui** [comment]
So here it is ;o). It's just parse element inside package. But I think we can easly add package in parsedData but it's maybe a little too early. Maybe we must wait decision with the generator and the core.

**Comment by MathieuAA** [comment]
I'll review it tomorrow, thanks

Le 31 octobre 2016 21:50:59 GMT+01:00, Duff <notifications@github.com> a écrit :
>So here it is ;o). It's just parse element inside package. But I think
>we can easly add package in parsedData but it's maybe a little too
>early. Maybe we must wait decision with the generator and the core.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-uml/issues/221#issuecomment-257416883

-- 
Mathieu ABOU-AICHI
