### ISSUE TITLE
Regenerate entity with jhipster uml create duplicate liquibase file

### ISSUE THREAD

**Issue by Dufgui** [jhipster/jhipster-uml#224]
### The issue

When you recreate twice time the same entity with jhipster uml , the changelogDate is updated. 
So on the entity generator, it don't find the old liquibase file and updated it.  And instead recreate a new one and don't delete the old one. So duplicate table creation when we start the test.

---
### The command

---
#### The stacktrace

```
Paste it here!
```

---

### Steps to reproduce

create an uml with a simple entity. 
generate the jhipster entity
change the uml
regenerate the entity
launch the test in the application.

---

### The XMI file

---

### Versions 

| JHipster           | JHipster UML           |
| ------------------ | ---------------------- |
| `3.9.1` |    `3182520621231ba017d2f35ffd6dbd74eb9b8ddb`   |

I can do a PR for this, but just defined , how you want to fix it (add old date in entity, improve entity generator, ....)

**Comment by MathieuAA** [comment]
Quick question, if I change the UML, it's normal the liquibase changelog changes, right? So, what's the matter?

**Comment by Dufgui** [comment]
Yes but the old file is not updated and instead a new file is created and added in the master.xml. So entity table is created twice and fail the second time. So we must remove manually the old liquibase file and remove reference to them in master.xml

**Comment by MathieuAA** [comment]
I'll look into it tomorrow then.

**Comment by Dufgui** [comment]
I think it's more a problem of process between generator and juml....so it's complicated to define when to change anything ;o)

**Comment by MathieuAA** [comment]
I have an idea. I'll work on that during my week-end.

Le 28 octobre 2016 10:26:51 GMT+02:00, Duff <notifications@github.com> a écrit :
>I think it's more a problem of process between generator and juml....so
>it's complicated to define when to change anything ;o)
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-uml/issues/224#issuecomment-256864791

-- 
Mathieu ABOU-AICHI

**Comment by Dufgui** [comment]
Don't hesite to ask me PR and work on this. As you can see i can code on juml and generators ;o)

**Comment by MathieuAA** [comment]
The problem was that the JSON files were correctly read, but incorrectly accessed in the entitycreator. This provoked the automatic change of the changelogDate...

**Comment by Dufgui** [comment]
Great ! Many thanks
