### ISSUE TITLE
UML Designer : association one (required) to many generate bad test files

### ISSUE THREAD

**Issue by Dufgui** [jhipster/jhipster-uml#225]
### The issue

The entity generator create the following tests lines in createEntity for one to many relation :

`A.setBs(B);`

But Bs is a Set because it's a one to many relation so we expect to have the same line as many to many relation :
`A.getBs().add(B);`

---
### The command

| `Replace the content` |
---
#### The stacktrace

```
Paste it here!
```

---

### Steps to reproduce

---

### The XMI file

```
<?xml version="1.0" encoding="UTF-8"?>
<uml:Model xmi:version="20131001" xmlns:xmi="http://www.omg.org/spec/XMI/20131001" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:uml="http://www.eclipse.org/uml2/5.0.0/UML" xmi:id="_wxy1EIPVEeaFY_lPQPbINQ" name="Model">
  <packageImport xmi:id="_wxy1EYPVEeaFY_lPQPbINQ">
    <importedPackage xmi:type="uml:Model" href="pathmap://UML_LIBRARIES/XMLPrimitiveTypes.library.uml#_0"/>
  </packageImport>
  <packagedElement xmi:type="uml:Class" xmi:id="_wx0Db4PVEeaFY_lPQPbINQ" name="A">
    <ownedAttribute xmi:id="_wx0DcIPVEeaFY_lPQPbINQ" name="name" isOrdered="true">
      <type xmi:type="uml:PrimitiveType" href="pathmap://UML_LIBRARIES/XMLPrimitiveTypes.library.uml#String"/>
      <lowerValue xmi:type="uml:LiteralInteger" xmi:id="_wx0DcYPVEeaFY_lPQPbINQ"/>
    </ownedAttribute>
  </packagedElement>
  <packagedElement xmi:type="uml:Class" xmi:id="_wx0DdoPVEeaFY_lPQPbINQ" name="B">
    <ownedAttribute xmi:id="_wx0Dd4PVEeaFY_lPQPbINQ" name="name" isOrdered="true">
      <type xmi:type="uml:PrimitiveType" href="pathmap://UML_LIBRARIES/XMLPrimitiveTypes.library.uml#String"/>
      <lowerValue xmi:type="uml:LiteralInteger" xmi:id="_wx0DeIPVEeaFY_lPQPbINQ"/>
    </ownedAttribute>
  </packagedElement>
  <packagedElement xmi:type="uml:Association" xmi:id="_BvBzYIS0Eea1grRuuvivtw" memberEnd="_BvBzYYS0Eea1grRuuvivtw _BvCacYS0Eea1grRuuvivtw" navigableOwnedEnd="_BvBzYYS0Eea1grRuuvivtw _BvCacYS0Eea1grRuuvivtw">
    <name xsi:nil="true"/>
    <ownedEnd xmi:id="_BvBzYYS0Eea1grRuuvivtw" name="functionalPort" type="_wx0Db4PVEeaFY_lPQPbINQ" association="_BvBzYIS0Eea1grRuuvivtw">
      <lowerValue xmi:type="uml:LiteralInteger" xmi:id="_BvBzYoS0Eea1grRuuvivtw" value="1"/>
      <upperValue xmi:type="uml:LiteralUnlimitedNatural" xmi:id="_BvCacIS0Eea1grRuuvivtw" value="1"/>
    </ownedEnd>
    <ownedEnd xmi:id="_BvCacYS0Eea1grRuuvivtw" name="alternateFunctions" type="_wx0DdoPVEeaFY_lPQPbINQ" association="_BvBzYIS0Eea1grRuuvivtw">
      <lowerValue xmi:type="uml:LiteralInteger" xmi:id="_BvCacoS0Eea1grRuuvivtw"  value="1"/>
      <upperValue xmi:type="uml:LiteralUnlimitedNatural" xmi:id="_BvCac4S0Eea1grRuuvivtw" value="*"/>
    </ownedEnd>
  </packagedElement>
</uml:Model>
```

---

### Versions 

| JHipster           | JHipster UML           |
| ------------------ | ---------------------- |
| `3.9.1` |    `last commit`   |

**Comment by MathieuAA** [comment]
Help me understand the case here: there's a relationship between A and B so that A (1)->(*) B, right?
So in A's JSON we see a One-to-Many and in B's we see a Many-to-One, there's no Many-to-Many.
Did I make a mistake?

**Comment by Dufgui** [comment]
No mistake, you are right. one A required to many B required

**Comment by MathieuAA** [comment]
So... can I close this?

**Comment by Dufgui** [comment]
Non parce que avec un One To Many tu as quand même un set dans À de B et vu que c'est requis dans les tests il génère A.setB(b). Alors que il devrait faire A.getB().add(b);  @jdubois dit que on devrait pas tomber dans ce cas côté générateur. Mais je sais pas les contrainte qu'il attend côté json génèré. Génère toi même ou si tu veux je t envois le json

**Comment by Dufgui** [comment]
Faudrait comparer le json à celui génère quand tu fait directement le générateur d entité

**Comment by MathieuAA** [comment]
For english people out there (I know there might be some, only a minority), he said "No because`A.getB().add(b);` should be the generated java code".

Frankly, I don't think you're right. I'm going to test it later this afternoon or tonight.

**Comment by MathieuAA** [comment]
If you want the generated JSON files here is the example of Oracle's HR model, for the [Employee](https://github.com/jhipster/jhipster-core/blob/master/test/test_files/jhipster_app/.jhipster/Employee.json) and the [Department](https://github.com/jhipster/jhipster-core/blob/master/test/test_files/jhipster_app/.jhipster/Department.json).

**Comment by Dufgui** [comment]
Sorry for the french, i am not well awaik ;o)

**Comment by Dufgui** [comment]
I just see your fix. You prefer to block it,  it's a choice but in fact there already some xmi information you not use, maybe you can just add a warn and simply don't add the required rule in case of one to many relation, no ? Because it's not a fault to create this in a model. It's just not a feature yet implemented in Jhipster, What do you think about it? (it's just a matter of flexibility fur users against coherence of model and code generated to summarize).

**Comment by MathieuAA** [comment]
Perhaps, yes. Personally, I love to throw things at users (exceptions for instance). I'll change it later.
