### ISSUE TITLE
[fearure]  generic xmi parser

### ISSUE THREAD

**Issue by Dufgui** [jhipster/jhipster-uml#228]
create a generic xmi parser 2.x

**Comment by MathieuAA** [comment]
It could be cool but it will unfortunately never happen as some UML editors export their XMI files with some differences:
  - the header (used to detect the editor without asking the user),
  - attributes never are the same (for instance, the enums aren't always the same everywhere),
  - even types differ!

However, I do agree... some editors could be refactored to share the same code.
However, XMI could change overtime (there was a bug in Modelio in v3.4).

Unless UML editors actually respect the XMI spec and export a common XMI file, and JUML's work would be made easy... I don't think there's a chance of seeing it happen =(

**Comment by Dufgui** [comment]
;o(
