### ISSUE TITLE
jhipster-uml menu options not working

### ISSUE THREAD

**Issue by KieranHIrl** [jhipster/jhipster-uml#233]
This issue is the same on window cmd and git bash. When I try to run the command below it provides an option of 1. umldesigner or 2. I don't see my editor. I am not able to navigate the menu options with my keyboard. I am able to navigate similar menu options when running yo jhipster?

jhipster-uml sample2.xmi
? Please choose between the available editors: (Press <space> to select, <a> to toggle all, <i> to inverse selection)
>( ) umldesigner
 ( ) I don't see my editor.

### The command
jhipster-uml

When I hit enter as I am not able to select either option, it returns below
jhipster-uml sample2.xmi
? Please choose between the available editors: (Press <space> to select, <a> to toggle all, <i> to inverse selection)
? Please choose between the available editors: (Press <space> to select, <a> to toggle all, <i> to inverse selection)
An error has occurred:
        TypeError
Error message:
        Cannot read property 'parse' of undefined
Stack trace:
TypeError: Cannot read property 'parse' of undefined
    at Object.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\jhipster-uml\lib\jhipsteruml.js:54:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\jhipster-uml\jhipster-uml.js:7:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

### Versions 
JHipster Generator v3.10.0
JHipster UML is 2.0.1

smaple2.xmi below:
[sample2.zip](https://github.com/jhipster/jhipster-uml/files/583830/sample2.zip)

**Comment by PierreBesson** [comment]
What is your version of node ?

**Comment by KieranHIrl** [comment]
Hi Pierre, v4.4.7. Thanks, K

**Comment by MathieuAA** [comment]
I've already seen this kind of error... Are you on windows?

**Comment by KieranHIrl** [comment]
Yes @MathieuAA , Windows 10 64 bit os. Thanks, K

**Comment by MathieuAA** [comment]
Do you use git bash? (have you tried with powershell?)

Le 10 novembre 2016 19:26:32 GMT+01:00, KieranHIrl <notifications@github.com> a écrit :
>Yes @MathieuAA , Windows 10 64 bit os. Thanks, K 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-uml/issues/233#issuecomment-259767813

-- 
Mathieu ABOU-AICHI

**Comment by KieranHIrl** [comment]
Hi @MathieuAA , I just tried and it is the same for both git bash and powershell. Any idea to resolve would be greatly appreciated. Cheers K

**Comment by MathieuAA** [comment]
That's weird... Have you checked [this](https://gist.github.com/nullivex/7115612) link and [this one](https://gist.github.com/Spudz76/7166291)? It explains what to install if you're playing with Node on Windows (everything may not be useful for you, but you get the gist).
There might be a good solution if you're Windows, have you tried [babun](https://babun.github.io/)? And if you're hipster enough you could also use the [oh-my-zsh plugin](https://jhipster.github.io/oh-my-zsh/).

**Comment by KieranHIrl** [comment]
Hi @MathieuAA , Tried using vagrant box with JHipster installed. I was able to select an option but when selecting 'I don't see my editor.' I got the error below.Note I am using Visual Paradigm to generate XMI from 'Reverse DB':
vagrant@vagrant:~/Desktop/jhipsterxmi$ jhipster-uml exportCRXmi.xmi
? Please choose between the available editors: I don't see my editor.
An error has occurred:
        UndetectedEditorException
Error message:
        You should report this issue by mentioning what your editor is.
Stack trace:
Error
    at Object.<anonymous> (/usr/lib/node_modules/jhipster-uml/lib/exceptions/undetected_editor_exception.js:7:39)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/jhipster-uml/lib/editors/editor_detector.js:9:33)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by MathieuAA** [comment]
Visual Paradigm is no longer supported...

Le 11 novembre 2016 10:45:24 GMT+01:00, KieranHIrl <notifications@github.com> a écrit :
>Hi @MathieuAA , Tried using vagrant box with JHipster installed. I was
>able to select an option but when selecting 'I don't see my editor.' I
>got the error below.Note I am using Visual Paradigm to generate XMI
>from 'Reverse DB':
>vagrant@vagrant:~/Desktop/jhipsterxmi$ jhipster-uml exportCRXmi.xmi
>? Please choose between the available editors: I don't see my editor.
>An error has occurred:
>        UndetectedEditorException
>Error message:
>        You should report this issue by mentioning what your editor is.
>Stack trace:
>Error
>at Object.<anonymous>
>(/usr/lib/node_modules/jhipster-uml/lib/exceptions/undetected_editor_exception.js:7:39)
>    at Module._compile (module.js:409:26)
>    at Object.Module._extensions..js (module.js:416:10)
>    at Module.load (module.js:343:32)
>    at Function.Module._load (module.js:300:12)
>    at Module.require (module.js:353:17)
>    at require (internal/module.js:12:17)
>at Object.<anonymous>
>(/usr/lib/node_modules/jhipster-uml/lib/editors/editor_detector.js:9:33)
>    at Module._compile (module.js:409:26)
>    at Object.Module._extensions..js (module.js:416:10)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-uml/issues/233#issuecomment-259920261

-- 
Mathieu ABOU-AICHI

**Comment by KieranHIrl** [comment]
Thanks @MathieuAA , Is there a step-by-step guide using UMLDesigner or other software that would allow me to take an existing MySQL database and create an example.xmi file that I can use with jhipster-uml example.xmi command? Cheers K

**Comment by MathieuAA** [comment]
Unfortunately, no. Not yet anyway.

Le 11 novembre 2016 12:02:29 GMT+01:00, KieranHIrl <notifications@github.com> a écrit :
>Thanks @MathieuAA , Is there a step-by-step guide using UMLDesigner or
>other software that would allow me to take an existing MySQL database
>and create an example.xmi file that I can use with jhipster-uml
>example.xmi command? Cheers K
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-uml/issues/233#issuecomment-259934178

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment]
Using UMLDesigner is documented though...

**Comment by KieranHIrl** [comment]
Thanks @MathieuAA , I'll check it out. Cheers, K
