### ISSUE TITLE
How can I specify the entity field to be shown in UI when setting up a one to one composition?

### ISSUE THREAD

**Issue by abrahamjins** [jhipster/jhipster-uml#235]
First of all, I would like to sorry for asking my doubts on this platform.
I came across a scenario where I want to setting up a relation, a one to one composition, between entities for eg, Country and Region. My intention is to configure relationship in such a way that I can select the 'regionCode', when am creating a Country. Please see below relationship created.Now am getting a value 'undefined' in the select field for region.

![region-country](https://cloud.githubusercontent.com/assets/17870997/20266563/b0156ffa-aa9c-11e6-9c84-550b1bd832cb.jpg)

![image](https://cloud.githubusercontent.com/assets/17870997/20266581/c82b5bfe-aa9c-11e6-9697-4f95347527b3.png)

Kindly help me to sort it out.

---
### The command

| `Replace the content` |
---
#### The stacktrace

```
Paste it here!
```

---

### Steps to reproduce

---

### The XMI file

---

### Versions 

| JHipster           | JHipster UML           |
| ------------------ | ---------------------- |
| `JHipster Version` |    `jhipster-uml -v`   |

**Comment by MathieuAA** [comment]
I suggest you read the doc, [here](https://jhipster.github.io/jhipster-uml/). Search for `Declare the field you want to use to display a relationship in AngularJS`. It works for every type of relationship.

**Comment by abrahamjins** [comment]
Thanks Mathieu.
That is exactly what I did. But the otherEntityField is not showing up, intead it is showing 'undefined'.
I have specified the table name in braces for each entity. Will that be a problem?

**Comment by MathieuAA** [comment]
The table name shouldn't be used, the class name should be however.
