### ISSUE TITLE
LocalDate not implemented

### ISSUE THREAD

**Issue by tomlogghe** [jhipster/jhipster-uml#24]
I copy/pasted the Book example from http://jhipster.github.io/jhipster_uml.html#jdl
It seems the type LocalDate is not implemented in https://github.com/jhipster/jhipster-uml/blob/master/lib/dsl/grammar.txt
This gives the error "Expected a type but "L" found"

**Comment by CarlKlagba** [comment]
The release is done. Go ahead, try and give us feedbacks !

**Comment by tomlogghe** [comment]
Tested with 1.1.1: Fixed. Thanks!
