### ISSUE TITLE
Support Papyrus

### ISSUE THREAD

**Issue by Dufgui** [jhipster/jhipster-uml#246]
Support another uml tools based on XMI :
https://eclipse.org/papyrus/

**Comment by Dufgui** [comment]
I post this here, and if you are ok, i work on it.

**Comment by MathieuAA** [comment]
I'm surprised this tool is still updated. Last I checked it was abandoned. The problem is that not many people use this tool but I'll reconsider adding it. Let me study it first.

**Comment by MathieuAA** [comment]
I'm deprecating this project in favor of the JDL, and this is not happening any time soon.
