### ISSUE TITLE
JHipster UML 2.0.3  (jhipster 2.21.1)

### ISSUE THREAD

**Issue by mansonso** [jhipster/jhipster-uml#247]
### The issue
 when try to generate the entity, 
yo jhipster:import-jdl entity_Vendor_Support.jh

Error!  The table name cannot contain a MYSQL reserved keyword

entity VendorSupport {
	title String required maxlength(255),
	description String required maxlength(3000),
	
	status String required maxlength(20),
	
	createdBy String,
    modifiedBy String,
    created ZonedDateTime,
    modified ZonedDateTime
}

entity VendorSupportReply {
	description String required maxlength(3000),	
	
	createdBy String,
    modifiedBy String,
    created ZonedDateTime,
    modified ZonedDateTime
}

relationship ManyToOne {
	VendorSupportReply{vendorSupport} to VendorSupport
}

---
### The command

| `Replace the content` |
---
#### The stacktrace

```
Paste it here!
```

---

### Steps to reproduce

---

### The XMI file

---

### Versions 

| JHipster           | JHipster UML           |
| ------------------ | ---------------------- |
| `JHipster Version` |    `jhipster-uml -v`   |

**Comment by jdubois** [comment]
The easiest solution: do not use a MySQL reserved keyword... There are other workarounds, of course.

**Comment by jdubois** [comment]
Can you post this on Stackoverflow? This is definitely not a bug.

**Comment by mansonso** [comment]
sure, no problem
