### ISSUE TITLE
DTO functionality is not working

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/jhipster-uml#25]
I'm using the newest (1.1.0) version but not even selecting all or one by one the script is not creating the dto classes.

**Comment by MathieuAA** [comment]
Hi again, from what I see, I notice no differences between our code and the JHipster's code (both use 'no' and 'mapstruct' as values for the 'dto' key). I'm going to test it...

**Comment by MathieuAA** [comment]
I tested the feature (for one, for two non-consecutive, and all entities), and for each class I selected, its corresponding DTO was created.
Go to `src/main/java/com/mycompany/myapp/web/rest/dto/` to find them.

**Comment by marcelinobadin** [comment]
Ooops. My bad. Wrong generator-jhipster version. I have updated and it works fine now.
