### ISSUE TITLE
Doesn't support .jdl and .jh files as input

### ISSUE THREAD

**Issue by BryanYin** [jhipster/jhipster-uml#251]
### The issue
I'm new to jhipster and recently started a project with this fantastic generator. I used JDL Studio to write and downloaded entity files in .jh format. Actually this is only for DB initialization, so I don't want any backend(BE) or frontend(FE) source code generated. So I wrote skipClient and skipServer for all in the jh file. Unfortunately `yo jhipster:import-jdl` skipped my both skips and generated BE and FE code for me. After further investigation on this project, I found jhipster-uml could save my life, but when I try to use this tool to generate code, I got below error. Anything wrong with my steps? I guess jhipster-uml should support his own language JDL but seems not?

---
### The command
jhipster-uml database\entity\config_entities.jdl

---
#### The stacktrace
```
D:\Projects\jhiDemo>jhipster-uml database\entity\config_entities.jdl -f
An error has occurred:
        TypeError
Error message:
        Cannot read property 'hasOwnProperty' of undefined
Stack trace:
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at C:\Users\byin\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\parser_factory.js:65:15
    at Parser.<anonymous> (C:\Users\byin\AppData\Roaming\npm\node_modules\jhipster-uml\node_modules\xml2js\lib\xml2js.js:493:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Object.onerror (C:\Users\byin\AppData\Roaming\npm\node_modules\jhipster-uml\node_modules\xml2js\lib\xml2js.js:311:26)
    at emit (C:\Users\byin\AppData\Roaming\npm\node_modules\jhipster-uml\node_modules\sax\lib\sax.js:640:35)
    at error (C:\Users\byin\AppData\Roaming\npm\node_modules\jhipster-uml\node_modules\sax\lib\sax.js:669:5)
    at strictFail (C:\Users\byin\AppData\Roaming\npm\node_modules\jhipster-uml\node_modules\sax\lib\sax.js:693:7)
    at beginWhiteSpace (C:\Users\byin\AppData\Roaming\npm\node_modules\jhipster-uml\node_modules\sax\lib\sax.js:967:7)
    at Object.write (C:\Users\byin\AppData\Roaming\npm\node_modules\jhipster-uml\node_modules\sax\lib\sax.js:1022:11)
```
---

### Steps to reproduce

see my issue description.

---

### The XMI file
no, i'm using .jh file.

---

### Versions 

| JHipster           | JHipster UML           |
| ------------------ | ---------------------- |
| `JHipster Version` |    `jhipster-uml -v`   |
|4.0.2|2.0.3|

**Comment by MathieuAA** [comment]
It's normal, as the JDL support has been moved to a subgen (you can use it with `yo jhipster:import-jdl YOUR_JDL).`

**Comment by BryanYin** [comment]
`jhipster:import-jdl` was my 1st choice, but it skipped my `skipClient` and `skipServer` configuration, any suggestion?

**Comment by BryanYin** [comment]
another problem is in the document: [https://jhipster.github.io/jhipster-uml/](url) it clearly mentioned JHUML supports .jh and jdl file, suggest you fix that to avoid misunderstanding.

**Comment by MathieuAA** [comment]
Oh? nice catch, completely forgot to remove it, thanks.
As for the import-jdl that doesn't take your skips, can you provide the JDL file? (I'll keep this ticket closed and open a new one in the JHipster Core project instead).

**Comment by BryanYin** [comment]
@MathieuAA It's very simple:
```
entity MonitorLocation (T_MLOCATION) {

	description String maxlength(40),

	geoId Integer,

	operId Integer,

	mpTypeId Integer,

	ip String maxlength(40),

	latitude Float,

	longitude Float
}

skipClient for MonitorLocation
skipServer for MonitorLocation
```

**Comment by MathieuAA** [comment]
The parsing is correctly done, my guess would be to check the subgen...

**Comment by MathieuAA** [comment]
It is the subgen. I'll make a PR to fix it when I have the time. Thanks for reporting it.

**Comment by BryanYin** [comment]
OK. If you created the PR would you mind let me know the PR# in someway so that I can catch the progress, I got a lot of entities to be created that need skip source code generation. Now I'm using git to remove generated codes except liquibase changelogs.

**Comment by MathieuAA** [comment]
Will do.
