### ISSUE TITLE
Incompatible type errors on generated code based on UML file.

### ISSUE THREAD

**Issue by KatonRyu** [jhipster/jhipster-uml#252]
### The issue

Upon compiling the code generated by jHipster-uml, an error is thrown by a generated test. The test creates an instance of ClassA, after which setClassAs(alssAs) is called on an instance of ClassB. This fails, because the parameter of this method is Set<ClassA> and not ClassA. Expected behavior is that the generated code compiles properly.

---
### The command

| `jhipster-uml uml\model.uml` |
---
#### The compilation error

```
Error:(77, 27) java: incompatible types: nl.aenova.flexpool.domain.ClassA cannot be converted to java.util.Set<nl.aenova.flexpool.domain.ClassA>
```

---

### Steps to reproduce

Run jhipster-uml on the UML file.
After the code is successfully generated, compile it.
An error is thrown on the test.

---

### The XMI file

`<?xml version="1.0" encoding="UTF-8"?>
<uml:Model xmi:version="20131001" xmlns:xmi="http://www.omg.org/spec/XMI/20131001" xmlns:uml="http://www.eclipse.org/uml2/5.0.0/UML" xmi:id="_Ch8jMPqWEeaFK-YMjnmGNQ" name="NewModel">
  <packagedElement xmi:type="uml:Class" xmi:id="_FhirYPqXEeaFK-YMjnmGNQ" name="ClassB"/>
  <packagedElement xmi:type="uml:Class" xmi:id="_J0OBgPqXEeaFK-YMjnmGNQ" name="ClassA"/>
  <packagedElement xmi:type="uml:Association" xmi:id="_ssJ3cPqcEeaFK-YMjnmGNQ" name=" " memberEnd="_ssJ3cfqcEeaFK-YMjnmGNQ _ssJ3dPqcEeaFK-YMjnmGNQ" navigableOwnedEnd="_ssJ3cfqcEeaFK-YMjnmGNQ _ssJ3dPqcEeaFK-YMjnmGNQ">
    <ownedEnd xmi:id="_ssJ3cfqcEeaFK-YMjnmGNQ" name="classBs" type="_FhirYPqXEeaFK-YMjnmGNQ" association="_ssJ3cPqcEeaFK-YMjnmGNQ">
      <lowerValue xmi:type="uml:LiteralInteger" xmi:id="_ssJ3cvqcEeaFK-YMjnmGNQ" value="1"/>
      <upperValue xmi:type="uml:LiteralUnlimitedNatural" xmi:id="_ssJ3c_qcEeaFK-YMjnmGNQ" value="1"/>
    </ownedEnd>
    <ownedEnd xmi:id="_ssJ3dPqcEeaFK-YMjnmGNQ" name="classAs" type="_J0OBgPqXEeaFK-YMjnmGNQ" association="_ssJ3cPqcEeaFK-YMjnmGNQ">
      <lowerValue xmi:type="uml:LiteralInteger" xmi:id="_ssJ3dfqcEeaFK-YMjnmGNQ"/>
      <upperValue xmi:type="uml:LiteralUnlimitedNatural" xmi:id="_ssJ3dvqcEeaFK-YMjnmGNQ" value="*"/>
    </ownedEnd>
  </packagedElement>
</uml:Model>`

---

### Versions 
| JHipster           | JHipster UML           |
| ------------------ | ---------------------- |
| `4.0.1` |    `The current version of JHipster UML is 2.0.3`   |

**Comment by MathieuAA** [comment]
Hi, I'll look into it. What editor did you use?

**Comment by MathieuAA** [comment]
Your XMI looks OK. The generated JSON files too.
I don't know why it fails for you to be honest but, can you try not naming your injected fields with the plural form? Instead of naming a field `classAs`, just name it `classA`. JHipster knows how to handle plural forms and deals with it accordingly.

**Comment by KatonRyu** [comment]
Hi, sorry for the late reply. Apparently my mail client decided to treat GitHub messages as spam. We're using UML Designer to make the diagram, and from what we can see the generation itself works but there seems to be an issue with jHipster-UML not taking the parameter type of the setter into account when generating the test. I'll give the singular naming a go and see if that changes anything.

**Comment by MathieuAA** [comment]
I doubt it, the XMI really looks ok. I'll build a heavy test diagram for this case and test it.

**Comment by KatonRyu** [comment]
Thanks for looking into it. If you need more information, I'll be happy to provide it. I've fixed my mail client so there shouldn't be any delays in my replies anymore.

**Comment by MathieuAA** [comment]
Not a problem!
