### ISSUE TITLE
Support for Sparxsystem Enterprise Architect

### ISSUE THREAD

**Issue by m1rc0** [jhipster/jhipster-uml#254]
Hi everybody,

I love the idea of designing my domain model in UML and then use it in my JHipster application. At work we need to use Enterprise Architect which offers different possibilities of exporting XMI (1.1 - 2.x).

See: 
![grafik](https://cloud.githubusercontent.com/assets/1621265/26538589/0b85e514-4448-11e7-9653-4289186ae893.png)

Sadly none seem to work with JHipster UML. I tried exporting the XMI and reimporting it into Modelio but sadly in that case all attribute types are missing. 

Therefore my request, could you please support Enterprise Architect?

**Comment by jdubois** [comment]
Unfortunately this is a commercial tool and we have no license for it.
Maybe this could be the other way around? Enterprise Architect is worth tons of $$$, so maybe with all that money they could support a major tool like JHipster ? :-)

**Comment by MDrock116** [comment]
I really like EA.  It stores your project in a single file which is good for source control.  Modelio stores many files and isn't the best at undo.  JDL-Studio's is cool, just also lacking a clean source control method.

**Comment by MathieuAA** [comment]
@MDrock116 Hi, as Julien has said, it's commercial...
However, if you're willing to develop a parser to make EA a supported parser, that'd be great.
Please do tell me if you're interested in doing this, I could help get up and running.

**Comment by MDrock116** [comment]
Thanks @MathieuAA .  Sorry for the delayed response.  Can't do that now but that's for the offer!  Actually been using JDL Studio a bit more and I really like how it minimizes the code needed to make UML so it actually is easier to source control in that regard.  It also allows for more specific instructions to JHipster which are VERY useful.  Enterprise Architect is a full blown UML tool which offers quite a bit more as far as UML goes than JDL Studio but as JHipster seems to be a superior code generator than any tool I've used and JDL Studio  works with it the best, I think it's worth mirroring Enterprise Arch class diagrams in JDL Studio or just sticking with JDL Studio alone for modeling.

**Comment by MathieuAA** [comment]
@MDrock116 Hi. Yes, JDL Studio should be enough.
I'm closing this ticket for now.
