### ISSUE TITLE
Array in MongoDB in JDL file.

### ISSUE THREAD

**Issue by mayurbais** [jhipster/jhipster-uml#258]
I have a JDL file  listing all my entities and one of them is something like 
entity Section {
	sectionName String,
	code String,
	strength Integer,
	courseId String,// Course,
	locationId String,//  Room,
	mainTeacherId String,//Teacher,
	eventsId String //Event
}

Here I want eventsId to be list of Strings...Is there any way that I can achieve this? 

### Versions 

| JHipster           | JHipster UML           | Editor & version |
| ------------------ | ---------------------- | ---------------- |
| `JHipster Version` |    `jhipster-uml -v`   |                  |

**Comment by MathieuAA** [comment]
@mayurbais There's no way to do it in the JDL, and you're in the wrong project! Go [there](https://github.com/jhipster/jhipster-core) the next time please!
