### ISSUE TITLE
Convert JDL to XMI

### ISSUE THREAD

**Issue by thedoctor0612** [jhipster/jhipster-uml#264]
Please is there a helpful support to generate an XMI file from my JDL file ?
Thanks

**Comment by jdubois** [comment]
This is the bug tracker, not StackOverflow.
Please use StackOverflow with the "jhipster" tag, as mentionned in our guidelines

**Comment by MathieuAA** [comment]
@thedoctor0612 And it isn't possible. XMI is a spec, but is not 100% followed by editors (Modelio, UML Designer, etc.). So if you export one file from Modelio and try to open in it GenMyModel, it won't work.
