### ISSUE TITLE
Bug in docs

### ISSUE THREAD

**Issue by casperravenhorst** [jhipster/jhipster-uml#265]
In this page: http://www.jhipster.tech/jhipster-uml/ under "Use JHipster-UML" arguments of the form `-db <databasetype>` are suggested, but only `--db <databasetype>` will work (so, double dashes). Even though this is very logical, I'd fix it for you.

**Comment by MathieuAA** [comment]
Thanks for catching this! Can you make a PR in jhipster.github.io?

**Comment by casperravenhorst** [comment]
Will do.
