### ISSUE TITLE
Installation of JHipster-UML terminates with error

### ISSUE THREAD

**Issue by eismeraldo** [jhipster/jhipster-uml#266]
### The issue
The installation starts with this command on Windows 10 and python 3.7.2:

D:\TempJHipster\Small>npm install -g jhipster-uml
D:\Appdata\npm\jhipster-uml -> D:\Appdata\npm\node_modules\jhipster-uml\jhipster-uml.js

> deasync@0.1.9 install D:\Appdata\npm\node_modules\jhipster-uml\node_modules\deasync
> node ./build.js

D:\Appdata\npm\node_modules\jhipster-uml\node_modules\deasync>if not defined npm_config_node_gyp (node "D:\Appdata\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Appdata\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: D:\Programme\Python\Python37\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Appdata\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Appdata\npm\node_modules\jhipster-uml\node_modules\deasync
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.9 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Appdata\npm-cache\_logs\2019-02-14T13_19_01_883Z-debug.log

### Suggest a Fix

from
import sys; print "%s.%s.%s" % sys.version_info[:3];
to
import sys; print ("%s.%s.%s" % sys.version_info[:3]);
The Result is then: 3.7.2

### Versions 

| JHipster           | JHipster UML           | Editor & version |
| ------------------ | ---------------------- | ---------------- |
| `JHipster Version` |    `jhipster-uml -v`   |                  |
D:\TempJHipster\Small>jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
small@0.0.0 D:\TempJHipster\Small
`-- generator-jhipster@5.7.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "ch.awi"
        },
        "jhipsterVersion": "5.7.2",
        "applicationType": "monolith",
        "baseName": "Small",
        "packageName": "ch.awi",
        "packageFolder": "ch/awi",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "cacheProvider": "ehcache",
        "enableHibernateCache": true,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "maven",
        "enableSwaggerCodegen": false,
        "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
        "clientFramework": "angularX",
        "useSass": true,
        "clientPackageManager": "npm",
        "testFrameworks": [],
        "jhiPrefix": "jhi",
        "otherModules": [],
        "enableTranslation": false
    }
}

</pre>
</details>

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by erickjvallejo** [comment]
Hi, I think so this can help you, I seems you don´t have the python right version.

https://github.com/nodejs/node-gyp#option-2

**Comment by MathieuAA** [comment]
I'll try to find time to fix this (and deprecate this project).
