### ISSUE TITLE
The type 'Short' isn't supported by JHipster, exiting now.

### ISSUE THREAD

**Issue by seainside75** [jhipster/jhipster-uml#30]
I'm trying to generate domain classes by reverse enginering an existing postgres database via VisualParadigm.
So, I successfully generated ERD and from it then  I generated classes ready to be exported into XMI format.
But, when i try to generate .json file from xmi format I got

![image](https://cloud.githubusercontent.com/assets/2210414/8582379/c42ab452-25c6-11e5-861f-5def2675729d.png)

Please, how can I solve this issue?

**Comment by outis10** [comment]
Short is not a valid type  see Annexes from  documentation, if you work
with SQL database then you should change Short for Integer type.
