### ISSUE TITLE
Add blob support from JHipster.

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-uml#32]
Work to be done:
  - Add blob (`byte[]`);
  - Find a way to specify its content (an image or any binary) for `fieldTypeBlobContent`;
  - Add validations (`required`, `minbytes` and `maxbytes`);
  - Add the mention `fieldsContainBlob`;
  - Add the two mentions of the validations (`fieldValidateRulesMinbytes` and `fieldValidateRulesMaxbytes`).

That should be everything to add (not to mention the wiki).

**Comment by MathieuAA** [comment]
The Blob implementation is paused until it is fixed in JHipster.

**Comment by andidev** [comment]
Great! Does it work in its current state?

By the way, by fixed you mean released?

**Comment by MathieuAA** [comment]
I think it does. The only problem I have is that the tests from JHipster don't pass.

**Comment by MathieuAA** [comment]
The tests are done. Once everything's ok in JHipster, I will merge the blomImpl branch with master.

**Comment by andidev** [comment]
So the test in jhipster fail? Do you mean the maven tests?

**Comment by MathieuAA** [comment]
Yes.

**Comment by andidev** [comment]
I cant reproduce the bug. Could you create an issue in genarator-jhipster with more details?

**Comment by MathieuAA** [comment]
Yes, I will. Will update this thread with the issue's link.
