### ISSUE TITLE
Option to choose 'otherEntityField' and 'pagination'

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/jhipster-uml#34]
Since last version where it only changes the models that we have changed in the XML everything is working very nice. But constantly I have to go to the json file to change the 'otherEntityField' name from id to something else and to add pagination. Once I do that, jhipster-uml detects that this json has been changed and any other change in the other entities make this one to be updated too. Can we have the option to set otherEntityField and pagination. Apparently it is the only thing missing now.

**Comment by CarlKlagba** [comment]
For the pagination we can do something similar as we did for the dto (with the option '-dto'). For the 'otherEntityField' I think we can do it without an option.

**Comment by marcelinobadin** [comment]
Yes, probably for the ‘otherEntityField’ something like constraints. And sure, I think pagination could be an option like –dto, choosing between all and ones that want to have pagination.


Badin, Marcelino G.
INDRA
Digital Systems Engineer
+55 11 3042 3150
+55 11 99279 3279 (mobile)
marcelinobadin@indra.com.br

From: CarlKlagba
Reply-To: jhipster/jhipster-uml
Date: Monday, July 20, 2015 at 9:05 AM
To: jhipster/jhipster-uml
Cc: Marcelino Badin
Subject: Re: [jhipster-uml] Option to choose 'otherEntityField' and 'pagination' (#34)


For the pagination we can do something similar as we did for the dto (with the option '-dto'). For the 'otherEntityField' I think we can do it without an option.

**Comment by CarlKlagba** [comment]
@marcelinobadin  I want to enable user to add  'otherEntityField' like this:

 - UML 

![otherentityfield](https://cloud.githubusercontent.com/assets/8936681/8822080/2176ecec-3063-11e5-8f5a-c1cf10ae47b8.jpeg)

- JDL 


relationship ManyToMany{
      Owner{notOwner(`<otherEntityField>`)} to NotOwner{owner}
}

With `<otherEntityField>` the name you want for 'otherEntityField' .

Is it something intuitive for you? Do you have a better syntax in mind?
My guess is yours.

**Comment by marcelinobadin** [comment]
I think you solution is very cool and yes, it is intuitive. Thank you.

**Comment by CarlKlagba** [comment]
Ok thx ! Just have to do the impl.

**Comment by CarlKlagba** [comment]
The wiki wont be update for a while so this is the doc i made for the change.

## Declare the field you want to use to display a relationship in AngularJS
To do that you must add the field name between `(``)` after the injected field name.

In a One-to-Many relationship you can add it in the 'Many' side of the relationship:

- UML

![jhipsteruml_otherentityfieldom](https://cloud.githubusercontent.com/assets/8936681/8851105/849421ec-314d-11e5-812c-203a2aba5597.jpeg)


- JDL

      relationship OneToMany{
        One{many(`<otherEntityField>`)} to Many{one}
      }

In a Many-to-Many relationship you can add it in the owner side of the entity:

- UML

![jhipsteruml_otherentityfieldmm](https://cloud.githubusercontent.com/assets/8936681/8851109/8fc30600-314d-11e5-968b-64f5760ab1f3.jpeg)

- JDL

      relationship ManyToMany{
        Owner{notOwner(`<otherEntityField>`)} to NotOwner{owner}
      }

## Pagination
You can choose the pagination for your entities using `-paginate`.

 `jhipster-uml <your_file.xmi> [-db (sql | mongodb | cassandra)] [-paginate]`

**Comment by marcelinobadin** [comment]
Cool. @CarlKlagba, I need a little help with Modelio. 

These are my entities. One Map can have Many Positions.
![screen shot 2015-07-23 at 8 21 59 pm](https://cloud.githubusercontent.com/assets/2465770/8864475/aaa23b78-3178-11e5-984e-7152f890a657.png)

Then, once I create the association I would like to know in which field I have to insert the ```map(name)``` according to association options in Modelio as in the picture below (Association name for the field under the yellow tip)
![screen shot 2015-07-23 at 8 22 48 pm](https://cloud.githubusercontent.com/assets/2465770/8864478/b11c4a5c-3178-11e5-8497-1f599a514d10.png)

Thank you.

**Comment by CarlKlagba** [comment]
Simply put it in 'Role', like you would if you wanted to change the 'relationshipName'

**Comment by marcelinobadin** [comment]
Great! Thank you. It work very smoothly. I will take this opportunity to thank you for your work. This tool really saves me too many work hours!

**Comment by CarlKlagba** [comment]
We are very happy you like it, and that it saved you a lot of time!
