### ISSUE TITLE
After model relationchip updates

### ISSUE THREAD

**Issue by lubo08** [jhipster/jhipster-uml#36]
HI.

Would be nice if you will be able enhance model regeneration.  If I add additional relations between entities model is updated or overwrite,  but order of entities in liquibase is not changed so database initialization failed. Just reorder this based on new model relationships. 
thanks.

**Comment by CarlKlagba** [comment]
I think that this issue was corrected with the 1.1.3 https://github.com/jhipster/jhipster-uml/releases/tag/1.1.3.
Try to update and tell us if everything works.
