### ISSUE TITLE
Carriage return problem

### ISSUE THREAD

**Issue by slucky31** [jhipster/jhipster-uml#38]
The generation failed with Windows Carriage Return (CR+LF) but succeeded with Unix Carriage return (LF).

Error with the Windows carriage return config file : 
```
C:\Dev\ComicsMan\comicsman-admin>jhipster-uml comicsManAdminWindows.jh
Expected "}", a field name or a space but "\r" found.
undefined
```

**Comment by CarlKlagba** [comment]
I have publish a fix. Update your JHipster-UML package.
