### ISSUE TITLE
"required" in Relationship in JDL file

### ISSUE THREAD

**Issue by phouverneyuff** [jhipster/jhipster-uml#39]
Currently we don't have one way to set one relationship required.

relationship ManyToOne{
    EntityA{entityB} to EntityB{entityA}
}

e.g.: EntityB is required when save EntityA.

**Comment by MathieuAA** [comment]
Hi. Unless I misunderstand what you're saying, there's no way to achieve that in JHipster with the questions. So that's normal it's not implemented in JHipster-UML.

**Comment by MathieuAA** [comment]
I update this thread because there _might_ be some work on the issue, [here](https://github.com/jhipster/generator-jhipster/issues/1859). When the corresponding JHipster thread is updated, I'll update this thred here (but still leaving it closed for the moment).

**Comment by amz** [comment]
jhipster supports "required" on relations from 3.2.0. Can this be achieved with jdl?

**Comment by MathieuAA** [comment]
Hi! With the JDL yes, and it is already supported.
However, this is not the place to ask such a question (wrong project, wrong way of doing that). Please open an issue in the JHipster Core project page (as it deals with the JDL) if you have any question related to the JDL in the future, thanks.
