### ISSUE TITLE
One way relationship problem

### ISSUE THREAD

**Issue by augurpl** [jhipster/jhipster-uml#41]
Hi All.
I've designed model that contains many One-way relationships.  I tried to generate from XMI jhipter files but I got error:
Found the .jhipster/PersonalDetails.json configuration file, automatically generating the entity
The entity PersonalDetails is being created.
WARNING otherEntityRelationshipName is missing in .jhipster/PersonalDetails.json for relationship with id 2, using personalDetails as fallback
ERROR otherEntityField is missing in .jhipster/PersonalDetails.json for relationship with id 2

Found the .jhipster/Attendee.json configuration file, automatically generating the entity
The entity Attendee is being created.
WARNING otherEntityRelationshipName is missing in .jhipster/Attendee.json for relationship with id 1, using attendee as fallback
ERROR otherEntityField is missing in .jhipster/Attendee.json for relationship with id 1

This is part of my model: https://api.genmymodel.com/projects/_5tUAkDooEeWMccEXBUwABA/diagrams/_5tV1wzooEeWMccEXBUwABA/jpeg

I'm not sure if I'm doing something wrong, or jhipster doesn't support this kind of relationship. 

Oh, and I'm using jhipster v2.19.0 installed from npm, and latest snapshot of jhipster-uml from github.

**Comment by CarlKlagba** [comment]
If you look issue #40, we are currently having compatibility issues  with the latest JHipster version. Due to time constraints it wont be fixed before 1 or 2 days. For know, try to use the version 2.18.0 or before. If you use the jhipster-uml from github make sure to use the master branch.

**Comment by MathieuAA** [comment]
The problem should be solved with 9119064, can you try?

**Comment by augurpl** [comment]
Thanks for your response. I'll try today in the evening and let you know.

**Comment by andidev** [comment]
There is still a bug out there if you are using the dto option see #1819 for progress on that but.

**Comment by augurpl** [comment]
Ok, problem solved. Entities have been generated properly. 

I didn't try with dto for now but I planned to use them in future. I'll monitor the issue you mentioned.

Thanks
