### ISSUE TITLE
Filter cannot find symbol: variable filter

### ISSUE THREAD

**Issue by alfredorueda** [jhipster/jhipster-uml#43]
Sorry maybe this issue must be reported here: https://github.com/jhipster/generator-jhipster/issues/1854

**Comment by CarlKlagba** [comment]
We had a issue like this, see #40. Now it should work.
On what JHipster-UML and JHipster version are you on? Try to update to the latest.
I am closing it for now, tell us if everything works ok.

**Comment by andidev** [comment]
This is a bug in jhipster generator that will be fixed next release. It occurs when you have an Entity with two one to one relationships where one is owner and the another one is not. See generator-jhipster #1854 how to fix this problem in the code.

**Comment by MathieuAA** [comment]
@alfredorueda Thanks for reporting it in JHipster-UML! This can be quite helpful for people having the same issue and thinking of getting help here.
