### ISSUE TITLE
Transfer UML attribute or class comments to source code of generated entities

### ISSUE THREAD

**Issue by mkresse** [jhipster/jhipster-uml#46]
Hi there,

the XMI format allows the definition of comments for classes or attributes (via the &lt;ownedComment&gt; element). When using the jhipster-uml generator, it would be great if the generator would recognize such comments and include them as javadoc comment in the generated entity class.
This way, the UML model could be used not only as model for the generator, but also as documentation of the entity model.

**Comment by MathieuAA** [comment]
Hi!

That's a pretty good idea! But that's the good part =).
Here comes the bad one: my main concern is that JSON can't have any comment.

We rely too much on the JSON dumped (and consumed) by JHipster that it would be pretty hard, if not impossible, to achieve this.
That being said, if JHipster could take another format as input, or another form of input...
The comments could be added directly to the templates.

Let's have the input of the JHipster 6 @jdubois, @andidev, @deepu105, @gmarziou, @atomfrede, @gzsombor on this.

**Comment by deepu105** [comment]
We can have the comment text as an optional parameter for the json and that
will be easier to handle so that in Jhipster templates you just need to
print it in a comment block

**Comment by andidev** [comment]
@deepu105 suggestion gives a minimal impact on the generator so I say this is doable if wanted. 
I could implement this in jhipster if wanted though I would like to have an example of where the comments should be placed and how they should look. I guess as javadoc comments for class and field? Not sure how to handle linebreaks though. Any suggestions on that?

**Comment by mkresse** [comment]
@andidev Regarding the question if this feature is wanted enough: I think it would be a very useful feature and I would definitely use it. However I have no idea, how the majority of the jhipster-uml users utilize the software and whether it would support their workflow.

Regarding the implementation: class comments appear directly within the packagedElement class, an example produced by Modelio 3.3 looks like:

```xml
    <packagedElement xmi:type="uml:Class" xmi:id="_lZ6hZkyUEeWd98JY82OrEw" name="MyCoolClass">
        <ownedComment xmi:type="uml:Comment" xmi:id="_lZ6hZ0yUEeWd98JY82OrEw">
            <body>&lt;p&gt;This class represents the Magna ligula pellentesque. Lacus ut sed. Himenaeos litora et posuere. Accumsan purus inceptos. Ultricies praesent metus. /* Fames odio quam. */&lt;/p&gt;&lt;p&gt;TODO:&lt;/p&gt;

                &lt;ul&gt;
                &lt;li&gt;first &amp;uuml;ber&lt;/li&gt;
                &lt;li&gt;second&lt;/li&gt;
                &lt;/ul&gt;
            </body>
        </ownedComment>
    </packagedElement>
```
The body element contains plain html, which could be used as class comment without much modification (xml entity decoding assumed):

```java
/**
 * <p>This class represents the Magna ligula pellentesque. Lacus ut sed. Himenaeos litora et posuere. Accumsan purus inceptos. Ultricies praesent metus. &#47;* Fames odio quam. *&#47;</p><p>TODO:</p>
 *
 * <ul>
 * <li>first &uuml;ber</li>
 * <li>second</li>
 * </ul>
 */
@Entity
@Table(name = "MYCOOLCLASS")
public class MyCoolClass {
```

New lines should be prefixed with " * " for nicer code layout and "*/" or in general slashes should be escaped using corresponding entity (&amp;#47;). Since line breaking is recommended (http://www.oracle.com/technetwork/articles/java/index-137868.html), due to html being insensitive to line feeds, a simple word wrap algorithm could be used:

```java
/**
 * <p>This class represents the Magna ligula pellentesque. Lacus ut sed. Himenaeos
 * litora et posuere. Accumsan purus inceptos. Ultricies praesent metus. &#47;*
 * Fames odio quam. *&#47;</p><p>TODO:</p>
 *
 * <ul>
 * <li>first &uuml;ber</li>
 * <li>second</li>
 * </ul>
 */
```

Attribute comments appear within &lt;ownedAttribute&gt; elements and should probably be transferred as a comment of the field declaration. Generally I suppose the same rules would apply. Maybe, since Modelio puts even on liners within &lt;p&gt; elements, stripping of enclosing paragraph elements might be a good idea?

**Comment by MathieuAA** [comment]
@mkresse yes, parsing the comments from modelio XMI files seems easy, but don't forget the others!
If JHipster adds the support for comments, then JHipster-UML will too. It's an option worth the work.

**Comment by andidev** [comment]
So jhipster support for javadoc comments is ready to be merged! see PR jhipster/generator-jhipster#1952 for an example of how the json should look like and what will be generated.

**Comment by MathieuAA** [comment]
Ok! It should be ready next week in JHipster-UML (I hope so anyway, if we have time).
Great work by the way!

**Comment by mkresse** [comment]
Wow, this looks really great - can't wait to try it out. Thanks a lot for your work.

**Comment by MathieuAA** [comment]
Work is being done [here](https://github.com/jhipster/jhipster-uml/tree/commenting-impl). The branch should be merged before the end of the week.

**Comment by MathieuAA** [comment]
@mkresse, @andidev  The comments are available in JHIpster-UML's branch 'commenting-impl'. You can try it and make comments about implementation issues.

**Comment by MathieuAA** [comment]
Closing this thread as the comment support has been added to JHipster-UML, the documentation will soon be updated too.
