### ISSUE TITLE
The DSL parser is not returning a valid object

### ISSUE THREAD

**Issue by andresfuentes** [jhipster/jhipster-uml#48]
Method DSLParser.prototype.parse = function()

Doesn't has a return value, also I noticed that the constructor is not calling 

AbstractParser.call(this, root, databaseTypes);

When using this parser the entitycreator fails when trying to call 

this.parsedData.getClass(classId)

due getClass is not part of the object

**Comment by MathieuAA** [comment]
I may have broken this parser... I'll try to fix it as soon as I get back to my computer.

**Comment by MathieuAA** [comment]
I committed a fix for this. I'm not making a release out of it yet, as I want to fix a few remaining bugs before releasing a new version.
Can you check if the problem's solved for you?

**Comment by andresfuentes** [comment]
yea.. it worked.. no errors this time. good job.
