### ISSUE TITLE
TypeError: Object.keys called on non-object

### ISSUE THREAD

**Issue by myspivey** [jhipster/jhipster-uml#49]
Trying to generate paginated objects off a Visual Paradigm UML. Getting the error TypeError: Object.keys called on non-object.

**Comment by MathieuAA** [comment]
I'll work on this as soon as I get back to my computer. Could you pass your XMI file so that I can reproduce the issue?

**Comment by MathieuAA** [comment]
Just tested the generation, and did not encounter any problem. Really need your XMI file so that I can test.

**Comment by myspivey** [comment]
This has been emailed to you just now. Thanks!

On Fri, Sep 4, 2015 at 1:25 PM, Mathieu ABOU-AICHI <notifications@github.com

**Comment by MathieuAA** [comment]
I didn't have your error, but had another one instead... I don't yet know whether it's because of the diagram, or the parser. I'll keep this thread updated.

**Comment by MathieuAA** [comment]
First, I didn't have your error (try to update JHipster-UML if you can).
I have found an error in the diagram: the TruckCompany class can't have two fields (here they are injected fields) named the same (companys), but of different types.

**Comment by MathieuAA** [comment]
I'll release a new version. Update and try that one. It should make your problem disappear.

**Comment by MathieuAA** [comment]
I will close this thread tonight after testing the latest modifications, and make a patch release out of it.

**Comment by geraldhumphries** [comment]
Having the same issue with a Modelio XMI when using the -paginate option, on master. I will open a pull request.
