### ISSUE TITLE
jhipster-uml issues

### ISSUE THREAD

**Issue by fernandoaugusto** [jhipster/jhipster-uml#51]
Hello!

I am trying this simple example and it is not working. 
The error message is attached.

thanks in advance

******************************Entities design**********************************************
entity Ficha{
  cpf Integer,
  nome String,
  processoCPJ Integer
}

entity Reclamada{
  nome String
}

relationship OneToOne{
  Ficha{reclamada} to Reclamada{ficha}
}

***********************ERROR MESSAGE ***********************************************

Cannot read property 'classes' of undefined
TypeError: Cannot read property 'classes' of undefined
    at Object.<anonymous> (C:\Users\FERNANDO\AppData\Roaming\npm\node_modules\jhipster-uml\jhipster-uml.js:72:27)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by CarlKlagba** [comment]
Looks like a JDL parsing issue. I will check it later today.

**Comment by MathieuAA** [comment]
A fix has been released, can you try it?

**Comment by MathieuAA** [comment]
I will close this thread tonight after testing the latest modifications, and make a patch release out of it.

**Comment by fernandoaugusto** [comment]
Hello, I have tested. Now an error message was thrown. But the message is OK because it says about relationships in MongoDB. So you can close the ticket. Thanks a lot!
