### ISSUE TITLE
Generate unidirectional jhipster relationships

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-uml#55]
In one-to-many/many-to-one relationships, JHipster-uml maps UML unidirectional relationships to JHipster bidirectional relationships (both many-to-one and one-to-many get generated)
As JHipster supports unidirectional relationships, it should be possible to only generate one side of the relationship. For instance if there is no "role" name on one side of the relationship in the diagram ?

**Comment by MathieuAA** [comment]
Hi again, this should has been implemented quite a long time ago... I'll check if this is a regression.

**Comment by MathieuAA** [comment]
My bad! This isn't completely handled (he names are, so that could speed up the work for us).
I don't know when this could be implemented, but we'll try to make it available with the next release.

**Comment by MathieuAA** [comment]
The implementation will be available in a parallel branch for a while, so that we can test it.
When everything's in order, we will merge it with the master branch.

**Comment by MathieuAA** [comment]
The implementation will be available in a parallel branch for a while, so that we can test it.
When everything's in order, we will merge it with the master branch.
The only remaining task is to define the syntax for the DSL. The branch could be merged tonight or tomorrow.

**Comment by MathieuAA** [comment]
This is the implementation Carl and I have chosen.
Provided `Toto` and `Titi` are our two entities, doing: 
```
relationship OneToOne {
  Toto{titi} to Titi {toto}
}
```
will result in creating a O2O association between the two, and the injected field in each are `toto` and `titi`.

Doing:
```
relationship OneToOne {
  Toto{} to Titi {}
}
```
will have the same result.

However, doing:
```
relationship OneToOne {
  Toto{titi} to Titi
}
```
will create a field `titi` in `Toto`, but not in `Titi`.
Note that this is equivalent to:
```
relationship OneToOne {
  Toto{} to Titi
}
```

**Comment by MathieuAA** [comment]
The code is ready to be merged (and should be so anytime soon).

**Comment by cbornet** [comment]
Hello @MathieuAA, this seems still not supported in the UML editors (modelio, ...). Could we have support in them also ?

**Comment by MathieuAA** [comment]
I tested it and it seemed done. I'll reopen it in the meantime, but did you upgrade?

**Comment by cbornet** [comment]
Maybe I didn't set it up correctly in modelio.
Here is a schema I was expecting to give unidir relationship in JHipster
![company_employee](https://cloud.githubusercontent.com/assets/11633333/10510513/cef4efd2-7333-11e5-87bc-48801521e95a.png)
![company_employee2](https://cloud.githubusercontent.com/assets/11633333/10510584/34eb15be-7334-11e5-9d6f-dac760296078.png)

**Comment by cbornet** [comment]
Exported xmi (modelio)

```xml
<?xml version="1.0" encoding="UTF-8"?><uml:Model xmlns:uml="http://www.omg.org/spec/UML/20110701" xmlns:xmi="http://schema.omg.org/spec/XMI/2.1" xmi:version="2.1" xmi:id="_hQyM8HMjEeWOi6s9FoL8tQ" name="simplerelationship">
  <eAnnotations xmi:id="_hQyM8XMjEeWOi6s9FoL8tQ" source="Objing">
    <contents xmi:type="uml:Property" xmi:id="_hQyM8nMjEeWOi6s9FoL8tQ" name="exporterVersion">
      <defaultValue xmi:type="uml:LiteralString" xmi:id="_hQyM83MjEeWOi6s9FoL8tQ" value="3.0.0"/>
    </contents>
  </eAnnotations>
  <packagedElement xmi:type="uml:Class" xmi:id="_hQyM9HMjEeWOi6s9FoL8tQ" name="Company">
    <ownedAttribute xmi:type="uml:Property" xmi:id="_hQyM9XMjEeWOi6s9FoL8tQ" name="Name" visibility="public" isUnique="false">
      <type xmi:type="uml:PrimitiveType" href="http://www.omg.org/spec/UML/20110701/PrimitiveTypes.xmi#String"/>
    </ownedAttribute>
  </packagedElement>
  <packagedElement xmi:type="uml:Class" xmi:id="_hQyM9nMjEeWOi6s9FoL8tQ" name="Employee">
    <ownedAttribute xmi:type="uml:Property" xmi:id="_hQyM93MjEeWOi6s9FoL8tQ" name="company" visibility="public" type="_hQyM9HMjEeWOi6s9FoL8tQ" association="_hQyM-nMjEeWOi6s9FoL8tQ">
      <lowerValue xmi:type="uml:LiteralInteger" xmi:id="_hQyM-HMjEeWOi6s9FoL8tQ"/>
    </ownedAttribute>
    <ownedAttribute xmi:type="uml:Property" xmi:id="_hQyM-XMjEeWOi6s9FoL8tQ" name="Name" visibility="public" isUnique="false">
      <type xmi:type="uml:PrimitiveType" href="http://www.omg.org/spec/UML/20110701/PrimitiveTypes.xmi#String"/>
    </ownedAttribute>
  </packagedElement>
  <packagedElement xmi:type="uml:Association" xmi:id="_hQyM-nMjEeWOi6s9FoL8tQ" memberEnd="_hQyM93MjEeWOi6s9FoL8tQ _hQyM-3MjEeWOi6s9FoL8tQ">
    <ownedEnd xmi:type="uml:Property" xmi:id="_hQyM-3MjEeWOi6s9FoL8tQ" visibility="public" type="_hQyM9nMjEeWOi6s9FoL8tQ" association="_hQyM-nMjEeWOi6s9FoL8tQ">
      <upperValue xmi:type="uml:LiteralUnlimitedNatural" xmi:id="_hQyM_HMjEeWOi6s9FoL8tQ" value="*"/>
      <lowerValue xmi:type="uml:LiteralInteger" xmi:id="_hQyM_XMjEeWOi6s9FoL8tQ"/>
    </ownedEnd>
  </packagedElement>
</uml:Model>
```

**Comment by cbornet** [comment]
I verified that I am up-to-date : setBidirectionalRelationship() gets called

**Comment by MathieuAA** [comment]
I see! I'll fix it tonight if I can, or tomorrow.

**Comment by MathieuAA** [comment]
We have some trouble with many to ones. I don't know how long it'll take

**Comment by MathieuAA** [comment]
I've just fixed the problem with the parser (Modelio's). I'm going to commit the fix so that you can test it. In the meantime, I'll kill the bug in the other parsers.

**Comment by MathieuAA** [comment]
Oh and by the way, using associations (not composition and not aggregation in this case) isn't officially supported by JHipster-UML as this kind of generic association hasn't been tested. If it works, good for you, but I strongly recommend that you don't use it. It's purely a logical debate, so I won't write a novel here, but it's better to specify which association you want to have.

**Comment by MathieuAA** [comment]
I tested every editor and each one of them, except UML Designer, supports some kind of unidirectionality (I'll update the doc very soon). JHipser-UML generates unidirectionals for three editors (4 if you count the DSL, but it's not an editor).
I noticed an issue with Visual Paradigm's XMI file, and I'll try to determine what's causing it. The editor is still usable, but doesn't properly handles bidirectionality (jobs <-> tasks in our Oracle's HR model).

I'm closing this one and opening a new one about this last point.

**Comment by cbornet** [comment]
@MathieuAA I now have an issue with the following Modelio diagram (sorry last time for the missing composition, it was not intentionnal)
![company_employee3](https://cloud.githubusercontent.com/assets/11633333/10604267/884d1124-7723-11e5-9787-6e9543fbb584.png)

Some fields are missing:
```bash
Found the .jhipster/Company.json configuration file, automatically generating the entity
The entity Company is being created.
ERROR relationshipType is missing in .jhipster/Company.json for relationship with id 1


Found the .jhipster/Employee.json configuration file, automatically generating the entity
The entity Employee is being created.
WARNING otherEntityField is missing in .jhipster/Employee.json for relationship with id 1, using id as fallback
```

**Comment by MathieuAA** [comment]
Can you pass your JSONs please?

**Comment by cbornet** [comment]
Company.json
```json
{
  "relationships": [
    {
      "relationshipId": 1,
      "relationshipName": "employee",
      "relationshipFieldName": "employee",
      "otherEntityName": "Employee"
    }
  ],
  "fields": [
    {
      "fieldId": 1,
      "fieldName": "Name",
      "fieldType": "String"
    }
  ],
  "changelogDate": "20151015082954",
  "dto": "no",
  "pagination": "no"
}
```
Employee.json
```json
{
  "relationships": [
    {
      "relationshipId": 1,
      "relationshipName": "company",
      "relationshipFieldName": "company",
      "otherEntityName": "Company",
      "relationshipType": "many-to-one"
    }
  ],
  "fields": [
    {
      "fieldId": 1,
      "fieldName": "Name",
      "fieldType": "String"
    }
  ],
  "changelogDate": "20151015082954",
  "dto": "no",
  "pagination": "no"
}
```
XMI
```xml
<?xml version="1.0" encoding="UTF-8"?><uml:Model xmlns:uml="http://www.omg.org/spec/UML/20110701" xmlns:xmi="http://schema.omg.org/spec/XMI/2.1" xmi:version="2.1" xmi:id="_gC8sQHcSEeWR56i1TSqTpQ" name="simplerelationship">
  <eAnnotations xmi:id="_gC8sQXcSEeWR56i1TSqTpQ" source="Objing">
    <contents xmi:type="uml:Property" xmi:id="_gC8sQncSEeWR56i1TSqTpQ" name="exporterVersion">
      <defaultValue xmi:type="uml:LiteralString" xmi:id="_gC8sQ3cSEeWR56i1TSqTpQ" value="3.0.0"/>
    </contents>
  </eAnnotations>
  <packagedElement xmi:type="uml:Class" xmi:id="_gC8sRHcSEeWR56i1TSqTpQ" name="Company">
    <ownedAttribute xmi:type="uml:Property" xmi:id="_gC8sRXcSEeWR56i1TSqTpQ" name="Name" visibility="public" isUnique="false">
      <type xmi:type="uml:PrimitiveType" href="http://www.omg.org/spec/UML/20110701/PrimitiveTypes.xmi#String"/>
    </ownedAttribute>
  </packagedElement>
  <packagedElement xmi:type="uml:Class" xmi:id="_gC8sRncSEeWR56i1TSqTpQ" name="Employee">
    <ownedAttribute xmi:type="uml:Property" xmi:id="_gC8sR3cSEeWR56i1TSqTpQ" name="company" visibility="public" type="_gC8sRHcSEeWR56i1TSqTpQ" aggregation="composite" association="_gC8sSncSEeWR56i1TSqTpQ">
      <lowerValue xmi:type="uml:LiteralInteger" xmi:id="_gC8sSHcSEeWR56i1TSqTpQ"/>
    </ownedAttribute>
    <ownedAttribute xmi:type="uml:Property" xmi:id="_gC8sSXcSEeWR56i1TSqTpQ" name="Name" visibility="public" isUnique="false">
      <type xmi:type="uml:PrimitiveType" href="http://www.omg.org/spec/UML/20110701/PrimitiveTypes.xmi#String"/>
    </ownedAttribute>
  </packagedElement>
  <packagedElement xmi:type="uml:Association" xmi:id="_gC8sSncSEeWR56i1TSqTpQ" memberEnd="_gC8sR3cSEeWR56i1TSqTpQ _gC8sS3cSEeWR56i1TSqTpQ">
    <ownedEnd xmi:type="uml:Property" xmi:id="_gC8sS3cSEeWR56i1TSqTpQ" name="employee" visibility="public" type="_gC8sRncSEeWR56i1TSqTpQ" association="_gC8sSncSEeWR56i1TSqTpQ">
      <upperValue xmi:type="uml:LiteralUnlimitedNatural" xmi:id="_gC8sTHcSEeWR56i1TSqTpQ" value="*"/>
      <lowerValue xmi:type="uml:LiteralInteger" xmi:id="_gC8sTXcSEeWR56i1TSqTpQ"/>
    </ownedEnd>
  </packagedElement>
</uml:Model>
```

**Comment by MathieuAA** [comment]
I'll fix it tonight if I have time. Thanks!

**Comment by MathieuAA** [comment]
I knew this case reminded me of something! This can't be done. JHipster detects that you want to do a Many-to-One with an entity that doesn't exist (in the Q&A), and warns you (rightly so if I might add).
I suggest you read this fantastic doc [here](https://jhipster.github.io/managing_relationships.html). That's what I'm going to do anyway =)

**Comment by cbornet** [comment]
Oh, you're right ! Thanks for pointing that out. I reversed the relationship and now it works perfectly. 
This is awesome : I now generate the exact same json files that I had produced with the yeoman gen. Great work !

**Comment by cbornet** [comment]
Do you think you could update the [UML file chapter](https://jhipster.github.io/jhipster_uml.html#umlfile) of the doc with example schemas for unidir one-to-many and unidir many-to-one (the one-to-many already in the doc is the bidir) ?

**Comment by MathieuAA** [comment]
Yes, but not today! I'll do it friday or during the week-end. Good idea =)
