### ISSUE TITLE
Spring Data DAO Generator support

### ISSUE THREAD

**Issue by Rapster** [jhipster/jhipster-uml#60]
Hi Mat,

Do you think it would be possible to generate Spring Data Daos? I got inspired by [propel project](http://propelorm.org/) and [JOOQ](http://www.jooq.org/)? For example, if I take the example in example.jh, I would have something like:

```java
public interface IEmployeeDao extends CrudRepository<Employee, Long> {
    public List<Employee> findByFirstName(String firstName);

    public List<Employee> findByLastName(String lastName);

    public List<Employee> findByHireDate(String hireDate);

    public List<Employee> findByHireDateBetween(Date d1, Date d2);

   // other usefull methods
}
```
If I want to customize my DAO I only have to inherits from what has been generated, what do you think?

**Comment by MathieuAA** [comment]
Hi!

I don't think it could be done via the questions asked by JHipster, so that's a no, sorry.
If JHipster implements such a feature, then yes, we would make it possible!

**Comment by jdubois** [comment]
From JHipster point of view: I don't understand the question, as this is already what we generate.

**Comment by Rapster** [comment]
Daos are generated in JHipster? I didn't see this feature in the website tough

**Comment by jdubois** [comment]
I'm sorry but I don't understand... On what website did you go to? This is JHipster-UML, you are probably on the wrong repo.

**Comment by jdubois** [comment]
I'm closing this as this is an invalid ticket, of course

**Comment by Rapster** [comment]
I asked this feature on jhipster-uml because it generates entity by uml diagram. I was wondering if it could do a little bit more: once entities are generated, generate daos.

**Comment by jdubois** [comment]
Yes, but it does -> this is the bug report system, did you read our guidelines? If you just have a general question, you have SO or the chat

**Comment by Rapster** [comment]
Ah yes indeed I use to work XXXDao class and not with XXXRepository class. My bad...
