### ISSUE TITLE
Lossing camelcase

### ISSUE THREAD

**Issue by markvgo** [jhipster/jhipster-uml#68]
I have the latest version of jhipster-uml, when I generate a class that has a relationship with camelcase I lose the capitals. 

This is from my script.jh file

relationship OneToMany{
  BankAccount{bankReconciliation} to  BankReconciliation{bankAccount}
}

This is from the generated BankAccount.json, see how  "otherEntityName" is all lower case

"relationships": [
    {
      "relationshipId": 1,
      "relationshipName": "bankreconciliation",
      "relationshipFieldName": "bankReconciliation",
      "otherEntityName": "bankreconciliation",
      "relationshipType": "one-to-many",
      "otherEntityRelationshipName": "bankAccount"
    }

**Comment by MathieuAA** [comment]
It seems we have a bit of an issue with camelcases at the moment. I'll try to fix it today.

**Comment by MathieuAA** [comment]
I've just pushed a fix for it, can you try it out?

**Comment by markvgo** [comment]
Works now,
Thanks

**Comment by MathieuAA** [comment]
You're welcome
