### ISSUE TITLE
Error running sample testcase umldesigner.uml

### ISSUE THREAD

**Issue by ouyangshixiong** [jhipster/jhipster-uml#72]
**Steps:
Copy umldesigner.uml file from git    basedir/test/xmi/umldesigner.uml into jhipster work dir.
run jhipster-uml  umldesigner.uml
mvn
until now everthing is OK.
Open bowser http://127.0.0.1:8080  loginin with admin account
click entitiy menu, click Employees-->create a new employee.  
No popup dialog,  firefox F12 show this error:
Can you tell me what's the problem is ,thank you very much**
"Error: $scope.manager is undefined
@http://172.17.0.4:8080/scripts/app/entities/employee/employee-dialog.controller.js:20:17
invoke@http://172.17.0.4:8080/bower_components/angular/angular.js:4473:14
instantiate@http://172.17.0.4:8080/bower_components/angular/angular.js:4481:27
$ControllerProvider/this.$get</<@http://172.17.0.4:8080/bower_components/angular/angular.js:9108:18
resolveSuccess@http://172.17.0.4:8080/bower_components/angular-bootstrap/ui-bootstrap-tpls.js:2861:32
processQueue@http://172.17.0.4:8080/bower_components/angular/angular.js:14634:28
scheduleProcessQueue/<@http://172.17.0.4:8080/bower_components/angular/angular.js:14650:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://172.17.0.4:8080/bower_components/angular/angular.js:15878:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://172.17.0.4:8080/bower_components/angular/angular.js:15689:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://172.17.0.4:8080/bower_components/angular/angular.js:15986:13
timeout/timeoutId<@http://172.17.0.4:8080/bower_components/angular/angular.js:17753:25
completeOutstandingRequest@http://172.17.0.4:8080/bower_components/angular/angular.js:5490:7
Browser/self.defer/timeoutId<@http://172.17.0.4:8080/bower_components/angular/angular.js:5762:7
" angular.js:12416:17

"Error: $scope.employee.job is undefined
@http://172.17.0.4:8080/scripts/app/entities/employee/employee-dialog.controller.js:12:17
processQueue@http://172.17.0.4:8080/bower_components/angular/angular.js:14634:28
scheduleProcessQueue/<@http://172.17.0.4:8080/bower_components/angular/angular.js:14650:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://172.17.0.4:8080/bower_components/angular/angular.js:15878:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://172.17.0.4:8080/bower_components/angular/angular.js:15689:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://172.17.0.4:8080/bower_components/angular/angular.js:15986:13
done@http://172.17.0.4:8080/bower_components/angular/angular.js:10511:36
completeRequest@http://172.17.0.4:8080/bower_components/angular/angular.js:10683:7
requestLoaded@http://172.17.0.4:8080/bower_components/angular/angular.js:10624:1
" angular.js:12416:17

**Comment by ouyangshixiong** [comment]
Other entity are OK.

**Comment by MathieuAA** [comment]
This seems like an Angular problem... I can't test it right now but can you paste the console's outputs?
I can't tell whether there's an error without logs.

**Comment by ouyangshixiong** [comment]
I had pasted the firefox console errors.  
I can't find any error in the jhipster backgroup terminal console. It seem all right.
Any idea?
Thank you.

**Comment by ouyangshixiong** [comment]
![error](https://cloud.githubusercontent.com/assets/2086862/10606185/9a40712e-7763-11e5-9c40-466bd8990a93.png)

**Comment by MathieuAA** [comment]
I'll do some tests tonight.

**Comment by MathieuAA** [comment]
I tested it with two separate editors but you're right, it doesn't work with UML Designer.
However, it may be unrelated!
I have the same error when I try to access JobHistories, but the modal does appear... @andidev, do you have an idea?

**Comment by andidev** [comment]
Not sure. Need more info. Is the project public?
At least it would be nice to see how `.jhipster/Employee.json` looks like

**Comment by ouyangshixiong** [comment]
jhipster@141ef562be08:/myshare/empty/.jhipster$ cat Employee.json 
{
  "relationships": [
    {
      "relationshipId": 1,
      "relationshipName": "jobHistory",
      "relationshipFieldName": "jobHistory",
      "otherEntityName": "JobHistory",
      "relationshipType": "one-to-one",
      "ownerSide": false,
      "otherEntityRelationshipName": "employee"
    },
    {
      "relationshipId": 2,
      "relationshipName": "department",
      "relationshipFieldName": "department",
      "otherEntityName": "Department",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipId": 3,
      "relationshipName": "job",
      "relationshipFieldName": "job",
      "otherEntityName": "Job",
      "relationshipType": "one-to-one",
      "otherEntityRelationshipName": "employee",
      "otherEntityField": "id",
      "ownerSide": true
    },
    {
      "relationshipId": 4,
      "relationshipName": "employee",
      "relationshipFieldName": "employee",
      "otherEntityName": "Employee",
      "relationshipType": "one-to-one",
      "otherEntityRelationshipName": "manager",
      "otherEntityField": "id",
      "ownerSide": true
    },
    {
      "relationshipId": 5,
      "relationshipName": "manager",
      "relationshipFieldName": "manager",
      "otherEntityName": "Employee",
      "relationshipType": "one-to-one",
      "ownerSide": false,
      "otherEntityRelationshipName": "employee"
    }
  ],
  "fields": [
    {
      "fieldId": 1,
      "fieldName": "firstName",
      "fieldType": "String"
    },
    {
      "fieldId": 2,
      "fieldName": "lastName",
      "fieldType": "String"
    },
    {
      "fieldId": 3,
      "fieldName": "email",
      "fieldType": "String"
    },
    {
      "fieldId": 4,
      "fieldName": "phoneNumber",
      "fieldType": "String"
    },
    {
      "fieldId": 5,
      "fieldName": "hireDate",
      "fieldType": "DateTime"
    },
    {
      "fieldId": 6,
      "fieldName": "salary",
      "fieldType": "Long"
    },
    {
      "fieldId": 7,
      "fieldName": "comissionPct",
      "fieldType": "BigDecimal"
    }
  ],
  "changelogDate": "20151020112628",
  "dto": "no",
  "pagination": "no",
  "fieldsContainDateTime": true,
  "fieldsContainCustomTime": true,
  "fieldsContainBigDecimal": true
}

**Comment by ouyangshixiong** [comment]
When I try to find a stable,easy modeling tools for jhipster-uml, I find modelio3.4 may has some bugs.
I checkout sample modelio.xmi file from basedir/test/xmi/, then import XMI into an empty project. It reported error like this:
![error2](https://cloud.githubusercontent.com/assets/2086862/10656408/cdf35ab0-78b0-11e5-9c97-19f41fdd124c.png)

**Comment by MathieuAA** [comment]
I've never seen such an issue with Modelio before... You could try UML Designer but it doesn't support constraints and unidirectionality. Every tool that deals with UML class diagrams comes with some flaws, that's why we designed our own DSL. You should try it!

**Comment by andidev** [comment]
This is lost likely a jhipster bug.

Maybe this is related to jhipster/generator-jhipster#2150

Could you please provide the server stacktrace from this error

**Comment by MathieuAA** [comment]
I'm keeping this thread open just in case.

**Comment by MathieuAA** [comment]
I've just pushed a pretty important fix to our entity creator. Care to try it out? To test it, clone this repo, `npm link` it, and try to generate your entities with it. You should have pretty different JSONs.

**Comment by ouyangshixiong** [comment]
Thanks a lot. I'will try it right now.

**Comment by ouyangshixiong** [comment]
I got an error when running command:
node /usr/bin/jhipster-uml jhipster-uml/test/xmi/umldesigner.uml

here is the result:
![jhipster_uml_error1](https://cloud.githubusercontent.com/assets/2086862/10713453/9bbb06e4-7af2-11e5-8f6f-3e3dc2c28797.png)

I'm not sure does the error relate to my local env. 
I will try the fix on another computer later.

**Comment by ouyangshixiong** [comment]
Here is the file Employee.json.
jhipster@e9dff5fc7107:/jhipster$ more .jhipster/Employee.json 
{
  "relationships": [
    {
      "relationshipId": 1,
      "relationshipName": "jobHistory",
      "otherEntityName": "jobHistory",
      "relationshipType": "one-to-one",
      "ownerSide": false,
      "otherEntityRelationshipName": "employee"
    },
    {
      "relationshipId": 2,
      "relationshipName": "department",
      "otherEntityName": "department",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipId": 3,
      "relationshipName": "job",
      "otherEntityName": "job",
      "relationshipType": "one-to-one",
      "otherEntityField": "id",
      "ownerSide": true,
      "otherEntityRelationshipName": "employee"
    },
    {
      "relationshipId": 4,
      "relationshipName": "employee",
      "otherEntityName": "employee",
      "relationshipType": "one-to-one",
      "otherEntityField": "id",
      "ownerSide": true,
      "otherEntityRelationshipName": "manager"
    },
    {
      "relationshipId": 5,
      "relationshipName": "manager",
      "otherEntityName": "employee",
      "relationshipType": "one-to-one",
      "ownerSide": false,
      "otherEntityRelationshipName": "employee"
    }
  ],
  "fields": [
    {
      "fieldId": 1,
      "fieldName": "firstName",
      "fieldType": "String"
    },
    {
      "fieldId": 2,
      "fieldName": "lastName",
      "fieldType": "String"
    },
    {
      "fieldId": 3,
      "fieldName": "email",
      "fieldType": "String"
    },
    {
      "fieldId": 4,
      "fieldName": "phoneNumber",
      "fieldType": "String"
    },
    {
      "fieldId": 5,
      "fieldName": "hireDate",
      "fieldType": "ZonedDateTime"
    },
    {
      "fieldId": 6,
      "fieldName": "salary",
      "fieldType": "Long"
    },
    {
      "fieldId": 7,
      "fieldName": "comissionPct",
      "fieldType": "BigDecimal"
    }
  ],
  "changelogDate": "20151025002411",
  "dto": "no",
  "pagination": "no"
}

**Comment by andidev** [comment]
What version of jhipster are you using? I think that maybe ZonedDateTime is treated as an enum since it is not supported in version 2.22 and that could lead to the stack trace you are seeing. Try to update your jhipster generator version and try again.

**Comment by ouyangshixiong** [comment]
sorry,I don't think jhipster-generator can be update by:
yo-->update-->choose jhipster generator

**Comment by MathieuAA** [comment]
You may have two concurrent versions of JHipster installed... try to git-clone from this repo, npm-link the clone and test it if you can.

**Comment by andidev** [comment]
Strange I think I had the same issue. Not sure how I solved it.  @jdubois do you know how this is possible?

**Comment by jdubois** [comment]
It might be installed several times -> the best way is to install it globally once and for all (like in https://github.com/yeoman/yo ), unless you want to contribute to the project (then it's npm link ...)

**Comment by ouyangshixiong** [comment]
OK，I will try to remove all the installed npm packages on my ubuntu and try it again.
I had tried it on a new macbook,yes,the version is 2.23, as we expected.

**Comment by ouyangshixiong** [comment]
Unfortunately after I update hipster version to 2.23.0 and use git clone hipster-uml on macbook, There is another error occur, like this:
![123](https://cloud.githubusercontent.com/assets/2086862/10812857/387f5024-7e55-11e5-994e-7bd353afc6c3.png)
I try to uninstall hipster old version on ubuntu,I don't think it works. Any idea? I will try it once again later.

**Comment by MathieuAA** [comment]
Is this a blocking error? Does it prevent you from performing a task?

**Comment by ouyangshixiong** [comment]
When I click Create a new Employee ,nothing popup. Only this entity failed,all others are OK

**Comment by ouyangshixiong** [comment]
I had tried to deploy it once again. There are two errors. First one is the one I description above.
Second,the country entity also has a error message. but, it doesn't block me to add a country.

**Comment by MathieuAA** [comment]
Then it might actually be an angulary issue...
