### ISSUE TITLE
latest jhipster-uml does not work on mac

### ISSUE THREAD

**Issue by andidev** [jhipster/jhipster-uml#73]
I'm getting the following error
```
env: node\r: No such file or directory
```

seems to be related to windows style line endings.

The following solved my issue:
http://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo#answer-30349952

**Comment by MathieuAA** [comment]
I'll fix it in a few minutes... but who are the people that still use Macs nowadays?!

**Comment by andidev** [comment]
The awesome ones! :smiley:

**Comment by MathieuAA** [comment]
I don't know what I can do about it. Even though I did the same command as the best answer suggested, git wouldn't detect a change. I will add it as a link in the docs.

**Comment by MathieuAA** [comment]
Please let me know if I forgot something! This kind of issue should not be encountered at all and I still don't understand why you had it.

**Comment by andidev** [comment]
It looks like git manages this by itself. However you can configure git to always use LF line endings according to https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings

**Comment by MathieuAA** [comment]
I'll do it as soon as I can, thanks again!

**Comment by delkant** [comment]
I'm having the same issue.  andidev, can you explain how you made it work more in detail? thanks!

**Comment by andidev** [comment]
I did as told in this StackOverflow answer: 
http://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo#answer-30349952

**Comment by delkant** [comment]
ok, I got it. sudo dos2unix /usr/local/lib/node_modules/jhipster-uml/jhipster-uml.js fixed the problem, thanks.
