### ISSUE TITLE
OneToMany relationship with User entity is ignored

### ISSUE THREAD

**Issue by andidev** [jhipster/jhipster-uml#74]
OneToMany relationship with the User entity is ignored.

The following jdl
```
entity AnEntity {
    aField String
}

relationship OneToMany {
    User{anEntity} to AnEntity{user}
}
```

...generates the follwing jhipster entity.json without the User relationship
```json
{
  "relationships": [],
  "fields": [
    {
      "fieldId": 1,
      "fieldName": "aField",
      "fieldType": "String"
    }
  ],
  "changelogDate": "20151020210726",
  "dto": "no",
  "pagination": "no"
}
```

**Comment by andidev** [comment]
Here is the above example in a [jhipster sample app](https://github.com/andidev/jh/tree/one-to-many-with-user-example) if needed.

Just run `jhipster-uml entities.jh`

**Comment by andidev** [comment]
By the way I tried to flip the relationship to
```
relationship ManyToOne {
     AnEntity{user} to User{anEntity}
}
```
without any success.

**Comment by MathieuAA** [comment]
I'm still trying to fix another issue. You'll have to be patient.

**Comment by MathieuAA** [comment]
I tested your case with the fix and it seems to work.

**Comment by andidev** [comment]
Great! Looking forward of using it.
