### ISSUE TITLE
Problem with generating model from Visual Paradigm when classes are part of package

### ISSUE THREAD

**Issue by augurpl** [jhipster/jhipster-uml#75]
Hi Guys. 
I've prepared model diagram with VP. I tried to generate model  but I got info that no classes are changed and nothing was generated. After few hours of digging I've figured that problem was caused by package that contained all classes. Generator found one object in tree root and it was not class.

**Comment by MathieuAA** [comment]
I'll test it tonight and, hopefuly, fix it right after. Thanks for reporting this!

**Comment by CarlKlagba** [comment]
That message appears when you already generate your model and nothing changed since then.
Try the option "-f" to force jhipster-uml to re-generate  your entities.

**Comment by augurpl** [comment]
I think it's not related with force option. There was nothing generated in .jhipster folder and i got this message. After removing package from my model, classes were properly generated.

**Comment by MathieuAA** [comment]
I'll try to see how to ignore the packages in the parser later today so that you can test it tomorrow I hope.

**Comment by MathieuAA** [comment]
The work needed to bypass packages is a bit more complicated than what I had in mind. Packages are logical layers and anyone can encapsulate a lot of packages before extracting classes... I'll need to come up with a working prototype before closing this thread.
