### ISSUE TITLE
Can't have a custom injected field's name

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-uml#77]
@pacu This is the "sequel" issue of #66.

The diagnosed issue is about generating two entities having a relationship between them so that if entity B is not the owner of this relationship but A is AND A's injected field from B doesn't have the same name as B (for instance B is `ExerciseTip` but the injected field is only `tip`), it fails.

**Comment by MathieuAA** [comment]
I might be wrong, but I don't think JHipster supports this...
I just tried with [this example](https://jhipster.github.io/managing_relationships.html#5), and I changed the question/answer flow by answering like this:

    ? What is the name of this relationship in the other entity? carDriver

@andidev, @CarlKlagba maybe you guys can hopefuly prove me wrong, I might lose my mind over this!

**Comment by MathieuAA** [comment]
I need someone from the JHipster team to confim this ASAP. I won't be able to work next week, and I want to get this closed ASAP too.

**Comment by andidev** [comment]
Not sure if I understand the issue. Maybe it gets more clearer  if you provide a jdl file for the issue.

**Comment by andidev** [comment]
Okey if we look at the Car Driver example from the doc, I can  confirm that setting the name of the relationship in the other entity to carDriver will only work if you also change the relationship name in the other entity to exactly the same name. 
At least this is how it is designed to work.

**Comment by andidev** [comment]
In other words only changing to carDriver will should not work.

**Comment by MathieuAA** [comment]
I'm very sorry Anders if I didn't give any JDL or flow, I assumed #66 would be clear enough... Guess I couldn't be wronger, my bad. Anyway, many thanks for having looked into this.

It should only be a field name... I don't get it, why does it make my tests fail?

**Comment by andidev** [comment]
I'll have a quick look into it

**Comment by andidev** [comment]
Does the test fail in Jhipster or Jhipster UML?

**Comment by MathieuAA** [comment]
JHipster

**Comment by MathieuAA** [comment]
By the way, I didn't use JHipster-UML to generate my .json files. I first tried the usual Q&A just to be sure...

**Comment by andidev** [comment]
Okey, if I use JDL should this one recreate the issue?

```
/**
  Abstract Exercise type. All exercise types have to extend this class
*/
entity Exercise {
  name String required,
  description String required,
  totalScore Integer required min(0)

}

entity ExerciseTip {
  /** the tip itself **/
  hint String required,

  /** further description of the tip itself **/
  tipDetail String

}
relationship ManyToMany {

  Exercise{tip} to ExerciseTip{exercise}
}
```

**Comment by MathieuAA** [comment]
It should. I've tweaked the parser and the entity creator, but you should be able to reproduce the issue.

**Comment by andidev** [comment]
Should I use the master version?

**Comment by MathieuAA** [comment]
Yes

**Comment by andidev** [comment]
Okey so I am a bit confused here I must say,
I'm using the jdl mentioned earlier with no comments:
```
entity Exercise {
  name String required,
  description String required,
  totalScore Integer required min(0)

}

entity ExerciseTip {
  hint String required,
  tipDetail String

}
relationship ManyToMany {
  Exercise{tip} to ExerciseTip{exercise}
}
```

and I get the following entity json files generated in the .jhipster folder:
*Exercise.json*
```
...

  "relationships": [
    {
      "relationshipId": 1,
      "relationshipName": "exerciseTip",
      "otherEntityName": "exerciseTip",
      "relationshipType": "many-to-many",
      "otherEntityField": "id",
      "ownerSide": true
    }
  ],
...
```

and 
*ExerciseTip.json*
```
  "relationships": [
    {
      "relationshipId": 1,
      "relationshipName": "exercise",
      "otherEntityName": "exercise",
      "relationshipType": "many-to-many",
      "ownerSide": false,
      "otherEntityRelationshipName": "exerciseTip"
    }
  ],
```


Shouldn't the result be
*Exercise.json*
```
...

  "relationships": [
    {
      "relationshipId": 1,
      "relationshipName": "tip",
      "otherEntityName": "exerciseTip",
      "relationshipType": "many-to-many",
      "otherEntityField": "id",
      "ownerSide": true
    }
  ],
...
```

and 
*ExerciseTip.json*
```
  "relationships": [
    {
      "relationshipId": 1,
      "relationshipName": "exercise",
      "otherEntityName": "exercise",
      "relationshipType": "many-to-many",
      "ownerSide": false,
      "otherEntityRelationshipName": "tip"
    }
  ],
```

or I'm I too tired or missing something?

**Comment by MathieuAA** [comment]
I think the result should be for _Exercise.json_:

    ...
    
     "relationships": [
        {
          "relationshipId": 1,
          "relationshipName": "exerciseTip",
          "otherEntityName": "exerciseTip",
          "relationshipType": "many-to-many",
          "otherEntityField": "id",
          "ownerSide": true
        }
      ],
    ...

I think I know why, the JHipster-UML parser does have the code to generate the issue, but I commented it out because I wanted to find if I created this issue in the first place or not.
I've just created a branch for you called "issue77" (the tests for this branch don't pass, it's normal).

Try to create the entities with the questions... I don't think the JHipster-UML code is not reliable to find this issue.

**Comment by andidev** [comment]
Are you sure "relationshipName": "exerciseTip" should'n be "relationshipName": "tip" in * Exercise.json* when using the the following jdl relation?

```
relationship ManyToMany {
  Exercise{tip} to ExerciseTip{exercise}
}
```

This makes me really confused :confused: 

I'll try creating it with Jhipster then.

I tried the issue 77 branch and it looks a bit better but still i dont like the "relationshipName": "exerciseTip" in it =)

**Comment by andidev** [comment]
This is how I would answer the questions asked by jhipster entity generator if I would try to model the following jdl relationship
```
relationship ManyToMany {
  Exercise{tip} to ExerciseTip{exercise}
}
```

Entity generation in jhipster:
```bash
$ jhe ExerciseTip
The entity ExerciseTip is being created.
Generating field #1
? Do you want to add a field to your entity? No
=================ExerciseTip=================
Generating relationships with other entities
? Do you want to add a relationship to another entity? Yes
? What is the name of the other entity? Exercise
? What is the name of the relationship? exercise
? What is the type of the relationship? many-to-many
? Is this entity the owner of the relationship? No
? What is the name of this relationship in the other entity? tip

$ jhe Exercise
The entity Exercise is being created.
Generating field #1
? Do you want to add a field to your entity? No
=================Exercise=================
Generating relationships with other entities
? Do you want to add a relationship to another entity? Yes
? What is the name of the other entity? ExerciseTip
? What is the name of the relationship? tip
? What is the type of the relationship? many-to-many
? Is this entity the owner of the relationship? Yes
? When you display this relationship with AngularJS, which field from 'ExerciseTip' do you want to use? id
```

and this sets "relationshipName" to "tip" in the "Exercise.json" entity.

Though when running `mvn test` it fails. This seems to be a JHipster 2.23.0 issue.

**Comment by andidev** [comment]
The same issue is there in JHipster 2.22.0

@jdubois 
Has the generation of the relationship type mentioned in my last comment ever worked in JHipster?

**Comment by MathieuAA** [comment]
Unless I'm wrong, the only mention of "tip" in the JSON files is in _ExerciceTip.json_, in otherEntityRelationshipName. That's what I noticed when answering the questions. Might be wrong though, but your answers do seem valid too. It would be nice to have a doc about it =)
