### ISSUE TITLE
Generate entities in the correct order

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-uml#78]
I have a model with unidirectional many-to-one relationships. The "many" side gets generated before the "owner" side which causes the DB generation to fail when creating the foreign key.

**Comment by cbornet** [comment]
To help, here is a failing modelio schema
![example](https://cloud.githubusercontent.com/assets/11633333/11168744/6780a7f6-8b9d-11e5-9359-dd190cf9e4e4.png)
And the corresponding modelio xmi
```xml
<?xml version="1.0" encoding="UTF-8"?><uml:Model xmlns:uml="http://www.omg.org/spec/UML/20110701" xmlns:xmi="http://schema.omg.org/spec/XMI/2.1" xmi:version="2.1" xmi:id="_8igfcIuSEeW30q1CKp4QZw" name="simplerelationship">
  <eAnnotations xmi:id="_8igfcYuSEeW30q1CKp4QZw" source="Objing">
    <contents xmi:type="uml:Property" xmi:id="_8igfcouSEeW30q1CKp4QZw" name="exporterVersion">
      <defaultValue xmi:type="uml:LiteralString" xmi:id="_8igfc4uSEeW30q1CKp4QZw" value="3.0.0"/>
    </contents>
  </eAnnotations>
  <packagedElement xmi:type="uml:Class" xmi:id="_8igfdIuSEeW30q1CKp4QZw" name="Employee">
    <ownedAttribute xmi:type="uml:Property" xmi:id="_8igfdYuSEeW30q1CKp4QZw" name="company" visibility="public" type="_8igffIuSEeW30q1CKp4QZw" aggregation="composite" association="_8igfeIuSEeW30q1CKp4QZw">
      <lowerValue xmi:type="uml:LiteralInteger" xmi:id="_8igfdouSEeW30q1CKp4QZw"/>
    </ownedAttribute>
    <ownedAttribute xmi:type="uml:Property" xmi:id="_8igfd4uSEeW30q1CKp4QZw" name="Name" visibility="public" isUnique="false">
      <type xmi:type="uml:PrimitiveType" href="http://www.omg.org/spec/UML/20110701/PrimitiveTypes.xmi#String"/>
    </ownedAttribute>
  </packagedElement>
  <packagedElement xmi:type="uml:Association" xmi:id="_8igfeIuSEeW30q1CKp4QZw" memberEnd="_8igfdYuSEeW30q1CKp4QZw _8igfeYuSEeW30q1CKp4QZw">
    <ownedEnd xmi:type="uml:Property" xmi:id="_8igfeYuSEeW30q1CKp4QZw" visibility="public" type="_8igfdIuSEeW30q1CKp4QZw" association="_8igfeIuSEeW30q1CKp4QZw">
      <upperValue xmi:type="uml:LiteralUnlimitedNatural" xmi:id="_8igfeouSEeW30q1CKp4QZw" value="*"/>
      <lowerValue xmi:type="uml:LiteralInteger" xmi:id="_8igfe4uSEeW30q1CKp4QZw"/>
    </ownedEnd>
  </packagedElement>
  <packagedElement xmi:type="uml:Class" xmi:id="_8igffIuSEeW30q1CKp4QZw" name="Company">
    <ownedAttribute xmi:type="uml:Property" xmi:id="_8igffYuSEeW30q1CKp4QZw" name="Name" visibility="public" isUnique="false">
      <type xmi:type="uml:PrimitiveType" href="http://www.omg.org/spec/UML/20110701/PrimitiveTypes.xmi#String"/>
    </ownedAttribute>
  </packagedElement>
</uml:Model>
```
The entities are generated in the order in which they appear in the xmi so this can be workarounded by organizing the order of the class in modelio.

**Comment by MathieuAA** [comment]
Hi, I've fixed it in the code (a very small code addition to the scheduler), so thank you for spotting this!
However, the tests fail:

    Failed tests: 
        CompanyResourceIntTest.getAllCompanys:106 JSON path "$.[*].Name"
        Expected: a collection containing "AAAAA"
            but: 
        CompanyResourceIntTest.getCompany:120 No value at JSON path "$.Name", exception: No results for path: $['Name']

        EmployeeResourceIntTest.getAllEmployees:106 JSON path "$.[*].Name"
        Expected: a collection containing "AAAAA"
        but: 
    EmployeeResourceIntTest.getEmployee:120 No value at JSON path "$.Name", exception: No results for path: $['Name']

    Tests run: 37, Failures: 4, Errors: 0, Skipped: 0

**Comment by cbornet** [comment]
Oh ! JHipster forbids capitalized attribute names. So jhipster-uml should probably do the same

**Comment by MathieuAA** [comment]
Thank you for opening another "issue" ticket, I'll fix it when I can.
