### ISSUE TITLE
I run npm update -g jhipster-uml and nothing is working anymore?

### ISSUE THREAD

**Issue by saminurmi** [jhipster/jhipster-uml#79]
sami$ jhipster-uml -help
env: node\r: No such file or directory

sami$ jhipster-uml ac.xmi -paginate
env: node\r: No such file or directory

What happened and why? Mac OSX El Capitan in environment and path looks like that:
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/sami/.node/bin

This used to work nicely before trying to update jhipster-uml and i tried to re install it as well but no luck.

**Comment by delkant** [comment]
This is a duplicated issue. Take a look here: https://github.com/jhipster/jhipster-uml/issues/73
brew install dos2unix
sudo dos2unix /usr/local/lib/node_modules/jhipster-uml/jhipster-uml.js

**Comment by MathieuAA** [comment]
The problem has been fixed in a commit, but not yet released. I'll make a big release in the week to come, if some issues are solved.
