### ISSUE TITLE
Set pagination and DTO properties per entity

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-uml#85]
Currently, it is only possible to set pagination and DTO globally.
It would be great if we could set it per entity as it is possible in jhipster.

**Comment by jdubois** [comment]
I don't understand: it's already working this way, you set those per entity, not globally

**Comment by jdubois** [comment]
Oups sorry!!! I thought this was on the main project, not JHipster UML!!!

**Comment by MathieuAA** [comment]
Ahah! @cbornet, it is already implemented! Check [this](https://github.com/jhipster/jhipster-uml/blob/master/lib/helper/jhipster_option_helper.js) out.

**Comment by MathieuAA** [comment]
Or [this](http://jhipster.github.io/jhipster_uml.html#usejuml).

**Comment by cbornet** [comment]
Do you think we could have it as properties in the xmi model ?

**Comment by cbornet** [comment]
For instance as a constraint as it is done for fields.

**Comment by MathieuAA** [comment]
I have some reservations about this. For instance, some editors don't handle constraints very well (hello GenMyModel). Another problem (a logical one) is that UML editors are not made for these kind of things...
However, I agree that it would be a very nice thing to have it as an option. I'll see what it would cost to add it, and then I'll try some things.

Thanks for the idea!

**Comment by cbornet** [comment]
Yes I understand your concerns. Actually, the main issue is that the questions are asked each time you generate the model. If you have a lot of entities it is quite painful. Maybe a solution there would be to check if there already exist an Entity.json file in .jhipster and not ask the question for this entity but use the option value that is in it. That way you will be asked only for the new entities. If you want to change an option, remove or edit the Entity.json file.
I also think this way the dto/paginate questions could be asked by default (unless there is no new entity).

**Comment by MathieuAA** [comment]
We could also add this option for the JDL.

**Comment by MathieuAA** [comment]
I checked Modelio, Visual Paradigm and GenMyModel. For all three, I could either specify somehow I wanted a DTO to be generated, or I couldn't simply do it...
I don't think there's an elegant way to specify this kind of information with the editors, so I won't add this, unless there's a pretty way to do it for all 4 editors.

That being said, I'm currently working to add it for the JDL.

**Comment by MathieuAA** [comment]
Quick update:

Here's the grammar changes I made to update the JDL (I'll make a PR in a few minutes for JHipster's wiki).

    entity A {
      name String required
    }

    entity B {}

    entity C {}

    dto A, B with mapstruct

    paginate A, C with infinite-scroll

    paginate B with pager

Notice the use of the keywords `dto`, `paginate` and `with`.
If an option doesn't exist, the user will be told of this error, and the option will be ignored.

**Comment by cbornet** [comment]
@MathieuAA This is great for JDL users. But for the editor users, have you considered my proposal of using the previously selected options when regenerating the model ?

**Comment by MathieuAA** [comment]
I was planning to test some things related to that tonight. Just wanted to get the ugly stuff out of the way.
However, this is still ugly for the editor users as they have to somehow specify their options at least once.
Like I said, I'll test some ideas tonight.

**Comment by MathieuAA** [comment]
I'm closing this thread because editors don't have a good way to do this. I'm going to ease up the option selection however.
