### ISSUE TITLE
Allow entity inheritance in JDL

### ISSUE THREAD

**Issue by wadael** [jhipster/jhipster-uml#96]
Feature request
So that this becomes possible

entity Person  {
  name String required,
  birthDate LocalDate
}

entity Author extends Person  {
  penName String required
}

**Comment by MathieuAA** [comment]
Can't do that sorry!
We'll only implement what is available in JHipster. Inheritance is not _yet_ a thing, so we won't add it _right now_. But be sure that it **will** be added to JHipster-UML as soon as it is supported by JHipster!

By the way, we will most likely use this syntax =)
